### ISSUE TITLE
Failed prop type: The prop `children` is marked as required in `ReactNativeModal`, but its value is `undefined`

### ISSUE THREAD

**Issue by VanessaChu** [react-native-community/react-native-modal#100]
I pasted the code from react-native-modal example into my own. I'm not sure why when I click the button, I get a warning "Failed prop type: The prop `children` is marked as required in `ReactNativeModal`, but its value is `undefined`" and the modal does not show. The example code works on its own but not in my code. 

The warning is shown at 
<Modal isVisible={this.state.visibleModal === 1}>{this._renderModalContent()}</Modal>

Please see attached for code.
[modal_no_work.txt](https://github.com/react-native-community/react-native-modal/files/1605329/modal_no_work.txt)

Warning thrown at line 111

**Comment by mmazzarolo** [comment]
Hello @VanessaChu 
Please try with the example in the README.md, which is even simpler than the one provided in the example dir.

**Comment by jerryheir** [comment]
@VanessaChu , Please how did you get to solve the problem... I'm facing the same thing

**Comment by Dev-Dipesh** [comment]
I received this error when I wrote my render function in a declarative way, but when changed it to function expression, it resolved the issue.

Declarative approach:
```js
_renderModalContent () {
  ...
}
```

Expressive approach:
```js
_renderModalContent = () => {
  ....
}
```

Now, I'm not exactly sure why that is, but maybe it's because of what stated in React docs:

> The [React docs](https://facebook.github.io/react/docs/composition-vs-inheritance.html) say that you can use props.children on components that represent `generic boxes` and that `don’t know their children ahead of time`.

**Comment by bartoszgolebiowski** [comment]
I had a similar problem.
Instead of _Failed prop type: The prop `children` is marked as required in `ReactNativeModal`, but its value is `undefined`_
I had _Failed prop type: The prop `children` is marked as required in `ReactNativeModal`, but its value is `null`_
It was caused because of this null before the last one line.
![image](https://user-images.githubusercontent.com/39523638/56796658-4e5e9700-6813-11e9-8f81-030851b3cc53.png)
I suggest checking the render method, maybe the result is undefined in come cases.

**Comment by rewieer** [comment]
Temporary fix : 

```js
<Modal>
<View>{ this.props.selectedParking ? this.renderModalContent() : null }</View>
</Modal>
```

**Comment by magrinibruna** [comment]
In my case, my <Popup>[empty]</Popup> were empty. After a put some text until configurate the Popup, I stop getting this error.

**Comment by ilkerceng** [comment]
> ```js
> <View>{ this.props.selectedParking ? this.renderModalContent() : null }</View>
> ```

or better with Fragment

    <>{ this.props.selectedParking ? this.renderModalContent() : null }</>

**Comment by csasiyash** [comment]
For me, I changed from : - 

`<Modal
        style={styles.modal}
        isVisible={this.props.ManageSlideUp.isSlideUp}
        {menuItems ? (
          <View style={styles.contents}>
            ...
          </View>
        ) : null}
      </Modal>`

to this : -

`<Modal
        style={styles.modal}
        isVisible={this.props.ManageSlideUp.isSlideUp}
        {menuItems ? (
          <View style={styles.contents}>
            ...
          </View>
        ) : (
          <></>
        )}
      </Modal>`

Just removing **null** with **<></>**
