### ISSUE TITLE
Better documentation? 

### ISSUE THREAD

**Issue by ssashanks** [react-native-community/react-native-modal#101]
This is not a bug/issue. Sorry if I am not using this correctly. 
I am a beginner with react native. The example animated modals are great! (in the sample video), but I discovered that they are not out of the box. I decided to try this only because writing my own modal designs would be a time consuming process. Better 'out of the box' sample code would be really helpful! 

btw, the code under /examples is not self contained atomic examples. The styles are refactored into a style file and code is refactored to render multiple modals in one file.

**Comment by mmazzarolo** [comment]
Hey @ssashanks, thank you for the feedback!
Yeah, I'm aware of the improvements we can make to the docs, I'll try to work on it improve them in my free time. 
In the meanwhile, if you're interested, you can start a pull request that can be used as a starting point for the improvements 👍

**Comment by mmazzarolo** [comment]
In the meanwhile, I updated the README.md 👍
