### ISSUE TITLE
[q] how to use animation provided by react-native-animatable

### ISSUE THREAD

**Issue by garan82** [react-native-community/react-native-modal#107]
I have a quick question. I'm sorry if it sounds silly, I've looked at stackoverflow but did not find anything. So how can I use animation from react-native-animatable with react-native-modal? Specifically, the prop **animationIn** for react-native-modal can be a string or object, I'd like to use an existing animation provided by react-native-animatable, say **bounceIn**. How can I pass bounceIn to react-native-modal?

Thanks!

**Comment by mmazzarolo** [comment]
Just set `animationIn="bounceIn" and you'll be good :)
Example:

```javascript
<Modal 
  isVisible={true} 
  animationIn="bounceIn"
>
   {yourModalContent}
</Modal>
```
