### ISSUE TITLE
Swipe to dismiss not working

### ISSUE THREAD

**Issue by MyGuySi** [react-native-community/react-native-modal#108]
I'm unable to get the swipe to dismiss feature to work at all. Here's my code:

```javascript
  render() {
    return (
      <Modal
        isVisible={this.props.visible}
        onSwipe={() => this.props.onShouldClose()}
        swipeDirection="left"
      >
        {this.renderCard()}
      </Modal>
    );
  }
```

Pretty sure I've followed the instructions correctly but swiping does not work at all, any help would be appreciated :)

**Comment by LouisJS** [comment]
The Swipe Feature is implemented in the [v5.0.0](https://github.com/react-native-community/react-native-modal/releases/tag/v5.0.0-0) release.

Make sure you're using it. By default if you install the package, you'll have the `4.1.1` version.

Checkout PR [#105](https://github.com/react-native-community/react-native-modal/pull/105) in order to have an idea of how to handle the swipe gesture

**Comment by mmazzarolo** [comment]
Thanks @LouisJS 💟

**Comment by MyGuySi** [comment]
That'll probably be the reason 😄 sorry I should have posted versions with the OP, my bad.

Thanks

**Comment by mmazzarolo** [comment]
No worries,
FYI I also just officially release v5.0.0 👍

**Comment by Im-Goutham** [comment]
For me it is not working both in android and ios 
I used like this 
   <Modal
           isVisible={showModal}
           backdropColor='black'
           backdropOpacity='0.20'
           onSwipeThreshold={200}
           swipeDirection='bottom'
           style={styles.bottomModal}
           onSwipe={() => alert('came here')}
           onBackdropPress={() => this.props.closeModal(false)}
           onBackButtonPress={() => this.props.closeModal(false)}
         >

version -> 6.0

**Comment by theohdv** [comment]
In your `onSwipe` method you need to set `showModal` to false in order to hide the modal.

Please refer to the documentation and if you have any problem create an issue instead of writting in this thread.
