### ISSUE TITLE
How to implement a ScrollView inside a Swipeable Modal

### ISSUE THREAD

**Issue by LouisJS** [react-native-community/react-native-modal#109]
I'm using the latest [release](https://github.com/react-native-community/react-native-modal/releases) of react-native-modal that implement the [swipe feature](https://github.com/react-native-community/react-native-modal/pull/105)

I'd like to add a ScrollView inside my modal.

https://snack.expo.io/ryRylJFHz

I'll keep working on this. If you manage to make it work, i'm just right there 😄 

I did also open a [stackoverflow](https://stackoverflow.com/questions/48466314/swipeable-react-native-modal-with-nested-scrollview) issue ⭐️

**Comment by mmazzarolo** [comment]
Hey @LouisJS 
I gave a shot at your expo snack and I'm not sure I fully understand what is the behaviour you expect to obtain 🤔  
I guess you'd like to keep the swipe-down to close feature on the image while still being able to scroll the modal text, am I right? 
I'm not sure it is possible right now because [the panhandlers](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js#L365) that handle the modal swipe gesture is applied to all the modal content. 
Maybe you could try playing a bit with the [gesture responder system](https://facebook.github.io/react-native/docs/gesture-responder-system.html) and with the modal code itself I guess (a good starting point might be [this PR on react-native-modal-box](https://github.com/maxs15/react-native-modalbox/pull/96)).

**Comment by mmazzarolo** [comment]
I'll keep this open, let me know if you make any progress on this 👍

**Comment by greenais** [comment]
I can confirm that SrollView iside RNM works just out of the box - sure, with swipeDirection left or right.
[http://gph.is/2nIDH3N](url)

**Comment by hkwaller** [comment]
I was in the same situation as you @LouisJS - and I did manage to solve it somewhat.

If you put a `<TouchableHighlight />` or one of its siblings inside the child scrollview and make it cover the view, things will magically start working with nested scrolling. 

I tried to implement the PR mentioned by @mmazzarolo but to no avail. Saw a suggestion for touch component somewhere and got it to work in the end. But, as I mentioned, it seems that the `<TouchableWhatever />` needs to be on top in the scroll view and cover it.

**Comment by mmazzarolo** [comment]
Thanks @hkwaller for taking the time to add your suggestion in the thread.

**Comment by LouisJS** [comment]
Could someone provide an example ? I can't manage to reproduce it.
Also, that does looks like a cheap trick to avoid the issue 😄

That would be awesome if `react-native-modal` handled it by default

**Comment by LouisJS** [comment]
Since @theohdv did implement the `Swipe` feature in this lib, maybe he could explain why it happens, and maybe we can try to find a fix for this

**Comment by theohdv** [comment]
I also noticed this issue, the problem is that the `ScrollView` in the modal won't take the touch event (and I don't know how to solve this conflict). It looks that the `panResponder` has more "importance" even if the `ScrollView` is its child. I tried to fix that by adjusting the gesture responder system but I didn't find a good solution.

@hkwaller workaround is working well (it is what I'm doing in my project).

But I agree with @mmazzarolo, a proper solution would be to implement a "swipeTarget" feature (I would love to implement it when I'll have some spare time).

**Comment by LouisJS** [comment]
Can you try to explain us how to implement this workaround starting from https://snack.expo.io/ryRylJFHz ?
I don't know where to put the <TouchableHighlight />

**Comment by hkwaller** [comment]
As far as I know you need it to be on top of the `<ScrollView />` and make sure it covers it. For instance with absolute-positioned style.

**Comment by LouisJS** [comment]
I tried on top of `ScrollView`, as child of `ScrollView`, covering it relative and absolute.
It just doesn't make it.

**Comment by hkwaller** [comment]
I updated the snack, @LouisJS. See the `<TouchableOpacity />` on line 56

Or am I thoroughly misunderstanding what you're trying to do? :)

**Comment by LouisJS** [comment]
Thanks for the snack @hkwaller. But the swipe down is not working anymore then ! 😄 

What i'm trying to achieve is : _Couple the modal swipe down feature with a ScrollView inside._
So when you scroll bottom-up, it scrolls the scrollview.
When you scroll up-down, it scrolls the scrollview until its y position is 0, then if you scroll up-down again, it swipe down the modal.

**Comment by hkwaller** [comment]
ah, gotcha. that sounds like something else.

i would kinda question if that is actually good UX. swiping up/down should in my mind mean similar things. how would you get back up in the scrollview if you scrolled down, without dismissing the modal?

**Comment by mmitchellgarcia** [comment]
@hkwaller  @LouisJS this is a pattern used in the Uber eats app. When you open up a menu item to customize it, a modal pops up. 

- If you swipe bottom to top, it will modal's scroll content like a scroll view. 
- If you scroll top to bottom, and there is no more vertical scrolling to be done, it will drag the modal down to dismiss it. 
- If you scroll top to bottom, and there is vertical scrolling, it will scroll. 

It's little complex, does anyone know if this is possible with `react-native-modal` as it is now? I was able to get really close with a <Touchable> child in the scroll view that I disabled when the <ScrollView /> scrollTop = 0, but it's not smooth. Is it possible to basically preventDefault() on a scroll event, and instead transfer the event to a PanResponder?

**Comment by pistonsky** [comment]
The behavior is absolutely standard - take a look at Apple Music: when you open a song that is currently playing - you can scroll the song, and also swipe the modal away. Once you scroll the song, you can scroll it back, and the modal will not swipe away, no matter how hard you try. But if you start scrolling when it is at scrollTop=0 - you can swipe it away.

I see it in every app I use, it's trending!

**Comment by mmitchellgarcia** [comment]
@pistonsky @LouisJS I was able to do this! I was overthinking it using a PanResponder. You can do this if you have a <ScrollView /> with a transparent background positioned absolutely above the content you'd like to to scroll over. 

```
<Animated.ScrollView
                scrollEventThrottle={16}
                onScroll={this._onScroll.bind(this)}
                onScrollBeginDrag={this._onScrollBeginDrag.bind(this)}
                onScrollEndDrag={this._onScrollEndDrag.bind(this)}
                contentContainerStyle={this.props.contentContainerStyle}
                alwaysBounceVertical={true}
                style={{
                    top: 0,
                    left: 0,
                    right: 0,
                    position: 'absolute',
                    height: Dimensions.get('window').height,
                    backgroundColor: this.state.isTransparentBackground ? 'transparent' : '#fff',
                    transform: [
                        {
                            // this value will animate from Dimensions.get('height') --> 0 on componentDidMount
                            translateY: this.state.cardLocation
                        }
                    ]
                }}
            >
                <View
                    style={{
                        minHeight: Dimensions.get('window').height,
                        // this value will change based on if user is scrolled on scrollview (if contentOffset.y > 0, we want to shadow to disapear)
                        shadowColor: this.state.isTransparentBackground ? '#333' : '#fff',
                        shadowOffset: {
                            height: 0
                        },
                        shadowOpacity: .3,
                        shadowRadius: 10,
                        backgroundColor: '#fff'
                    }}
                >
                    {this.props.children}
                </View>
            </Animated.ScrollView>
```

**Comment by aligfl** [comment]
@mmitchellgarcia the wrapper component, I should be wrapper my children component in your view? and it should work?

**Comment by mmitchellgarcia** [comment]
@aligfl yes, this worked for my case.

**Comment by mmazzarolo** [comment]
This feature should be now available thanks to #149

**Comment by AleksandrZhukov** [comment]
still, have this problem when there is Button or other elements with Touchable component. I found another workaround that works for me 
```
<ScrollView>
  <TouchableOpacity>
    <TouchableWithoutFeedback>
      <View>
        {content here} 
      </View>
    </TouchableWithoutFeedback>
  </TouchableOpacity>
</ScrollView>
```

**Comment by nandorojo** [comment]
For a bit I wasn't able to scroll within the modal. Not exactly sure why this worked, but similar to some of the other solutions, this did the trick for me. I only tried it for a horizontal `ScrollView`.

```
<ScrollView scrollEnabled={false} style={{ flex: 0 }}>
  <ScrollView horizontal>
    <TouchableWithoutFeedback>
      <FlatList 
            horizontal
            ...
       /> // you can put something other than FlatList, but that's what I used here
    </TouchableWithoutFeedback>
  </ScrollView>
</ScrollView>
```

**Comment by Jorundur** [comment]
> still, have this problem when there is Button or other elements with Touchable component. I found another workaround that works for me
> 
> ```
> <ScrollView>
>   <TouchableOpacity>
>     <TouchableWithoutFeedback>
>       <View>
>         {content here} 
>       </View>
>     </TouchableWithoutFeedback>
>   </TouchableOpacity>
> </ScrollView>
> ```

Thanks @AleksandrZhukov! This worked for me when the solutions above had not. I.e. I had a `ScrollView` in a `Modal` (using `react-native-modalbox`) and that `ScrollView` had some content with buttons that needed to be clickable.

I did your solution but substituted `TouchableOpacity` with `TouchableHighlight` so as not to get a visible flash when clicking anywhere in the `ScrollView`

Ended up with:
```jsx
<Modal>
  <View>
    {/* ... */}
    <ScrollView>
      <TouchableHighlight>
        <TouchableWithoutFeedback>
          <View>
            {/*  ... list of items with clickable buttons ... */}
          </View>
        </TouchableWithoutFeedback>
      </TouchableHighlight>
    </ScrollView>
    {/* ... */}
  </View>
</Modal>
```

**Comment by mmazzarolo** [comment]
We can continue discussing this in #236

**Comment by JimTeva** [comment]
For those still looking for an answer, it is now available in the library [here](https://github.com/react-native-community/react-native-modal/blob/master/example/src/modals/ScrollableModal.tsx).

**Comment by drivecrux** [comment]
The Happiness and joy that I felt after being stuck on it for 3 hours.

**Comment by MasterTeus** [comment]
> Para quem ainda está procurando uma resposta, ele já está disponível na biblioteca [aqui.](https://github.com/react-native-community/react-native-modal/blob/master/example/src/modals/ScrollableModal.tsx)

@JimTeva I could adapt it to a functional component using React Hook

**Comment by roxdavirox** [comment]
> I was in the same situation as you @LouisJS - and I did manage to solve it somewhat.
> 
> If you put a `<TouchableHighlight />` or one of its siblings inside the child scrollview and make it cover the view, things will magically start working with nested scrolling.
> 
> I tried to implement the PR mentioned by @mmazzarolo but to no avail. Saw a suggestion for touch component somewhere and got it to work in the end. But, as I mentioned, it seems that the `<TouchableWhatever />` needs to be on top in the scroll view and cover it.

you save me <3

**Comment by asilbekashirov** [comment]
> still, have this problem when there is Button or other elements with Touchable component. I found another workaround that works for me
> 
> ```
> <ScrollView>
>   <TouchableOpacity>
>     <TouchableWithoutFeedback>
>       <View>
>         {content here} 
>       </View>
>     </TouchableWithoutFeedback>
>   </TouchableOpacity>
> </ScrollView>
> ```

Thanks for this solution! Really helped me out, was struggling with this stuff for quite a while :)
