### ISSUE TITLE
backdropOpacity and backdropColor not working

### ISSUE THREAD

**Issue by tronginc** [react-native-community/react-native-modal#110]
Modal from react-native-modal is so good for my old project. But today, i create new app and backdropOpacity and backdropColor not working.

![Issue Image](https://i.imgur.com/YGGGsj9.jpg)

Here is my code:

><Modal
                onBackdropPress = {()=>this.setState({isVisible: false})}
                onBackButtonPress = {()=>this.setState({isVisible: false})}
                visible={this.state.isVisible} onRequestClose = {()=> null}
                style={{marginTop: 56, marginRight: 1, marginLeft: 20, marginBottom:50}}
            >
                <View style={{flex:1, backgroundColor:'white'}}>
                    <View style={{height: 10, flexDirection: 'row', paddingLeft: 10}}>
                        <Text style={{alignSelf: 'flex-start', fontSize: 18}}>Thông báo</Text>
                    </View>
                </View>
</Modal>

so I add 2 props:
`                onSwipe={() => this.setState({ isVisible: false })}
                swipeDirection="up"`

this is working but I must be tap on the Modal.

![Issue Image](https://im4.ezgif.com/tmp/ezgif-4-cce289af36.gif)

> react-native 0.53.0
react-native-modal 5.0.0

please help me

**Comment by toussa** [comment]
Try removing `backgroundColor:'white'`
And set `transparent={true}
        backdropColor="rgba(0,0,0,0.5)"` in modal props

**Comment by mmazzarolo** [comment]
Thanks @toussa

@tronginc what the device are you using? could you try on a nexus/pixel device/simulator?

**Comment by tronginc** [comment]
@mmazzarolo I am testing it on Asus Zenfone Max 6.0.1, Samsung Galaxy Note 5 7.1.1, Emulator : google custom phone 8.0, Zenfone Max 7.1.2
So this didn't work @toussa 
But I add `onSwipe={() => this.setState({ isVisible: false })} swipeDirection="up"`
this is working but I must be tap on the Modal.
https://imgur.com/a/NQSP3

I was trying to create new blank app and add Modal but have same issue!

> react-native 0.53.0 0.52.0 & 0.51.0
react-native-modal 5.0.0

**Comment by mmazzarolo** [comment]
Sorry @tronginc for answering late. 
Could you share the entire code you're using?

**Comment by kodie** [comment]
I also couldn't get the backdrop to work, I ended up doing `<Modal style={{backgroundColor: 'rgba(0,0,0,0.5)'}}>` for the time-being.

**Comment by mmazzarolo** [comment]
Could you share the entire code you're using?
What device are you using for testing?
Does the issue persist when using a different device?

**Comment by kodie** [comment]
Here's the render() and the StyleSheet. I was also unable to get `animationIn` or `animationOut` to work however the native `animationType` works.

Issues persist on an iPhone 8 running iOS 11.2 and also on a Google Pixel XL running Android 8.

react-native v0.52.2
react-native-modal v5.0.1

```javascript
export default class TriggerEditor extends Component {
  render() {
    const typeLocationOpts = (
      <View style={ styles.triggerOptions }>
        <Btn
        align='flex-start'
        style={{ alignSelf: 'flex-start', marginBottom: 20 }}
        onPress={ () => { this._autoFillLocation() } }>Auto Fill Location</Btn>
        <Text style={ styles.text }>Location</Text>
        <TextInput
          style={ styles.textInput }
          value={ this.state.location }
          onChangeText={ text => this.setState({ location: text }) }
          underlineColorAndroid="transparent" />
      </View>
    );

    const typeMotionOpts = (
      <View style={ styles.triggerOptions }>
        <Text style={ [ styles.text, { marginBottom: 20 } ] }>Trigger will happen if your are moving 8 MPH or faster.</Text>
      </View>
    );

    return(
      <Modal
        animationType="fade"
        avoidKeyboard={ true }
        onBackButtonPress={ () => this._cancel() }
        onBackdropPress={ () => this._cancel() }
        style={ styles.modal }
        visible={ this.props.open }>

        <View style={ styles.container }>
          <View style={{ flex: 1, flexDirection: 'row', alignItems: 'flex-end' }}>
            <Text style={ [ styles.text, { flex: 1, flexDirection: 'row' } ] }>Enter your Trigger Name</Text>
            <Btn style={{ flexDirection: 'row' }} onPress={ () => this._cancel() }>Cancel</Btn>
          </View>

          <TextInput
            style={ [ styles.textInput, { flex: 1, flexDirection: 'row' } ] }
            value={ this.state.name }
            onChangeText={ text => this.setState({ name: text }) }
            underlineColorAndroid="transparent" />

          <Text style={ styles.text }>Trigger Type</Text>

          <Select
            data={ [
              { value: 'Location' },
              { value: 'Motion' }
            ] }
            value={ this.state.type || this.props.type }
            onChange={ this._onChangedType } />

          { this.state.type === 'Location' && typeLocationOpts }
          { this.state.type === 'Motion' && typeMotionOpts }

          <Btn
            align='center'
            style={{ backgroundColor: '#47acb9', borderWidth: 0 }}
            onPress={ () => this._save() }>Save Trigger</Btn>
        </View>

      </Modal>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#782651',
    padding: 20,
    position: 'absolute',
    bottom: 0,
    width: '100%'
  },
  modal: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    margin: 0
  },
  textInput: {
    backgroundColor: '#fff',
    borderRadius: 5,
    marginVertical: 20,
    padding: 15
  },
  text: {
    color: '#92bbc9'
  },
  triggerOptions: {
    borderColor: '#9d3470',
    borderTopWidth: 1,
    paddingTop: 20
  }
});

```

**Comment by faizalshap** [comment]
Hey Guys,
I solved the issue by changing the `visible` prop to `isVisible`.

**Comment by cihanbas** [comment]
@toussa 

thank you GREAT Man : )

**Comment by mmazzarolo** [comment]
Ha!  
Yeah, I admit that when I started the repo I should have named the prop `visible` for dodging issues like this... 🤔

**Comment by Bang9** [comment]
@faizalshap  thx, you save me lol

**Comment by v4lerio** [comment]
> I also couldn't get the backdrop to work, I ended up doing `<Modal style={{backgroundColor: 'rgba(0,0,0,0.5)'}}>` for the time-being.

this works on `react-native 0.55.4` and `react-native-modal 6.5.0`

**Comment by alexsoul95** [comment]
@faizalshap solution worked for me !!!

**Comment by abbaxee** [comment]
@faizalshap you just saved my life... Thank you ❤️
