### ISSUE TITLE
[Q] blur background when modal is active

### ISSUE THREAD

**Issue by garan82** [react-native-community/react-native-modal#113]
Current behavior is that the background is darken-ed when modal is visible. I would like to blur the background instead, how can I achieve this? Thanks!

**Comment by mmazzarolo** [comment]
Hi @garan82 , I'm sorry but it is not possible right now. 😞 
To achieve the blur effect we would need something like `react-native-blur`, which being a native module would cause a lot of trouble in its implementation.

**Comment by developer239** [comment]
Doesn't work shouldn't be closed: https://github.com/react-native-community/react-native-modal/issues/445
