### ISSUE TITLE
keyboard not visible after dialog close

### ISSUE THREAD

**Issue by assafb81** [react-native-community/react-native-modal#114]
Hi @mmazzarolo,
I am using react-native-modal v4.1.1 and RN v0.52.

I looked at issue #53 but I still having issues.

I am using Android (in iOS it works fine without `onModalHide`): When my modal dialog is shown the keyboard is hidden - which is the behavior I want.
When the dialog is closed the keyboard never shows up again, even though I am staying in the same screen.

my component that contain the modal dialog looks like this:

```
class ComponentA extends Component {
    constructor(props) {
        super(props);

        this.state = {
            isErrorDialogVisible: false,
        };
    }

    componentWillReceiveProps = (nextProps) => {
        is (nextProps.error) {
            this.setState({
                isErrorDialogVisible: true,
            });
        }
    }

    closeDialog = {
        this.setState({
            isErrorDialogVisible: false,
        })
    }

    render() {
        return(
            <View>
                <TextInput
                    .....
                />
                <Modal
                    isModalVisible={this.state.isErrorDialogVisible}
                    handleClick={this.closeDialog}
                />
            </View>
        )
    }
}
```

and my modal dialog component is something like:
```
export default class ModalDialog extends Component {

    onButtonClick = () => {
        this.props.handleClick();
    }

    render() {
        return(
            <View>
                <Modal
                    isVisible={this.props.isModalVisible}
                >
                    <View>
                        .....
                        <TouchableOpacity onPress={this.onButtonClick}>
                                ....
                        </TouchableOpacity>
                    </View>
                </Modal>
            </View>
        )
    }
}
```

After the dialog closes, I can see that `closeDialog` is called but the keyboard never pops up again?
I tried to tried to regain focus`this.textInput.focus();` in `componentWillUpdate` method but with no luck.

using `onModalHide` method?
Is there a way to call `onButtonClick`  after `onModalHide` is called?

**Comment by mmazzarolo** [comment]
Hey @assafb81, did you already try calling `this.textInput.focus()` in the `onModalHide` callback? 
I don't see any reason for it to not work 🤔 (also, make sure the `focus()` works correctly)

**Comment by assafb81** [comment]
@mmazzarolo 
yep, I tried that
the calling to modal dialog in my component is this:
```

<ModalDialog
  isModalVisible={this.state.isErrorDialogVisible}
  handleClick={this.onDialogClose}
  onModalHide={Platform.OS === 'android' ? this.keyboardFocus : undefined}
/>
```
`keyboardFocus` method is:
```
keyboardFocus = () => {
  setTimeout(() => {
    this.textInput.focus();
  }, 100);
}
```

I tried also without setTimeout, and also `this.textInput.blur()` inside that method.

and in my modal dialog the code is:
```
onModalHide = () => {
  if (this.props.onModalHide) {
    this.props.onModalHide();
  }
}
```

and inside the modal:
```
<Modal
  isVisible={this.props.isModalVisible}
  animationOutTiming={hideDuration}
  onModalHide={this.onModalHide}
>
```

And it did not do the trick

**Comment by mmazzarolo** [comment]
Thanks for the feedback, could you try swapping `react-native-modal` with the react-native original `modal` to see if the issue persists?

**Comment by assafb81** [comment]
@mmazzarolo its involving too much code change
will make me consider not using `react-native-modal`

**Comment by mmazzarolo** [comment]
> will make me consider not using react-native-modal

🤔

**Comment by assafb81** [comment]
please see revise comment

**Comment by mmazzarolo** [comment]
@assafb81 ...why did you delete your posts?

**Comment by assafb81** [comment]
@mmazzarolo 
A big advantage to use the this package is the `onModalHide`.
I solved the issue:

As follows:
```
class ComponentA extends Component {
    constructor(props) {
        super(props);

        this.state = {
            isErrorDialogVisible: false,
        };
    }

    componentWillReceiveProps = (nextProps) => {
        is (nextProps.error) {
            this.setState({
                isErrorDialogVisible: true,
            });
            this.textInput.blur();
        }
    }

    closeDialog = {
        this.setState({
            isErrorDialogVisible: false,
        })
    }

    // method called only in Android
    keyboardFocus = () => {
        setTimeout(() => {
            this.textInput.focus(); 
        }, 100);
    }

    render() {
        return(
            <View>
                <TextInput
                    .....
                />
                <Modal
                    isModalVisible={this.state.isErrorDialogVisible}
                    handleClick={this.closeDialog}
                    onModalHide={Platform.OS === 'android' ? this.keyboardFocus : undefined}
                />
            </View>
        )
    }
}
```
and my modal dialog component is something like:

```
export default class ModalDialog extends Component {

    onModalHide = () => {
        if (this.props.onModalHide) {
            this.props.onModalHide();
        }
    }

    onButtonClick = () => {
        this.props.handleClick();
    }

    render() {
        return(
            <View>
                <Modal
                    isVisible={this.props.isModalVisible}
                    onModalHide={this.onModalHide}
                >
                    <View>
                        .....
                        <TouchableOpacity onPress={this.onButtonClick}>
                                ....
                        </TouchableOpacity>
                    </View>
                </Modal>
            </View>
        )
    }
}
```

I removed bad/wrong comments

**Comment by evanjmg** [comment]
I'm having the same issue, I can't focus on an input after closing the modal

**Comment by rewieer** [comment]
This isn't directly related to `react-native-modal`, but the way Modal works in RN. It seems you cannot have the keyboard out for an input focused behind a modal. And while the modal is closing, *the modal isn't closed yet*, it animates and then close. 

You have to wrap your focus function into a setTimeout and wait for the animation to finish (check the value of the `animationOutTiming`) + a few milliseconds before focusing on the input.

The best I could do is to delay the moment we call onModalHide to the very last moment. We cannot inside the library wrap it into a setTimeout, this would just patch a few use cases and we would have to carry this fix around while it's not supposed to be our problem.

This is addressed in https://github.com/react-native-community/react-native-modal/commit/a032d4d061a2a3d73092e7b42d295e64bf80efa4 and will be shipped in the next release.

**Comment by evanjmg** [comment]
There’s a better workaround. Run InteractionManager.runAfterInteractions(()=>{}) and inside it will be your focus event

**Comment by evanjmg** [comment]
UPDATE: That workaround does not work in all cases. This is still a big issue. I'm having to implement my own modal with Animated.View to get around this
