### ISSUE TITLE
Close modal when android back button pressed

### ISSUE THREAD

**Issue by ShaikhKabeer** [react-native-community/react-native-modal#115]
How to close the modal when android back button is pressed ? please help

**Comment by mmazzarolo** [comment]
Hi,
just se the `isVisible` prop to `false` when the modal's `onBackButtonPress` prop is called.

**Comment by ShaikhKabeer** [comment]
Hey Thanks @mmazzarolo , it's working

**Comment by manjunathpy** [comment]
Hi 

Setting this code in Modal Helped Me Out Close The Modal On Back button Press

onBackButtonPress={() => this.setState({ visibleModal: null })

**Comment by cerib** [comment]
This seems to be outdated. To close the modal on back button press you need to add this prop in the modal:

`onRequestClose={() => { **your code to dismiss the modal** }`


example:

`<Modal
        visible={modalVisible}
        animationType="slide"
        onRequestClose={modalVisibleToggle}
      >`

**Comment by murtuzamacdev** [comment]
Thank you @cerib. It worked with `onRequestClose`

Can someone please update the readme.

**Comment by SanjuGB** [comment]
`onBackButtonPress` doesn't work anymore.

Use this => `onRequestClose={() => displayModal(false)}` instead.

**Comment by CtoStarje** [comment]
use this:

backButtonClose={true}

It works :)

**Comment by MdGolam-Kibria** [comment]
use onRequestClose method and write your logic here  happy codding
<Modal visible={modalVisible} transparent={true} onRequestClose={() => {
                    setModalVisible(false)
 }}>

**Comment by zeeintanzania** [comment]
> Hi, just se the `isVisible` prop to `false` when the modal's `onBackButtonPress` prop is called.

Please see this

Screen 1 (Button) --> onPress Show Modal and Modal has two buttons (Perfectly Working) --> onPress Button Navigate to Screen 2 (Perfectly Working) --> But on Screen 2 onBack  to Screen Screen the Modal is still showing it's needs to be hide. 

What should we do. 
const [visible, setVisible] = React.useState(false);

  const showModal = () => setVisible(true);
  const hideModal = () => setVisible(false);
  const containerStyle = {
    height: "20%",
    width: "100%",
    position: "absolute",
    bottom: 0,
  };

**Comment by Abdulmateenchitrali** [comment]
@cerib Thanks

**Comment by saumya66** [comment]
> use onRequestClose method and write your logic here happy codding <Modal visible={modalVisible} transparent={true} onRequestClose={() => { setModalVisible(false) }}>

this works!

**Comment by nived-cv** [comment]
> Hi, just se the `isVisible` prop to `false` when the modal's `onBackButtonPress` prop is called.

this is not working.... the onBackButtonPress is not executing while android back button is pressed

**Comment by Danu-rxone** [comment]
```
<Modal
      animationType={"fade"}
      transparent={true}
      visible={visible}
      onRequestClose={() => setModalVisible(false)}
    >
```
