### ISSUE TITLE
Allow user interaction with content outside modal

### ISSUE THREAD

**Issue by riwu** [react-native-community/react-native-modal#118]
When a modal is active, the user is not able to interact with contents outside the modal 
(eg. top navigation bar or bottom navigation tabs -- the view below with white background is the modal).

![](https://i.imgur.com/9PIgmjY.png)

Would be good to have a prop on `Modal` to enable this as it provides better UX for some designs.

**Comment by mmazzarolo** [comment]
Hey @riwu 
I think that what you're looking for is not really a modal but just a custom View absolutely positioned  inside your screen.  

From my understanding one of the core concepts of a modal is that the modal itself should overlay all the screen, regardless of its position (feel free to correct me if I am wrong).  

Please notice that under the hood react-native-modal uses [the original react-native modal](https://facebook.github.io/react-native/docs/modal.html).

**Comment by Estebank94** [comment]
I am also interested in this feature.

**Comment by MaxInMoon** [comment]
I don't understand why the backDrop should capture the onPress event (with `hasBackdrop={false}`).
It's really important because the goal to a modal is to be portable (not absolute in a parent)

**Comment by mmazzarolo** [comment]
> I don't understand why the backDrop should capture the onPress event (with hasBackdrop={false}).
Because [the original react-native modal](https://facebook.github.io/react-native/docs/modal.html) (which uses the native modals), which is used by `react-native-modal` doesn't allow it ;/
