### ISSUE TITLE
Add 'hideModalContentWhileAnimating' to typings

### ISSUE THREAD

**Issue by alex-blair** [react-native-community/react-native-modal#121]
I'm using the super helpful `hideModalContentWhileAnimating` prop in a project and I noticed it hasn't been added to the typings yet. 

I'm happy to make a PR for this - let me know! 😸

**Comment by mmazzarolo** [comment]
Yup! Thank you in advance!

**Comment by alex-blair** [comment]
@mmazzarolo I've made a PR 🙂

**Comment by mmazzarolo** [comment]
Great, merged 👍
