### ISSUE TITLE
Trying to react-native-modalbox with your module... 

### ISSUE THREAD

**Issue by juliepwchen** [react-native-community/react-native-modal#123]
Currently, I am using 'react-native-modalbox', but I want to switch to your module 'react-native-modal' because of the 'onSwipe' feature.  But I notice that in 'react-native-modalbox', there is a "backdropContent" prop/feature where you can add an element in the backdrop.  (I am currently using this feature to add a Video background on my Modal.)  Is there anything like this in 'react-native-modal' or is there a way for me to do the same?  Thanks!

**Comment by mmazzarolo** [comment]
I'm sorry but unfortunately this feature is not available (yet) and we don't have any plan on adding it (yet) since it would involve huge changes on the codebase. 😞
