### ISSUE TITLE
Multiple swipeDirection

### ISSUE THREAD

**Issue by matteo-pennisi** [react-native-community/react-native-modal#125]
I was wondering if it is possible to pass multiple swipe directions to Modal.
Right now the modal can receive only one prop. There is a workaround for this or it can be implemented in the future?

Thanks,
Matteo

**Comment by mmazzarolo** [comment]
Hey!  
Yes, I think it might be implemented without too many issues.  
I you're interested in giving it a try by yourself I can give you some hints on what you should do... 
In the meanwhile I'll leave the issue open so that we can track how many people would need a feature like this 👍

**Comment by matteo-pennisi** [comment]
Sure!
I can try to implement this feature :+1: 
 Some suggestions?

**Comment by mmazzarolo** [comment]
Thanks nice! Grazie 💃 

Let's start by saying that the prop `swipeDirection` would accept both a string and an array (for multiple direction). 

Then you should probably modify start taking a look at every line where the prop `swipeDirection` is used in a condition (inside an `if` or `switch`) and edit the interesting part taking into account that now `swipeDirection` can also be an array.  

From a quick look you would probably need to edit: 
- [The `swipeDirection` prop in the proptypes to allow array of directions too](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js#L55)
- [This block](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js#L163-L170) where we checks if we should move the modal [only on the X axis](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js#L167) or only in the [Y axis](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js#L169): with multiple directions allow now there is even another case to add that allows moving on both axes (e.g.: when `swipeDirection={['left', 'down']}`
- [Here](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js#L225) you should also take into account that multiple directions can be used and modify the method accordingly
- [And lastly, the tricky bit is this](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js#L225). Now you should not test anymore the prop `swipeDirection` but instead you should keep track of the direction the user has swiped to.  

Let me know if you have any question! We can also try to ping someone else for suggestions :)

**Comment by matteo-pennisi** [comment]
Ciao Matteo :)
_(Scrivo in inglese perchè magari la conversazione può essere utile a qualcuno)_

I've made some changes as you can see [here](https://github.com/matteo-pennisi/react-native-modal/commit/f53644352f1b9467750f4252f65ba362881424ff).
Now it moves on both axes but _close() and getAccDistancePerDirection need a refactor. 
As you said we need to track user swipe direction so I think we need to use `DraggedUp, DraggedDown, DraggedLeft, DraggedRight` vars. 
I'm right or I am doing mistakes?

**Comment by mmazzarolo** [comment]
Ciao!

Seems good to me. 
Yes, you should keep track of user action using something like `this.state.draggedDirection`. Keep in mind that the dragged direction might be tricky to handle because it could change multiple times if the user drags to a direction and then to different one.

**Comment by bhtruong93** [comment]
@matteo-pennisi I'm interested in this feature as well, can I help anywhere?

**Comment by matteo-pennisi** [comment]
Hi @bhtruong93, sorry for late response. At the moment I don't have time to continue due to some exams:sleepy: If you want you can watch what I did [here](https://github.com/matteo-pennisi/react-native-modal).

**Comment by 7elven** [comment]
this is my modified
https://github.com/7elven/react-native-modal/blob/master/src/index.js

ex. <Modal swipeDirection={["down","up"]} >

**Comment by matteo-pennisi** [comment]
@7elven I will try your fork  :+1:

**Comment by durdevic** [comment]
Hey guys, I'm just wondering where the progress is now? 
This feature would be so awesome to have 💪

**Comment by sunweiyang** [comment]
Tried it out, my comments are in #217.

**Comment by mmazzarolo** [comment]
@sunweiyang thank you for your feedbacks 🙏

**Comment by mmazzarolo** [comment]
Hey all, wanna give it a try to @rewieer 's #266 ?

**Comment by durdevic** [comment]
Hey @mmazzarolo, thanks for the heads up!

I just tried it but unfortunately I cant get it to work. I still receive this error: 

```
Warning: Failed prop type: Invalid prop `swipeDirection` of value `left` supplied to `ReactNativeModal`, expected one of ["up","down","left","right"].
```

I checked to **next** branch but the code for some reason is still the same in index.js

```
...
    swipeThreshold: PropTypes.number,
    swipeDirection: PropTypes.oneOf(["up", "down", "left", "right"]),
    useNativeDriver: PropTypes.bool,
...
```

Don't know what I'm doing wrong. Drop me a code I could use and I would gladly test it 👍

**Comment by rewieer** [comment]
It didn't get merged into next it seems
You can pull it from [there](https://github.com/rewieer/react-native-modal/tree/swipe-directions) !

**Comment by durdevic** [comment]
@rewieer Got it, works perfectly! 👌 

Gonna test it later a bit with FlatList to see how it behaves but with the simple content it's awesome 💪 

Awesome work! Thanks a bunch! :)

**Comment by mmazzarolo** [comment]
@durdevic thanks for testing it! Merging it into `next` and we'll release it later this/next week 👍 
(keeping the thread open until we release it)

**Comment by mmazzarolo** [comment]
@rewieer I'm a bit out of the loop
