### ISSUE TITLE
Centering

### ISSUE THREAD

**Issue by CCabia** [react-native-community/react-native-modal#126]
Hi, I'm trying to center the modal on my React Native project. I tried to center it using flexbox the style prop on the parent view, but it simply doesn't work. The modal keeps appearing on the left. I tried applying it on the modal itself, but of course, that affects the contents of the modal and not the modal itself.

Did I miss anything?

Here's my render code:
```
return (
      <View style = { styles.flex }>
        <Modal isVisible = { this.state.modalVisible } style = {styles.infoWindow}>
          <View>
          <Text>I am the modal content!</Text>
          <Text>I am the modal content!</Text>
          </View>
        </Modal>
        <GridLayout
          items = { items }
          itemsPerRow = { 4 }
          renderItem = { this.renderGridItem }/>
      </View>
    );
```

Thanks!

**Comment by mmazzarolo** [comment]
Hi!
[The provided example](https://github.com/react-native-community/react-native-modal/tree/master/example) uses a centered modal, take a look at [what styles it uses](https://github.com/react-native-community/react-native-modal/blob/master/example/src/app.style.js) to achieve the effect.

**Comment by mmazzarolo** [comment]
Thanks @lustigdev !
