### ISSUE TITLE
Chance to use default transitions of original React Native Modal

### ISSUE THREAD

**Issue by facuescobar** [react-native-community/react-native-modal#128]
## Feature Request

Chance to use 'fade' and default transitions of original React Native Modal

react-native-modal library allows us to show content using great animations, but it doesn't allow us to implement a basic 'fade' modal animation.

It would be great to have current react-native-modal and default Modal animations available to use.

**Comment by mmazzarolo** [comment]
Hey, we're using `react-native-animatable` for declaring the animations, so it would be a bit weird to add the default transition too here 🤔
