### ISSUE TITLE
Paddings in the modal

### ISSUE THREAD

**Issue by psycura** [react-native-community/react-native-modal#129]
Hello, and thank you for this awesome plugin.
When i use this modal, i have strange behavior - my content window inside the modal itself have paddings around the content.
Even if i add style to my content with full width and height , the padding still exist.

Why is this happen?

**Comment by imjaad9090** [comment]
wrap your content window inside a view and give that view style of flex:1

**Comment by psycura** [comment]
doesnt help
![screenshot_20180318-152258](https://user-images.githubusercontent.com/22491732/37566356-9af6c93e-2ac0-11e8-807f-06f46a8d5ded.jpg)

**Comment by bitlab-code** [comment]
It seems strange but it's a margin, use style property:
```javascript
<Modal 
  ...
  style = {{  margin: 0 }}
>
```

**Comment by mmazzarolo** [comment]
@bitlab-code solution should work (thanks btw!)  

The "issue" is caused by [this line](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js#L371) where I setup a minimal default margin of the modal (based on the device size). 
I know that it might sound weird to add a margin reset style but changing the default behaviour now would probably be a breaking change.

**Comment by makani20** [comment]
<Modal
          onBackdropPress={() => false}
          backdropOpacity={1}
          animationType="slide"
          hasBackdrop
          style={{
           **margin: 0,**
            backgroundColor: colors.blackOpacityColor,
          }}
          visible={locationPopup}>

**Comment by fellenabmb** [comment]
> It seems strange but it's a margin, use style property:
> 
> ```js
> <Modal style = {{  margin: 0 }}>
>   <View style = {{ flex: 1 }}>
>     ...
> ```

You sir, are a savior. I've been removing margins from my modals for a couple of hours wondering where the hell did that margin came from. What a troll default style that one is, I tell you.

**Comment by victorrequena20** [comment]
Set Modal.Content maxWidth property in 1000 work for me
`<Modal.Content
          style={{
            maxWidth: 1000,
            margin: 0,
            width: "100%",
            position: "absolute",
            bottom: 0,
            paddingVertical: 24,
            paddingHorizontal: 16,
          }}
        >
          <Stack>

          </Stack>
        </Modal.Content>`

**Comment by PhirunOem** [comment]
> It seems strange but it's a margin, use style property:
> 
> ```js
> <Modal style = {{  margin: 0 }}>
>   <View style = {{ flex: 1 }}>
>     ...
> ```

I'm new in react native. And it works !
