### ISSUE TITLE
 can support modal box nested modal box?

### ISSUE THREAD

**Issue by Rpeanut** [react-native-community/react-native-modal#132]
hai I open a full sceen modal, then i press a button in this modal, i  expect open another modal and cover it up , but i found only exist one modal. Can this be done?

**Comment by mmazzarolo** [comment]
Hey!
Showing multiple modals at the same time is not UX friendly so it is not "officially" supported. 

If you're interested though here are some other related issues [1](https://github.com/react-native-community/react-native-modal/issues/30), [2](https://github.com/react-native-community/react-native-modal/issues/34).
