### ISSUE TITLE
backdropColor not working!!

### ISSUE THREAD

**Issue by orensaldanha** [react-native-community/react-native-modal#137]
`import React , { Component } from 'react'
import { View , Text, TouchableHighlight , Dimensions,TouchableWithoutFeedback} from 'react-native'
import { StackNavigator } from 'react-navigation'

import { Button, Container, Icon } from 'native-base';

import { Ionicons } from '@expo/vector-icons'

import ElevatedView from 'react-native-elevated-view'

import Modal from "react-native-modal";

import Header from './components/Header.js'
import Catalog from './components/Catalog.js'

const {height, width} = Dimensions.get('window');
const newHeight = 0.70*height
const newWidth = 0.85*width

export default class Main extends Component {
    constructor(props) {
        super(props);
        this.setModalVisible = this.setModalVisible.bind(this);
    }
    state = {
        modalVisible: false,
      };
    
      setModalVisible(visible) {
        this.setState({modalVisible: visible});
      }
    
    static navigationOptions = {
        header: null
    }
    render()  {
        return (
            <View style={{ flex: 1}}>
                 <Modal
                    visible={this.state.modalVisible}
                    onRequestClose={() => {}}
                    onBackdropPress={() => this.setModalVisible(false)}
                    backdropColor={'grey'}
                    backdropOpacity={1}
                   >
                            <View style={{height:newHeight,width:newWidth,backgroundColor:'#fff',alignSelf:'center',position:'absolute'}}> 
                               
                                <Button transparent onPress={() => {  this.setModalVisible(!this.state.modalVisible)  }}>
                                    <Icon name='ios-arrow-back'style={{fontSize: 30, color: 'black'}} />
                                </Button>
                                <View style={{paddingHorizontal:15}}>
                                <Text>Hello World!</Text>
                                </View>
                            </View>
                    </Modal>

                <Header />
                <Catalog  setModalVisible={this.setModalVisible} />
                   
                 
      </View>
          

        )
    }
}

Here's the code for the Modal , I cant get the backdropColor to grey.

Heres a screenshot.
`
![capture](https://user-images.githubusercontent.com/36854536/38263353-84cd7b2e-378d-11e8-8533-134349383260.PNG)

**Comment by sskinner3** [comment]
Use isVisible, not visible

**Comment by mmazzarolo** [comment]
thank you @sskinner3
