### ISSUE TITLE
Issue with using FlatList in Modal -  Layout issue

### ISSUE THREAD

**Issue by tomleeshihhung** [react-native-community/react-native-modal#148]
Normally, the height of FlatList can be controlled by wrapping it with the react native <View>
However, it doesn't appear to work here.

The FlatList disregards the boundaries set by <View> and the rows continue on.
Interestingly, if I make the FlatList horizontal, it works just fine.

Any ideas? Thank you

Below is the code for the Modal component.

<
Modal isVisible={visible}
   animationIn='slideInUp'
    backdropOpacity={0.5}
    style={{ margin: 15 }}>

<
View style={{ height: 300 }}>
<
FlatList
    data={data}
    renderItem={modalBenefitItem}
    keyExtractor={(item) => item.key}
    scrollEnabled/>

<
/View>
<
/Modal>

**Comment by landandan** [comment]
me too

**Comment by mmazzarolo** [comment]
Could you share a simple repo with the issue?

**Comment by zmfang** [comment]
???How can I do?

**Comment by GreatAuk** [comment]
+1

**Comment by Donhv** [comment]
+1

**Comment by Josin22** [comment]
+1

**Comment by boss225** [comment]
+1

**Comment by thedeg123** [comment]
+1

**Comment by alicema15** [comment]
+1

**Comment by sometimescasey** [comment]
Can confirm I'm experiencing this right now as well, with react-native and Expo 38.

Inside the Modal I can set a View with `style={{flex:1}}` or `style={{height:300}}`, but if I use a FlatList inside this View, the list content begins scrolling from the bottom of the screen, not the bottom of the Modal.

Making a note here in case anyone finds a solution.

**Comment by CMDezz** [comment]
@sometimescasey  You saved my day at 2AM. Thank you.
