### ISSUE TITLE
Modal stays open after reloading on Android

### ISSUE THREAD

**Issue by spectralsun** [react-native-community/react-native-modal#152]
If I have a modal open on android and I do a reload from the developer menu on my android device, the modal never closes when the app reloads. To make matters worse, I can't close it either after the app is reloaded.

Steps to reproduce:

- On android, open a Modal
- Open the developer menu (you can shake the phone to do this)
- Tap reload
- Watch as the app reloads but the modal stays open and is no longer closable

**Comment by mmazzarolo** [comment]
Hey, duplicate of issue #150

**Comment by dev4xy** [comment]
+1
