### ISSUE TITLE
Option for no animation at all?

### ISSUE THREAD

**Issue by paul-git** [react-native-community/react-native-modal#153]
Hey there,

I'm trying to just "pop up" the modal.  It seems that the available animations (including those from rn-animate) are all too much for some old phones and the delay is quite noticeable. So I would like to be able just to show and hide the modal without any animation whatsoever (I understand of course that "show" and "hide" are animations itself somehow, but I think I made my point).
I tried to use 

```
{
this.state.isModalVisible && 
<Modal isVisible={true}>
 <...my stuff...>
</Modal>
}
```

to avoid animations but it seems to animate the modal anyway. Am I doing it wrong?
Is there any way to just switch it on and off? Even animationInTiming = 1 doesn´t accelerate it too much. I guess the delay won´t go away without animations, but at least it appears as fast as possible.

Greets and thanks,
Paul

**Comment by mmazzarolo** [comment]
Hey @paul-git , did you already try replacing react-native-modal with the original react-native modal just to make sure that is the animation that is slowing down the modal (and not its content)?
I would also suggest you to play a bit with both `useNativeDriver`and `hideModalContentWhileAnimating` for speeding it up a bit.  

Also, yes, we still miss a "no-animation" mode where we disable completely the animations... anyone willing to send a PR for it?

**Comment by paul-git** [comment]
Hey @mmazzarolo, 
thanks for the help. From reading through other comments I just compiled it for productive, which made it **much** more responsive. I will play around with the options you named, and with a fast fadeIn it is almost like not animated.

I guess you can close this question, unless you want to keep it open for the PR.

Thanks again,
Paul
