### ISSUE TITLE
Two modal in SingleClass ?

### ISSUE THREAD

**Issue by Salman18** [react-native-community/react-native-modal#155]
I have two buttons and each button has different content to pop up.

But if I define two modals it is overriding and showing same.

Please let me know how to use or Defines two modals in one Class based Component.

**Comment by theohdv** [comment]
Can you share your code ? It will help us to better understand your situation.

**Comment by mmazzarolo** [comment]
Thanks @theohdv 
@Salman18 please follow the issue template

**Comment by Salman18** [comment]
<View>
        <Modals isVisible={this.state.isModalVisible} style={{ justifyContent: 'center', alignItems: 'center' }}>
            <View style={{ backgroundColor: 'white', height: 300, width: 270, borderRadius: 7 }}>
                  <View style={styles.outerView}>
                      <Text style={{ color: '#00a3ee', fontWeight: 'bold' }}>Gadgets</Text>
                      <View style={styles.modalsStyle}><Icons size={28} name='md-arrow-forward' color='#00a3ee' /></View>
                  </View>
                  <View style={styles.tabstyle}>
                    <ScrollableTab />
                  </View>
              <TouchableOpacity onPress={this.toggleModal}>
                   <Text>Hide me!</Text>
              </TouchableOpacity>
            </View>
        </Modals>
        <View>
      <Modal 
      transparent visible={this.state.pickerDisplayed} animationType={'slide'}
      >
       <View style={styles.modalStyle}>
                 <View style={styles.outerViewSecond}>
                      <Text style={{ color: '#00a3ee', fontWeight: 'bold' }}>Speciality</Text>
                      <View style={styles.modalsStyle}><Icons size={28} name='md-arrow-forward' color='#00a3ee' /></View>
                  </View>
                  <View style={styles.tabstyle}>
                    <ScrollableTab />
                  </View>
         <TouchableOpacity onPress={() => this.togglePicker()}>
           <Text style={{ color: '#999' }}>Cancel</Text>
        </TouchableOpacity>
       </View>
      </Modal>
    </View>
        </View>

**Comment by Salman18** [comment]
this is my code and how can I define Two modals in one class.

if I am definin like this its showing only one modal to both .

**Comment by mmazzarolo** [comment]
Please see the [example project](https://github.com/react-native-community/react-native-modal/tree/master/example). It handles multiple modals.

**Comment by Salman18** [comment]
Thanks. Will check
