### ISSUE TITLE
Very slow in android 

### ISSUE THREAD

**Issue by Im-Goutham** [react-native-community/react-native-modal#158]
modal taking 2 or 3 seconds to open in Android, while in ios it is very fast.

`
<Modal
           isVisible={this.state.showModal}
           animationIn='slideInUp'
           backdropColor='black'
           backdropOpacity='0.20'
           animationInTiming={0}
           style={styles.bottomModal}
           onSwipe={() => this.setState({showModal: false})}
           onBackdropPress={() => this.setState({showModal: false})}
         >
           <View style={styles.modalContent}>
               <List itemDivider={false}>
                 <ListItem icon noBorder style={{borderBottomWidth: 0}}>
                   <Left>
                     <Icon name="ios-camera"/>
                   </Left>
                   <Body>
                     <Text>Upload from camera</Text>
                   </Body>
                 </ListItem>        
               </List>
           </View>
         </Modal>
           </View>
`

**Comment by mmazzarolo** [comment]
Android is slower when not build in release mode. 
Try creating a release apk and see if it works correctly there.

**Comment by waqaramjad** [comment]
still facing slow issue

**Comment by ChinmayDeyUI** [comment]
After release Apk the performance still slow

**Comment by yestay90** [comment]
after release the lag when opening modal still exists.

**Comment by michaelVictoriaDev** [comment]
Still feel lag in android :/

**Comment by maximusnikulin** [comment]
same here

**Comment by adamsolomon1986** [comment]
lag still exists on Android with RN > .61

**Comment by magrinj** [comment]
This ticket should be reopened, facing same issue in release on Android, modal is faster in debug... and take some time to open in release mode with react-native 0.61.5.

**Comment by murat0** [comment]
Same here

**Comment by aryatama** [comment]
Same here

**Comment by murat0** [comment]
If you are referring to 2-3 seconds, it's most likely related to async content keeping the modal from showing up. It might get a bit confusing because even if your content loading code is placed within ComponentDidMount it can still block the Modal from showing smoothly. I would suggest using an ActivityIndicator along with an isLoading prop and not showing anything at the initial state other than the Modal wrapper itself. 

this.state = {
 isLoading: true
}

componentDidMount() {
 setTimeout(() => this.setState({isLoading: false}), 1000);
}

`<Modal visible={isVisible}.....>
{
 !isLoading ? 
  // show your stuff
 : <ActivityIndicator ... />
}

`


P.S You also need to wrap the Modal itself with the `isVisible` prop so that it un-mounts and resets once you dismiss it, resetting the state too. Otherwise it stays mounted.

**Comment by HelKyle** [comment]
In my case, it works correctly after stopping debug js remotely.

**Comment by cglacet** [comment]
@HelKyle Wow, ok. Same for me, but it's still a bit slow. 

Here some version I have installed.
 ```
{
    "react-native": "0.62.2",
    "react-dom": "^16.13.1",
    "react": "^16.13.1",
    "react-native-reanimated": "^1.9.0",
}
```

I tried this on a physical device (one plus).

**Comment by cglacet** [comment]
Here you have a [code example](https://codesandbox.io/s/compassionate-tesla-6bmuk?file=/src/App.js:0-2047) that totally screw with the animations on android when debugging  (with React Native Debugger) if you want to test it:

```jsx
import React, { useState } from "react";
import { Button, Text, View, StyleSheet } from "react-native";
import Modal from "react-native-modal";

function MyModal(props) {
  return (
    <Modal
      backdropOpacity={1}
      swipeDirection={"down"}
      onSwipeComplete={props.onRequestClose}
      isVisible={props.isVisible}
    >
      <View style={styles.modalView}>
        <View style={styles.formView}>{props.children}</View>
      </View>
    </Modal>
  );
}

function ModalTester() {
  const [isModalVisible, setModalVisible] = useState(false);

  const toggleModal = () => {
    setModalVisible(!isModalVisible);
  };

  return (
    <View style={{ flex: 1 }}>
      <Button title="Show modal" onPress={toggleModal} />
      <MyModal isVisible={isModalVisible} onRequestClose={toggleModal}>
        <View style={{ flex: 1 }}>
          <Text>Hello!</Text>
          <Button title="Hide modal" onPress={toggleModal} />
        </View>
      </MyModal>
    </View>
  );
}

const styles = StyleSheet.create({
  modalView: {
    flex: 1,
  },
  modalBackground: {
    flex: 1
  },
  modalBackgroundContent: {
    flex: 1
  },
  formView: {
    flex: 1,
    width: "100%",
    backgroundColor: "white"
  }
});

export default class App extends React.Component {
  render() {
    return <ModalTester />;
  }
}
```

For those who can't experience the problem, here is how it looks like. When showing the modal : 

- Press the "show modal"  -> The modal just appear at its final position after approximately .5s in (no animation at all)

When closing it: 

- Tap "hide modal"  -> Everything but the hello view + hide modal button disappear (no animation), count 1s before these two also disappear without animation 
- Swipe down just a little (< `threshold`)  -> the modal freezes here for ~ .5s then slide back up in a few steps each separated by ~ .5s which gives a total of around 2s animation to fully get back to its original position. 
- Swipe down past the threshold distance -> the modal freezes too, but then disappear without any animation.

On the other hand, while swiping (before releasing) all animations are very smooth (sliding and opacity decreasing for the "backdrop").

**Comment by wsfung2008** [comment]
i solved it by adding the following prop
useNativeDriver={true} 

https://stackoverflow.com/questions/61127422/react-native-modal-time-delay-and-jerky-animation

**Comment by binitgurzu** [comment]
still looking for solutions +1

**Comment by dvijeniii05** [comment]
I have the same issue.
Currently got useNativeDriver={true} but the modal appearance is still slow

**Comment by gabrielporcher** [comment]
I'm currently using modals in 2 different projects.
An older app, with :
 "react": "16.13.1",
   "react-native": "0.63.2"
and which uses class components.

In my another newer app I'm using : 
"react": "17.0.2",
  "react-native": "0.67.2",
And using functional components

In my old app the modal opens very quickly and smoothly.
In my newest app, the modal is taking a while to open, and often with slow animations

I can't understand the reason for this, since in the newest app I'm using more efficient versions and approaches

PS: I tested the same code in both apps, and the old app is much faster to open the modal

**Comment by HyopeR** [comment]
I think this topic should be reopened. Because there really seems to be a slowness problem on the android platform.

<pre>
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-modal": "^13.0.1",
</pre>

**Comment by ancyrweb** [comment]
If this is a problem linked to RN itself, then the issue should be opened there.
Can you provide a repro ?

**Comment by robin3317** [comment]
> In my case, it works correctly after stopping debug js remotely.

Me too.

**Comment by sajiro** [comment]
DId you guys manage to fixed this? i have the same issue its super delay and no animation. when closing the background is going out first then the content after 1 sec i think.

**Comment by sajiro** [comment]
faster, but still laggy
