### ISSUE TITLE
modal is shown 2 times

### ISSUE THREAD

**Issue by faycito** [react-native-community/react-native-modal#159]
i dont know why but, my modal is shown 2 times, can u help me please?,

`
import React, { Component } from 'react'
import {
    Text,
    View,
    StyleSheet,
    TouchableOpacity,
    Dimensions,
    ImageBackground,
    Image,
    ScrollView,
    Platform,
    Modal,
    Alert,
    TouchableHighlight
} from 'react-native'
import { StackNavigator } from 'react-navigation'
import Button from 'react-native-button'
import { Actions } from 'react-native-router-flux'
import colors from '../../../app.styles'
import TabsComponent from '../../Tabs/tabs.component'
import PopoverTooltip from 'react-native-popover-tooltip'
import Carousel, { Pagination } from 'react-native-snap-carousel'

let { width } = Dimensions.get("window")
export default class HomePage extends Component {

    name = "I"
    constructor(props) {
        super(props)
        this.state = {
            modalVisble: false,
            myPlan: 'Trio',
            phoneNumber: '',
            plan: {
                title: "TRIO",
                internet: "Internet 6 mbs",
                tv: "TV Estándar",
                linea: "Fija Tarifa Plan Nacional",
                precio: "150.00"
            },
            phones: {
                one: {
                    phone: "2837002",
                    plan: 'Trio'
                },
                two: {
                    phone: "4785526",
                    plan: 'Duo'
                },
                three: {
                    phone: "7884566",
                    plan: 'Mono'
                }
            },
            misDatos: [
                {
                    texto: "Mejora tu plan, con más velocidad",
                    velocidad: "200",
                    precio: "160.00"
                },
                {
                    texto: "Mejora tu plan, con más canales",
                    bloque: "HBO+ ",
                    precio: "60.00"
                },
                {
                    texto: "Mejora tu plan, con más velocidad y canales",
                    velocidad: "120",
                    bloque: "HBO+",
                    precio: "200.00"
                }
            ],
        }
    }

    static navigationOptions = {
        headerLeft: null,
        title: 'Mi movistar ',
        headerStyle: {
            backgroundColor: colors.primaryBlue,
            shadowOpacity: 0,
            elevation: 0
        },
        headerTitleStyle: {
            color: 'white',
            fontSize: 20,
            fontStyle: 'italic'
        },
        headerRight:
            <View style={{ flex: 1, flexDirection: 'row' }}>
                <TouchableOpacity>
                    <View style={{ height: 40, width: 50 }}>
                        <Image
                            source={require('../../../../assets/img/icons/ico-bolsa.png')}
                            style={{ width: 35, height: 35, marginTop: 12.5, resizeMode: 'contain' }}
                        ></Image>
                    </View>
                </TouchableOpacity>
                <TouchableOpacity>
                    <View style={{ borderWidth: 1.5, borderColor: 'white', padding: 5, margin: 10, width: 40, height: 40, borderRadius: 100 }}>
                        <Text style={{ color: 'white', fontSize: 20, textAlign: 'center', lineHeight: 27 }}>I</Text>
                    </View>
                </TouchableOpacity>
            </View>
    };

    pagination() {
        const { entries, activeSlide } = this.state.misDatos;
        return (
            <Pagination
                dotsLength={entries.length}
                activeDotIndex={0}
                containerStyle={{ backgroundColor: 'rgba(0, 0, 0, 0.75)' }}
                dotStyle={{
                    width: 10,
                    height: 10,
                    borderRadius: 5,
                    marginHorizontal: 8,
                    backgroundColor: 'rgba(255, 255, 255, 0.92)'
                }}
                inactiveDotStyle={{
                    // Define styles for inactive dots here
                }}
                inactiveDotOpacity={0.4}
                inactiveDotScale={0.6}
            />
        );
    }

    setModalVisible(visible) {
        this.setState({modalVisible: visible});
    }

    _renderItem = ({ item, index }) => {
        _getSliderContent = ({ item }) => {
            if (item.velocidad && item.bloque) {
                return (
                    <Text style={{ color: 'white', fontSize: 18 }}>a <Text style={{ fontWeight: 'bold', fontSize: 22, color: '#fff' }}> {item.velocidad} </Text><Text style={{ color: 'white', fontSize: 18 }}>mbps y </Text><Text style={{ fontWeight: 'bold', fontSize: 22, color: '#fff' }}>{item.bloque}</Text></Text>
                )
            } else if (item.velocidad) {
                return (
                    <Text style={{ fontSize: 18, color: 'white' }}>a <Text style={{ fontWeight: 'bold', fontSize: 22, color: '#fff' }}> {item.velocidad} </Text> <Text style={{ fontSize: 18, color: 'white' }}> mbps </Text></Text>
                )
            }
            else if (item.bloque) {
                return (
                    <Text style={{ fontSize: 18, color: 'white' }}>bloque <Text style={{ fontWeight: 'bold', fontSize: 22, color: '#fff' }}> {item.bloque}</Text> </Text>
                )
            }
        }
        _getSliderHeader = ({ item }) => {
            if (item.velocidad && !item.bloque) {
                return (
                    <View style={[styles.sliderHeader, {
                        paddingLeft: 50,
                        paddingRight: 50,
                        paddingTop: 7.5,
                        paddingBottom: 30
                    }]}>
                        <Text style={{
                            color: '#fff',
                            fontSize: 18,
                            textAlign: 'center'
                        }}> {item.texto} </Text>
                        {_getSliderContent({ item })}
                    </View>
                )
            }
            else {
                return (
                    <View style={styles.sliderHeader}>
                        <Text style={{
                            color: '#fff',
                            fontSize: 18,
                            textAlign: 'center'
                        }}> {item.texto} </Text>
                        {_getSliderContent({ item })}
                    </View>
                )
            }
        }
        _modalView = ({item}) => {
            return (
                <Modal
                animationType="slide"
                transparent={false}
                visible={this.state.modalVisible}
                onRequestClose={() => {
                    Alert.alert('Modal has been closed.');
                }}>
                <View style={{ marginTop: 22 }}>
                    <View>
                        <Text>Hello World!</Text>

                        <TouchableHighlight
                            onPress={() => {
                                this.setModalVisible(false);
                              }}
                        >
                            <Text>Hide Modal</Text>
                        </TouchableHighlight>
                    </View>
                </View>
            </Modal>
            )
        }
        return (
            <View style={{
                width: '95%',
                height: 270,
                borderWidth: 1,
                borderColor: colors.secondary1,
                marginTop: 20,
                borderRadius: 15
            }}
            >
                {_modalView({})}
                {_getSliderHeader({ item })}
                <View style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    height: 160,
                    marginTop: 15
                }}>
                    <Text style={{ color: colors.grey4, fontSize: 20 }}> S/ {item.precio} al mes </Text>
                    <TouchableOpacity style={{ height: 50, padding: 15, borderRadius: 10, marginTop: 25, marginBottom: 25, width: 200, backgroundColor: colors.primaryGreen }}
                    >
                        <Text style={{ color: '#fff', textAlign: 'center', fontSize: 18, lineHeight: 20 }}>¡LO QUIERO!</Text>
                    </TouchableOpacity>
                    <TouchableOpacity onPress={() => this.setModalVisible(true)}><Text>Hola mundo</Text></TouchableOpacity>
                </View>
            </View>
        );
    }

    render() {
        return (
            <ScrollView style={{ backgroundColor: '#FBFCFC' }}>
                <ImageBackground source={require('../../../../assets/img/banner.png')}
                    style={{ height: 40, width: '100%' }}>
                    <View>
                        <View style={{ backgroundColor: colors.primaryBlue }}>
                            <PopoverTooltip
                                ref="Popover1"
                                buttonComponent={
                                    //Aqui va el número
                                    <View
                                        style={{
                                            backgroundColor: 'rgba(0,0,0,0)', height: 30, width: 130,
                                            marginLeft: 20
                                        }}
                                    >
                                        <View style={{
                                            width: '100%', paddingLeft: 10, paddingRight: 10,
                                            flex: 1, flexDirection: 'row', justifyContent: 'center', alignContent: 'center'
                                        }}>
                                            <Text style={{ color: 'white', fontSize: 16 }}>{this.state.phoneNumber ? this.state.phoneNumber : this.state.phones.one.phone} <Text>{this.state.myPlan}</Text></Text>
                                            <Image
                                                source={require('../../../../assets/img/icons/down_arrow.png')}
                                                style={{ width: 17.5, height: 20, resizeMode: 'contain', marginLeft: 5, marginTop: 2 }}
                                            >
                                            </Image>
                                        </View>
                                    </View>
                                }
                                items={[
                                    {
                                        label: this.state.phones.one.phone,
                                        onPress: () => { this.setState({ myPlan: 'Trio' }), this.setState({ phoneNumber: this.state.phones.one.phone }) }
                                    },
                                    {
                                        label: this.state.phones.two.phone,
                                        onPress: () => { this.setState({ myPlan: 'Duo' }), this.setState({ phoneNumber: this.state.phones.two.phone }) }
                                    },
                                    {
                                        label: this.state.phones.three.phone,
                                        onPress: () => { this.setState({ myPlan: 'Mono' }), this.setState({ phoneNumber: this.state.phones.three.phone }) }
                                    }
                                ]}
                                animationType='spring'
                                overlayStyle={{ backgroundColor: 'transparent' }}
                                timingConfig={{ duration: 500 }}
                            />
                        </View>
                    </View>
                </ImageBackground>
                {/* Monto a pagar */}
                <TabsComponent />
                <View style={styles.montoPago}>
                    <View>
                        <Text style={[styles.texting, { color: '#000' }]}> Monto a pagar: <Text style={{ fontWeight: 'bold', color: '#000' }}>S/ 299.90 </Text></Text>
                        <Text style={{ paddingLeft: 7, color: colors.grey5, fontStyle: 'italic', fontSize: 14 }}>Vence   15 feb</Text>
                    </View>
                    <View>
                        <TouchableOpacity style={styles.btnPagar}>
                            <Text style={{ color: 'white', textAlign: 'center', lineHeight: 45, fontSize: 14 }}> PAGAR </Text>
                        </TouchableOpacity>
                    </View>
                </View>
                <View style={styles.content}>
                    <View style={styles.plan}>
                        <View style={{ justifyContent: 'center', alignItems: 'center' }}>
                            <Text style={{ fontSize: 16, marginBottom: 10, textAlign: 'center' }}> Tu Plan:</Text>
                            <Text style={{ fontSize: 18, fontWeight: 'bold', color: colors.grey5, textAlign: 'center' }}>{this.state.plan.title}</Text>
                            <Text style={{ fontSize: 14, color: colors.grey2, textAlign: 'center', fontStyle: 'italic' }}>S/{this.state.plan.precio} al mes</Text>
                        </View>
                        <View style={{ justifyContent: 'center' }}>
                            <View style={{ display: 'flex', flexDirection: 'row' }}>
                                <View style={{ width: 20 }}>
                                    <Image source={require('../../../../assets/img/icons/ico-int.png')}></Image>
                                </View>
                                <Text style={{ fontSize: 14, color: colors.secondary1, marginBottom: 10 }}> {this.state.plan.internet} </Text>
                            </View>
                            <View style={{ display: 'flex', flexDirection: 'row' }}>
                                <View style={{ width: 20 }}>
                                    <Image source={require('../../../../assets/img/icons/ico-tv.png')}></Image>
                                </View>
                                <Text style={{ fontSize: 14, color: colors.secondary1, marginBottom: 10 }}> {this.state.plan.tv} </Text>
                            </View>
                            <View style={{ display: 'flex', flexDirection: 'row' }}>
                                <View style={{ width: 20 }}>
                                    <Image source={require('../../../../assets/img/icons/ico-tel.png')}></Image>
                                </View>
                                <Text style={{ fontSize: 14, color: colors.secondary1 }}> {this.state.plan.linea} </Text>
                            </View>
                        </View>
                    </View>
                    <View style={{ height: 300, width: '90%' }}>
                        <Carousel
                            ref={(c) => { this._carousel = c; }}
                            data={this.state.misDatos}
                            renderItem={this._renderItem}
                            sliderWidth={width * .95}
                            itemWidth={width * .95}
                            style={{ marginTop: 10 }}
                            loop={true}
                            autoplay={true}
                            autoplayDelay={100}
                            autoplayInterval={2000}
                            useScrollView={true}
                        />
                        {/* {this.pagination} */}
                    </View>
                </View>
            </ScrollView>
        );
    }
}

const styles = StyleSheet.create({
    content: {
        padding: 20,
        backgroundColor: '#fff'
    },
    texting: {
        fontSize: 14
    },
    montoPago: {
        height: 75,
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 25,
        paddingRight: 25,
        display: 'flex',
        backgroundColor: colors.grey0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    btnPagar: {
        marginRight: 5,
        // height: 50,
        borderRadius: 10,
        width: 95,
        height: 46.5,
        backgroundColor: colors.primaryGreen
    },
    plan: {
        borderWidth: 1,
        padding: 15,
        borderColor: colors.grey0,
        borderRadius: 10,
        display: 'flex',
        flexDirection: 'row'
    },
    sliderHeader: {
        width: '100%',
        height: 90,
        borderTopLeftRadius: 14,
        borderTopRightRadius: 14,
        backgroundColor: this.colors.secondary1,
        display: 'flex',
        alignItems: 'center',
        paddingLeft: 20,
        paddingRight: 20,
        paddingTop: 10,
        paddingBottom: 15
        //paddingLeft: 10
    }
})
`

**Comment by Im-Goutham** [comment]
Try replacing  _modalView({}) to this._modalView({})

**Comment by mmazzarolo** [comment]
Hi!
Please see the example directory in this repo for an example on how to use the modal.
