### ISSUE TITLE
Close modal on outside tap of modal area

### ISSUE THREAD

**Issue by ShaikhKabeer** [react-native-community/react-native-modal#164]
Hello Guys, How do I close modal when  I tap on outside area of modal. Need help !!

**Comment by mmazzarolo** [comment]
Hi,
[How can I hide the modal by pressing outside of its content?](https://github.com/react-native-community/react-native-modal#how-can-i-hide-the-modal-by-pressing-outside-of-its-content)

**Comment by mmazzarolo** [comment]
Sorry @ShaikhKabeer but I don't get it, the FAQ is talking about **onBackdropPress**, not **onBackButtonPress** 🤔 
Please read the FAQ: The prop **onBackdropPress** allows you to handle this situation.
