### ISSUE TITLE
Why not re-render Modal window?

### ISSUE THREAD

**Issue by sinevitch** [react-native-community/react-native-modal#167]
Why not re-render Modal window?

https://stackoverflow.com/questions/50680576/why-not-re-render-modal-window?noredirect=1#comment88382215_50680576

"react-native-modal": "^5.4.0",
"react-redux": "^5.0.7",
"react": "16.3.1",
 "react-dom": "^16.3.2",
 "react-native": "^0.55.3"

**Comment by mmazzarolo** [comment]
Could you please provide an example here? Please follow the issue template before submitting a new issue.
Thanks!
