### ISSUE TITLE
on iphoneX It represent weird.

### ISSUE THREAD

**Issue by gwl002** [react-native-community/react-native-modal#168]
![image](https://user-images.githubusercontent.com/18588945/40968775-ee790976-68e8-11e8-9e58-99e7feea6c9b.png)

When use the modal original It shows normal,but when use this package it seems the modal can not cover the full screen in iPhone X.

**Comment by waterFallFlow** [comment]
you can try to add margin style like this:
![image](https://user-images.githubusercontent.com/15437785/40975661-3b794f78-68fe-11e8-81c6-7da6e01b0eec.png)

**Comment by mmazzarolo** [comment]
Thanks @waterFallFlow
