### ISSUE TITLE
onBackdropPress not working on iOS. Works on android

### ISSUE THREAD

**Issue by Samesh** [react-native-community/react-native-modal#169]
Hi, onBackdropPress function works on android but doesn't work in iOS. Please see. Version 6.0.0

`<Modal
                    isVisible={showChooseFriendshipModal}
                    backdropColor="#009688"
                    onBackButtonPress={hideFriendshipModalFunc}
                    onBackdropPress={() => console.log("Clicked")}
                >`

**Comment by mmazzarolo** [comment]
Hi @Samesh 
could you please create a new issue following the issue template?
Thanks!

**Comment by Samesh** [comment]
There was a problem with my styling. It actually works. Sorry about that

**Comment by eamonwhiter73** [comment]
I am having a similar problem, I'm not sure if it is my styling...

this.state = {
      modalVisible: false,
 }

setModalVisible(visible) {
    this.setState({ modalVisible: visible })
  }

_renderModalContent = () => (
    <TouchableWithoutFeedback onPress={() => {console.log('tapped')}}>
      <View
        style={{
          paddingTop: 5,
          paddingBottom: 10,
          paddingLeft: 10,
          paddingRight: 10,
          marginTop: 84,
          flex: 0.892,
          marginLeft: (Dimensions.get('window').width - 300) / 2,
          backgroundColor: 'rgba(0,0,0,0.8)',
          width: 300,
          borderRadius: 4,
          borderWidth: 0,
        }}>
        <View style={{ flexDirection: 'column', justifyContent: 'space-between', flex: 1 }}>
          <View style={{ flexDirection: 'column', flex: 1 }}>
            <Text
              style={{
                flex: 0,
                width: Dimensions.get('window').width,
                color: 'white',
                fontWeight: '700',
                marginBottom: 5,
              }}>
              Date(s) Needed:
            </Text>
            {this.showCalendar()}
          </View>
          <View style={{ flexDirection: 'column', flex: 0.2, marginBottom: 10 }}>
            <TextInput
              style={{
                width: 280,
                flex: 1,
                borderColor: 'gray',
                borderWidth: 1,
                backgroundColor: '#ffffff',
                paddingLeft: 5,
                borderRadius: 4,
              }}
              onChangeText={text => this.setState({ message: text })}
              value={this.state.message}
              multiline={true}
              numberOfLines={2}
            />
          </View>
          <View style={{ flex: 0.1, borderRadius: 4, borderWidth: 0 }}>
            <TouchableOpacity
              activeOpacity={1}
              style={{
                backgroundColor: this.state.rentButtonBackground,
                flex: 1,
                justifyContent: 'center',
                alignItems: 'center',
                width: 280,
                borderRadius: 4,
                borderWidth: 0,
              }}
              onPress={() => {
                this.setState({ rentButtonBackground: '#94ebe6' })

                setTimeout(() => {
                  this.setState({ rentButtonBackground: '#6de3dc' })

                  this.setModalVisible(false)
                }, 1)
              }}>
              <Text
                style={{
                  backgroundColor: this.state.rentButtonBackground,
                  textAlign: 'center',
                  color: 'white',
                  fontWeight: '900',
                  fontSize: 18,
                  borderRadius: 4,
                  borderWidth: 0,
                }}>
                SEND
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </TouchableWithoutFeedback>
  );

render() {
    return (
      <View style={{}}>
        <TouchableWithoutFeedback onPress={() => {this.setModalVisible(false); console.log('tapppppped');}}>
          <Modal
            animationType="slide"
            transparent={false}
            visible={this.state.modalVisible}
            onBackDropPress ={() => {this.setModalVisible(false)}}
            onRequestClose={() => {
              alert('Modal has been closed.')
            }}
            style={{margin:0}}>
            {this._renderModalContent()}
          </Modal>
        </TouchableWithoutFeedback>

        {!this.state.modalVisible && (
          <TouchableOpacity
            style={{
              backgroundColor: this.state.rentButtonBackground,
              flex: 1,
              flexDirection: 'row',
              justifyContent: 'center',
              alignItems: 'center',
              width: Dimensions.get('window').width,
              height: 44,
            }}
            onPress={() => {
              this.setState({ rentButtonBackground: '#94ebe6' })

              setTimeout(() => {
                this.setState({ rentButtonBackground: '#6de3dc' })

                this.setModalVisible(true)
              }, 1)
            }}>
            <Text
              style={{
                backgroundColor: this.state.rentButtonBackground,
                textAlign: 'center',
                color: 'white',
                fontWeight: '900',
                fontSize: 18,
              }}>
              RENT
            </Text>
          </TouchableOpacity>
        )}
      </View>
    )
  }

The touches don't register when I click on the backdrop (the white area when you have `transparent: {false}`.
