### ISSUE TITLE
How to disable swipe gesture?

### ISSUE THREAD

**Issue by tpnguyen91** [react-native-community/react-native-modal#170]
Hi Guys, 

How can I disable swipe gesture. like isSwipe? 

Thanks in advance.

**Comment by mmazzarolo** [comment]
Hi there, swiping is disabled by default and it's controlled by `swipeDirection` (set it to null or undefined)

**Comment by MayoudP** [comment]
> Hi there, swiping is disabled by default and it's controlled by `swipeDirection` (set it to null or undefined)
@mmazzarolo 
This one doens't work in the version right ? I'm trying to disable Swipe, but now,  `swipe` is set by default and setting `swipeDirection` to `null` doesn't change anything... 
:/

**Comment by mmazzarolo** [comment]
@MayoudP this should still be the same way it's working [now](https://github.com/react-native-community/react-native-modal/blob/640901813102b0ddd592a10d756350c55d4abaf4/src/index.js#L572)

**Comment by MayoudP** [comment]
Ok my bad, I actually added twice the `swipeDirection` props with `swipeDirection={['down']}` for the second one, that's why it was still swiping down.... :big_facepalm: 

Anyway thanks for the hint !
