### ISSUE TITLE
supportedOrientations throwing error (in Typescript)

### ISSUE THREAD

**Issue by JeremyBradshaw7** [react-native-community/react-native-modal#172]
Tried using supportedOrientations as per the docs and Typescript throws an error:

[ts] Property 'supportedOrientations' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Modal> & Readonly<{ children?: ReactNode; }> & Rea...'.

**Comment by mmazzarolo** [comment]
Do you mind adding its support [here](https://github.com/react-native-community/react-native-modal/blob/master/src/index.d.ts)?
