### ISSUE TITLE
How can I place the modal at certain location instead of just being centered?

### ISSUE THREAD

**Issue by ethanyuwang** [react-native-community/react-native-modal#174]
I noticed that by default the modal is centred in the middle of the screen, but for my case, I want to place it in the top half of the screen with a margin from the very top. How can I achieve this?

**Comment by Manoj002** [comment]
Hello @ethanyuwang 
you got it how to change position?
if yes, please share here too even im interested in it and will help others too

**Comment by mmazzarolo** [comment]
@Manoj002 I'd suggest you to take a look at the example folder: there's a modal here that spawns from the bottom (that you can easily tweak to make it show up from the top)

**Comment by Manoj002** [comment]
@mmazzarolo @lustigdev , thanks for your replies mates,
will check it by today and @mmazzarolo i guess my keyboard issue sorry for the notifications...

**Comment by mmazzarolo** [comment]
@Manoj002 no worries, and thanks @lustigdev ! 🥇

**Comment by mmazzarolo** [comment]
@lustigdev feel free to submit a PR and add your video to the README if you want ;)

**Comment by lustigdev** [comment]
@mmazzarolo That's really awesome! I'll certainly do that. Maybe for a few React Native libraries. 

Nothing is more valuable to me picking up a new tool than to see a quick video from scratch of it functioning from installation. 

Do you do interaction for any of the other react-community projects?

**Comment by lustigdev** [comment]
@manoj002 did you get a chance to try my solution yet?

Let me know how it works for you.

**Comment by lustigdev** [comment]
Sounds good. Enjoy your hopeful bout of relaxation being AFK. We as society don't get enough time for ourselves anymore. Good for you for taking time for yourself. 

Looking forward to checking out your website and repos too! Very cool stuff.

**Comment by Manoj002** [comment]
@lustigdev , hey buddy that saved my life thanks for that mate and @mmazzarolo it will be awesome if it will be added to readme

**Comment by lustigdev** [comment]
So glad it helped! That API is just a little confusing at first, but glad it helped. I'll submit a PR with a GIF to a few different libraries I use. For me, seeing a video of install / setup / usage is much more valuable than text.

If you could just give a like on that video, I'd appreciate it! I've also got more videos similar on my channel and will be adding more :)

**Comment by Manoj002** [comment]
@lustigdev , awesome would love to !
