### ISSUE TITLE
"react-native-modal": "^6.0.0",

### ISSUE THREAD

**Issue by clycheng2015** [react-native-community/react-native-modal#175]
### When reporting a bug, please be sure to check if the issue still persists with react-native original modal:
Under the hood `react-native-modal` uses react-native original [Modal component](https://facebook.github.io/react-native/docs/modal.html).  
Before reporting a bug, try swapping `react-native-modal` with react-native original Modal component to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

**Comment by clycheng2015** [comment]
"react": "^16.0.0-alpha.12",
    "react-native": "^0.48.1",
    "react-native-modal": "^6.0.0",
 when the model show more than one time on my android mobile,the modal background(backdrop) is blacker and blacker,and then the bg is come to  black,that can,t see the view beheind the modal ,it is terribe!this seems to relates to moblie memory?do you thnow why??

**Comment by mmazzarolo** [comment]
Hey!
1. You cannot show multiple modals at the same time
2. You can find many other issues related related to this in the closed issues list
3. Please fill and follow the issue template before submitting a new issue
