### ISSUE TITLE
Modal flashes. appearing again after being dismissed

### ISSUE THREAD

**Issue by yasir-netlinks** [react-native-community/react-native-modal#176]
Hi there, sorry for posting this here, I am facing a problem... I am using version `5.4.0` and this is happening on iOS , not sure if it's happening on android. This problem wasn't noticed at all on simulator, but when running on a real device

When dismissing the modal, it flickers sometimes, meaning that when dismissed and the modal disappears, it reappears again (right away) and then gone again. This happens fast , as if it flashes the modal. (this happens only sometimes)

**Comment by mmazzarolo** [comment]
Hi!
Please fill all the needed info in issue template, thanks!

### When reporting a bug, please be sure to check if the issue still persists with react-native original modal:
Under the hood `react-native-modal` uses react-native original [Modal component](https://facebook.github.io/react-native/docs/modal.html).  
Before reporting a bug, try swapping `react-native-modal` with react-native original Modal component to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior


### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

### Please note by far the quickest way to get a new feature is to file a Pull Request.

**Comment by ajaykumar97** [comment]
I also have the same issues.

**Comment by harzkr** [comment]
Hi @yasir-netlinks  and @ajaykumar97 
Did you get a chance to work around it ? Any fixes ?
Im facing the same issue on iOS device, do not see it in Android or the emulators.

**Comment by ajaykumar97** [comment]
I got the solution. just disable useNativeDriver i.e. `useNativeDriver={false}`

**Comment by harzkr** [comment]
Wonderful! @ajaykumar97  Thank you for the resolution. Will try it.

**Comment by harzkr** [comment]
@ajaykumar97 No this does not work, setting `useNativeDriver={false}`, still getting the issue on iOS devices. I am removing the modal altogether, will be using a separate route to write the functionalities of the modal there
