### ISSUE TITLE
Modal Take Up only Part of Screen

### ISSUE THREAD

**Issue by TylerNRobertson** [react-native-community/react-native-modal#177]
Not looking to make a bug report but have a question. Is there any way to make this modal only cover a certain percentage of the screen and leave the rest able to be tapped on still? I have buttons that will be above the modal but belong to the parent of the Modal that is technically behind it.

**Comment by mike-niemand** [comment]
A modal by definition must force a user to interact with it before returning to the application. You're probably looking for a message box or similar.

**Comment by mmazzarolo** [comment]
@mike-niemand thanks 👍 

@TylerNRobertson I agree with Mike, I'm sorry but this it out of the scope of the library :(
