### ISSUE TITLE
App on babel error after upgrading to RN 0.56.0

### ISSUE THREAD

**Issue by thatjuan** [react-native-community/react-native-modal#178]
Hello,

My app fails to start after upgrading from RN 0.55 to 0.56.0. After looking into it some more, I found that it's a babel error and it's pointing to react-native-modal. I'm using version 6.1.0.

The error reads:

>  bundling failed: ./node_modules/react-native-modal/src/index.js Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?

**Comment by Titozzz** [comment]
https://github.com/facebook/react-native/issues/20038. 
https://github.com/babel/babel/issues/7177.

These are also related

**Comment by mmazzarolo** [comment]
Ouch. Sorry but I'm a bit busy right now, anyone willing to recap what's happening/proposing a fix there?

**Comment by Titozzz** [comment]
This is not a fix and we definitely need to dig further, but in the meantime if it is critical for you, just transpile the index using REPL and paste it. 😭

**Comment by Titozzz** [comment]
https://github.com/react-native-community/react-native-modal/pull/179 @mmazzarolo @ashoat

**Comment by JChanceHud** [comment]
Proposed branch is working for my project, thanks @Titozzz @Ashoat!

**Comment by mmazzarolo** [comment]
Can I safely bump the minor? 
I haven't had a chance to test it.
Otherwise I'll just cut a new major.

**Comment by Ashoat** [comment]
Based on semver, this should only be a minor release. There should be no breaking changes.

**Comment by mmazzarolo** [comment]
Thanks @Ashoat  (and also thanks for finding the workaround!)

**Comment by mmazzarolo** [comment]
Minor released 🎉

**Comment by thatjuan** [comment]
Yay, that worked! Thanks @Ashoat and @mmazzarolo
