### ISSUE TITLE
Edit how far the modal exits

### ISSUE THREAD

**Issue by Vikaton** [react-native-community/react-native-modal#18]
Is there a way to edit how far the modal exits? If I alter the size of the modal and I call hideModal, the modal itself drops a few, then abruptly disappears

**Comment by g3r4n** [comment]
Should be fixed in #15

**Comment by mmazzarolo** [comment]
Hey @Vikaton, #17 should fix it indeed.
I'll probably release it on NPM tomorrow. If you need it asap you can use the master branch.

**Comment by Vikaton** [comment]
Thank you!

**Comment by mmazzarolo** [comment]
Landed in [v2.3.2](https://github.com/react-native-community/react-native-modal/releases/tag/v2.3.2).  
Feel free to comment here if needed!
