### ISSUE TITLE
supportedOrientations warning on lastest version (v6.3.0)

### ISSUE THREAD

**Issue by kientux** [react-native-community/react-native-modal#183]
After upgrade from version `6.1.0` to `6.3.0`, this warning appears:

![simulator screen shot - iphone 8 - 2018-07-06 at 11 17 37](https://user-images.githubusercontent.com/4200743/42359783-7392991e-810e-11e8-8471-641f4460c68d.png)

My modal doesn't even have `supportedOrientations` prop:

```js
      <Modal
        style={styles.modal}
        isVisible={isVisible}
        backdropOpacity={0.3}
        onBackdropPress={onPressOutside}
      >
        <View style={styles.container}>
          <FlatList
            data={categories}
            keyExtractor={this.keyExtractor}
            renderItem={({ item }) => this.renderItem(item, () => onItemSelected(item))}
          />
        </View>
      </Modal>
```

I tried to add `supportedOrientations={["portrait"]}` but the warning still persists.

**Comment by jpinz** [comment]
Hi! The warning was fixed in the other pull request I made, just waiting for @mmazzarolo to make a new release with it and it should be all good! Sorry for the inconvenience!

**Comment by kientux** [comment]
The warning is gone with `v6.4.0`. Thanks for the quick fix!
