### ISSUE TITLE
where do you put the backdrop height?

### ISSUE THREAD

**Issue by quadsurf** [react-native-community/react-native-modal#184]
your readme says to first do this:
```
const IOS = Platform.OS === "ios";
const WIDTH = Dimensions.get("window").width;
const HEIGHT = IOS
  ? Dimensions.get("window").height
  : require("react-native-extra-dimensions-android").get("REAL_WINDOW_HEIGHT");
```

now that I have access to that new/true height, I tried sticking it in 2 of the places below, but neither worked:
```
<Modal ... style={{height:HEIGHT,width:WIDTH}}/>
```
(the above does not work)

```
<View style={{height:HEIGHT,width:WIDTH}}/>
   <Modal .../>
</View>
```
(the above does not work either)

since neither of the above two worked, where do i stick it? would be helpful to add this to the readme

**Comment by Andrei997** [comment]
Would also love to know!

**Comment by mmazzarolo** [comment]
Moving the discussione to the re-opened #147 👍

**Comment by lenvonsam** [comment]
how to set height prop in android

**Comment by DimitrisTzimikas** [comment]
Just do that...
https://github.com/listenzz/react-native-modal-translucent
