### ISSUE TITLE
KeyboardAvoidingView with taps handled

### ISSUE THREAD

**Issue by jetre219** [react-native-community/react-native-modal#189]
Hi, actually with the KeyboardAvoidingView boolean, when you click on something else than the keyboard on the device's screen, it closes the keyboard. So, even if I click a button the keyboard is still dismissed and the button is not clicked, so I have to do two taps to reach my button. I don't know if their will be an easy way for you to put a props like the react-native keyboardShouldPersistTaps one.

**Comment by shuzootani** [comment]
@jetre219 Did you find any solution to this 'two taps' issue?

**Comment by devdebajyotidas** [comment]
Also bumped into this. Any workaround so far?

**Comment by marcbc** [comment]
Same here, first tap outside the keyboard hides it, but it seems to be captured, and the actual button clicked on screen doesn't trigger the onPress action.

**Comment by vladb95** [comment]
why did you close this issue? any solution?

**Comment by brmk** [comment]
having the same issue

**Comment by Sydney-o9** [comment]
Apply this to your scroll view. See https://stackoverflow.com/questions/56067862/need-to-click-twice-in-keyboardavoidingview-even-when-keyboardshouldpersisttaps
```
keyboardShouldPersistTaps="handled"
```
