### ISSUE TITLE
3rd image in demo on github not visible. Image not found 404 error.

### ISSUE THREAD

**Issue by kalwaniyash** [react-native-community/react-native-modal#190]
The 3rd image in the demo section on github is not visible. On redirection it shows a 404 error.
Error: 404: Not Found
Re-directed url: https://raw.githubusercontent.com/pistonsky/react-native-modal/master/.github/example-modal.gif

**Comment by mmazzarolo** [comment]
Whops, fixed it, thanks @kalwaniyash ! ❤️

**Comment by kalwaniyash** [comment]
The same issue is still existing on npm.

**Comment by mmazzarolo** [comment]
Yep, it will be solved by the next release
