### ISSUE TITLE
How can we specify no animation?

### ISSUE THREAD

**Issue by JeremyBradshaw7** [react-native-community/react-native-modal#191]
How can we specify no animation via animationIn and animationOut props? 

If we don't pass the props at all it activates the default slide transitions. I've tried passing {} and 'none' for both props but it still defaults to the slide.

**Comment by mmazzarolo** [comment]
Hey!
See #153

**Comment by JeremyBradshaw7** [comment]
Yeah not really the answer I was looking for, but OK.

**Comment by ken0x0a** [comment]
```js
<Modal
            animationIn={{ from: { opacity: 1 }, to: { opacity: 1 } }}
            animationOut={{ from: { opacity: 0 }, to: { opacity: 0 } }}
            animationInTiming={0}
            animationOutTiming={0}
>
```
This did not solve my problem though.
