### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by josephkim583** [react-native-community/react-native-modal#195]
How can I make the modal not cover the whole screen? Can I just have a small container box in the middle of the screen? Also how do I make the modal appear and disappear faster?

**Comment by mmazzarolo** [comment]
Please see the props in the README.
With them you can adjust the animation timing, decrease the backdrop opacity and the size of the modal. Also, check the example folder :)

**Comment by Thembelani** [comment]
Hi @mmazzarolo . Instead of making this a test for this guy and the rest of us who have no idea how this plugin works, you could have stated which property he/we should look out for.
Thanks,

**Comment by rewieer** [comment]
Hi @Thembelani, we created a README file and a very complete example project so that we don't have to answer such questions individually. If you feel like the README file isn't complete enough, you're most welcome to fill a PR 😃

**Comment by mmazzarolo** [comment]
@Thembelani I'm sorry, didn't want to sound rude. Unfortunately we can't answer every generic question is asked in the GitHub issues, it would be really time consuming.  
I would suggest you to be a bit more specific and, as a rule of thumb, ask non-issue questions to StackOverflow. Thanks!
