### ISSUE TITLE
Scrollable modal with swipe feature is not smooth enough (tested in android devices

### ISSUE THREAD

**Issue by bbeckk** [react-native-community/react-native-modal#199]
I have used Scrollable modal from the example but it is not smooth enough. It stops for a sec and then starts scrolling again. I wanted to make a comment sections like facebook which is very smooth. What might be the reason? I had used it in my project but it was not smooth, so I tried the example you have provided which gives the same result.

       <Modal
          isVisible={this.state.visibleModal === 8}
          onSwipe={() => this.setState({ visibleModal: null })}
          swipeDirection="down"
          scrollTo={this.handleScrollTo}
          scrollOffset={this.state.scrollOffset}
          scrollOffsetMax={400 - 300} // content height - ScrollView height
          style={styles.bottomModal}
        >
          <View style={styles.scrollableModal}>
            <ScrollView
              ref={ref => (this.scrollViewRef = ref)}
              onScroll={this.handleOnScroll}
              scrollEventThrottle={16}
            >
              <View style={styles.scrollableModalContent1}>
                <Text>Scroll me up</Text>
              </View>
              <View style={styles.scrollableModalContent1}>
                <Text>Scroll me up</Text>
              </View>
            </ScrollView>
          </View>
        </Modal>

See the video of modal in android samsung device (nougat)
https://youtu.be/5JX-flj5Jgs

Now see how smooth is fb comment modal in the same device.

https://youtu.be/cE8-79TcVtg

**Comment by mmazzarolo** [comment]
Are you running the app in development mode?

**Comment by bbeckk** [comment]
yeahh...

**Comment by mmazzarolo** [comment]
Could you try it in release mode? 🌊

**Comment by huylv-teko** [comment]
i tried in release mode but still same behavior with dev mode. I spent many weeks to research on internet but didn't found any working example (without using native bridge). Seem there are no way to archived this (same ui with facebook).

**Comment by Ol1va** [comment]
Same issue. Has anyone found a solution?
I believe it happens because of onSwipeComplete. When I stop swiping component freezes for a sec and then it closes.
