### ISSUE TITLE
How to show modal with no animation?

### ISSUE THREAD

**Issue by pareksha** [react-native-community/react-native-modal#201]
I want to show modal without any animation, it is like doing `animationType: "none"` as in the original Modal of react-native. This library is quite easy to use, does this support `no animation modal`?

**Comment by mmazzarolo** [comment]
Hi! 
#191 ?

**Comment by pareksha** [comment]
I have made the PR, please review https://github.com/react-native-community/react-native-modal/pull/202

**Comment by veyseler-su** [comment]
I used a hack for that problem. Simply use small floating number for animationInTiming and animationOutTiming. I used 0.1 and the modal pops instantly like it does not have any animation at all :)

**Comment by EhsanSarshar** [comment]
why you not use View instead of Modal
