### ISSUE TITLE
Recommended use with a global loading spinner

### ISSUE THREAD

**Issue by grit96** [react-native-community/react-native-modal#203]
In my application I have a top-level global spinner component using the ActivityIndicator in an absolutely positioned View controlled by a visible prop. It displays fine when a modal is not open.

I have a number of modals in various places in my app, and the modals always show on top of the spinner even though the spinner is hierarchically at the end of the application.

What is the recommended solution for this problem?

**Comment by mmazzarolo** [comment]
Hey!
A modal, by definition, will always be positioned above all the other Views of the app, regardless the View hierarchy. 

If you need to show the activity indicator even above the modal I guess you can integrate it in a Modal wrapper which will:
- show the modal content when not loading
- show the spinner when loading

**Comment by grit96** [comment]
After doing some testing, it appears that when I build my spinner using the 'react-native' Modal component it displays over the top of the 'react-native-modal' Modal when I run the app on Android, but not on iOS.

**Comment by mmazzarolo** [comment]
React-native-modal uses 'react-native' modal under the hood and you can have two of them displayed at the same time unfortunately.

**Comment by grit96** [comment]
Okay, thanks. I've decided to go with the modal wrapper method that wraps the content with a spinner. It's interesting that the behaviour of multiple modals is different on Android and iOS.

**Comment by mmazzarolo** [comment]
> It's interesting that the behaviour of multiple modals is different on Android and iOS.
Yeah, I know :/ 

Thanks for the discussion.
