### ISSUE TITLE
Question about multiple modals

### ISSUE THREAD

**Issue by David-Haile** [react-native-community/react-native-modal#204]
Hi.

I just installed this package and used it with success. However when trying multiple modals this posed a small challenge. I then checked the examples and noticed you could achieve this by creating new instances of '_toggleModal' (, _toggleModal2 etc.) as well as multiple states (isModalVisible1, isModalVisible2, etc.).

However this makes it so you have repetitive code. Is there a more practical way to solve this problem so that you don't have repetitive code? I'm not too experienced with js but I would assume you'd have an array of states and some sort of switch for it.

EDIT: This is about clicking a button, showing a modal, hiding the said modal and clicking a different button that shows a different modal with different content and NOT showing overlaying modals.

Any suggestions or ideas?

**Comment by mmazzarolo** [comment]
🤔 I'm not sure that I'm following what you mean. 
If you want two different modals I would just create two separate components (e.g.: `Modal1`, `Modal2`) and save in the state which one you want to show. 
Something like this:
```javascript
import React, { Component } from "react";
import { Text, TouchableOpacity, View } from "react-native";
import Modal from "react-native-modal";

export default class ModalTester extends Component {
  state = {
    visibleModal: null // Can be 'Modal1' or 'Modal2'
  };

  showModal = (modalName) => {
    this.setState({ visibleModal: modalName });
  }
  
  hideModal = () => {
    this.setState({ visibleModal: null });
  } 

  render() {
    return (
      <View style={{ flex: 1 }}>
        <TouchableOpacity onPress={() => this.showModal("Modal1")}>
          <Text>Show Modal 1</Text>
        </TouchableOpacity>
        <TouchableOpacity onPress={() => this.showModal("Modal2")}>
          <Text>Show Modal 2</Text>
        </TouchableOpacity>
        <YourCustomModal1 isVisible={this.state.visibleModal === "Modal1"} />
        <YourCustomModal2 isVisible={this.state.visibleModal === "Modal1"} />
        </Modal>
      </View>
    );
  }
}
```

**Comment by David-Haile** [comment]
Hi, sorry for the late response.

As of now the way I made sure I showed modals with different content is with the code shown below. However if I want a third togglable modal, I would need a _toggleModal3. 
`
export default class SvgScreen extends React.Component {  
state = { isModalVisible: false, isModalVisible2: false};

  _toggleModal = () =>
    this.setState ({ isModalVisible: !this.state.isModalVisible});

  _toggleModal2 = () =>
    this.setState ({ isModalVisible2: !this.state.isModalVisible2});

<Modal isVisible={this.state.isModalVisible} onBackdropPress={this._toggleModal}>
       <View style={{backgroundColor:'#fff'}}>
             <Text>Modal 1</Text>
        </View>
</Modal>

<Modal isVisible={this.state.isModalVisible} onBackdropPress={this._toggleModal}>
        <View style={{backgroundColor:'#fff'}}>
             <Text>Modal 2</Text>
        </View>
</Modal>
`
I see that your implementation is more fitting and eleminates the duplicate code rather than copy pasting the same thing over and over again for each additional modal. I'm going to try it out and see if it works for me as well, thank you for the reply.
