### ISSUE TITLE
backdrop can't cover the StatusBar

### ISSUE THREAD

**Issue by YanmaY** [react-native-community/react-native-modal#206]
What I want is like this:

![tim 20180911154440](https://user-images.githubusercontent.com/7043862/45345978-7974dd00-b5da-11e8-861d-d77c11f2eb4b.jpg)

What I got is like this:
![tim 20180911154553](https://user-images.githubusercontent.com/7043862/45345982-7da0fa80-b5da-11e8-9544-14ac51e9d5c3.jpg)

How can I make the backdrop cover the StatusBar?

**Comment by mmazzarolo** [comment]
See #50 😢

**Comment by alvintheodora** [comment]
@mmazzarolo @YanmaY  do you have the solution? could you share the code snippet here? I'm also having this issue. The modal doesnt cover the statusbar

**Comment by YanmaY** [comment]
@alvintheodora [react-native-modal-translucent](https://github.com/listenzz/react-native-modal-translucent)
