### ISSUE TITLE
Native error on hide

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-community/react-native-modal#21]
The message is:

> **The specified child already has a parent. You must call removeView() on the child’s parent first.**

I'm seeing this whenever I hide the modal. I'm not sure if the modal causes this, I'm just _really_ hoping someone sees this error and goes _"oh, yeah you're just being stupid. Do <42> to solve your problem"_.

This only happens on android and works fine on ios.

```
addViewInner
    ViewGroup.java:4417
addView
    ViewGroup.java:4258
addView
    ViewGroup.java:4198
addView
    ReactViewManager.java:209
addView
    ReactViewManager.java:41
manageChildren
    NativeViewHierarchyManager.java:394
execute
    UIViewOperationQueue.java:179
run
    UIViewOperationQueue.java:787
flushPendingBatches
    UIViewOperationQueue.java:843
access$1600
    UIViewOperationQueue.java:48
doFrameGuarded
    UIViewOperationQueue.java:889
doFrame
    GuardedFrameCallback.java:31
doFrame
    ReactChoreographer.java:129
doFrame
    ChoreographerCompat.java:107
run
    Choreographer.java:872
doCallbacks
    Choreographer.java:686
doFrame
    Choreographer.java:618
run
    Choreographer.java:860
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
loop
    Looper.java:154
main
    ActivityThread.java:6119
invoke
    Method.java:-2
run
    ZygoteInit.java:886
main
    ZygoteInit.java:776
```

**Comment by RWOverdijk** [comment]
**Update:** It happens as soon as the modal has an Image as content. So this works:

```jsx
<Modal isVisible={this.props.active} animationIn="fadeIn" animationOut="fadeOut" animationOutTiming={300}>
        <Text>Hello world</Text>
      </Modal>
```

And this doesn't, and causes the error:

```jsx
<Modal isVisible={this.props.active} animationIn="fadeIn" animationOut="fadeOut" animationOutTiming={300}>
        <Image style={styles.desertImage} source={Images[this.props.image || 'desert']} />
      </Modal>
```

**Comment by mmazzarolo** [comment]
Hi @RWOverdijk , thanks for reporting the issue.  
Could you try wrapping the `Image` in another `View` (and maybe toy a bit with its style)?

**Comment by RWOverdijk** [comment]
@mmazzarolo The View didn't change anything unfortunately. What do you mean by toying with styling? By the way, are you guys on gitter / slack somewhere?

**Comment by mmazzarolo** [comment]
> What do you mean by toying with styling?

My fault, I wasn't explicit enough.  
Being an Android-only issue, this might be related with how the layout is handled, so it might be worth applying/removing `flex: 1` or a fixed width/height to the `View`, just to see if it changes anything.   
Another thing worth investigating is the [`onLayout`](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js#L147) prop applied to the Modal.  

> By the way, are you guys on gitter / slack somewhere?  

I'm the only maintainer right now and this lib has been moved to `react-native-community` only recently, so I'm not on gitter/slack yet 🙍  
Also, I have a full time job so I can't code on the Github projects during my working hours (but I can still chat and answer to issues without any problem). 
  

Note for self: [these issues may be useful](https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=image%20onlayout).

**Comment by RWOverdijk** [comment]
@mmazzarolo Same here, also combining my job with OS work. I may be able to chip in a bit, but that does involve a learning period. I'm [here](https://gitter.im/spoonx/dev) and [here](https://gitter.im/RWOverdijk).

As to the issue at hand, I don't think styling is involved. It's trying about setting a child element. I tried a bunch and nothing appears to work for me. I'll dig deeper on the train.

**Comment by mmazzarolo** [comment]
Just created a chat room for [on Gitter for react-native-modal](https://gitter.im/react-native-modal/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link), but I'll probably ask other react-native-community maintainers for a unified room.

**Comment by RWOverdijk** [comment]
Disappeared as soon as I just rebuilt my app. So not sure what caused it. I can no longer reproduce it.
