### ISSUE TITLE
Create github page for adding docz

### ISSUE THREAD

**Issue by nicholasess** [react-native-community/react-native-modal#210]
Hi everyone!
I'm member of the core team [docz](https://github.com/pedronauck/docz) and i will send a PR with docs to react-native-modal. Before that, i need that you create in settings the github page in branch master the directory ```docs```. 

After tell me when the github page created.

Thanks

**Comment by mmazzarolo** [comment]
Hey @nicholasess !
First of all, you're all doing a great job with docz! I've been following the project for a while now and it looks like it's growing really fast.  

That say, I don't have access to the settings of this repo (but I may contact the organization admin if needed).  

Are you sure that docz will work with react-native-modal? IIRC the react-native docz integration uses react-native-web which had a few issues with both the modal component and react-native-animatable.

**Comment by nicholasess** [comment]
@mmazzarolo Nice feature, i thought about documentation just with images, but add the package with features in playground it so beautiful.

We can have two steps, first create documentation with images and second update with playground.

Do you accept it?
