### ISSUE TITLE
Overlap modal component by react-navigation screen. [Help Wanted]

### ISSUE THREAD

**Issue by hupptechnologies** [react-native-community/react-native-modal#211]
Hello,

I have built app that open enter password/pin screen every time when app goes to background and back to active state, but when i put app in background with modal opened then come back modal still stays over password screen. I know this is not  an bug but i want solution for it. I tried my manipulating style but seems modal is higher in view stack then my password screen and modal has been used at every screen as alert behaviour.

Does anyone have solid solution for it ?

Thanks.

**Version Info**
react-native: 0.53.3
react-native-modal: 5.3.0
react-navigation: 1.5.8

**Comment by mmazzarolo** [comment]
> seems modal is higher in view stack

Yep, that's what a modal does.  
You need to handle the visibility of the modal in some ways, for example by hiding it before the app goes to the background.  
That said, you should ask this question on stackoverflow since it's not a feature request nor a bug report 😞
