### ISSUE TITLE
Modal is not updating

### ISSUE THREAD

**Issue by manoel17rpn** [react-native-community/react-native-modal#214]
Hi, 
I am showing information in my APP via the modal. When I close the modal, and in another window of the APP I update the information, and open the modal again the information is outdated.

In my code, I created the modal in a specific file, in a class with the render method. And the information is passed via props. In the modal class, I put the method shouldComponentUpdate and componentWillReceiveProps to update the props, and in the componentWillReceiveProps method I put a console.log (nextProps); to see if the information was arriving correctly updated, and yes yes updated. But the texts do not update

**Comment by mmazzarolo** [comment]
Hey!
Please read the [issue template](https://github.com/react-native-community/react-native-modal/blob/master/ISSUE_TEMPLATE.md) before submitting a new issue/question.  
Thank you 🙏
