### ISSUE TITLE
How to create a drop-down modal menu?

### ISSUE THREAD

**Issue by kdenz** [react-native-community/react-native-modal#22]
I figured that I would to precisely determine the position of the modal, so that when it appears, it appears right below the button which opens it. How should I approach it with react-native-modal? Thanks!

**Comment by g3r4n** [comment]
Can you share a design of what you tried to achieved ?

**Comment by ng-hai** [comment]
I think you should try `react-native-menu`

**Comment by mmazzarolo** [comment]
Closing it, feel free to reopen if still needed :)
