### ISSUE TITLE
Button OnPress

### ISSUE THREAD

**Issue by MohamedShaw** [react-native-community/react-native-modal#220]
in modal when i use RactButton inside modal onPress isnot working 
only work TouchableOpacity onPress ? 
what this problem >
any solution?
<Modal
      animationIn="bounceIn"
       animationOut="bounceOut"
	useNativeDriver
	hideModalContentWhileAnimating
	backdropOpacity={0.55}
				
	isVisible={this.state.orderData.status === "ARRIVED" }
>
<View style={styles.modalContentContainer}>
	<TouchableOpacity
		onPress={() => {
			this.onRefusedOrder()
		}}
	</TouchableOpacity>
</View>
</Modal> //this it work correctly
<Modal
      animationIn="bounceIn"
       animationOut="bounceOut"
	useNativeDriver
	hideModalContentWhileAnimating
	backdropOpacity={0.55}
				
	isVisible={this.state.orderData.status === "ARRIVED" }
>
<View style={styles.modalContentContainer}>
	<RectButton
		onPress={() => {
			this.onRefusedOrder()
		}}
	</RectButton>
</View>
</Modal> //Not working

**Comment by mmazzarolo** [comment]
Hey!
Could you please follow the [issue template](https://github.com/react-native-community/react-native-modal/blob/master/ISSUE_TEMPLATE.md)? Thanks!
