### ISSUE TITLE
How to have modal window in to separate component?

### ISSUE THREAD

**Issue by vivekshah-zymr** [react-native-community/react-native-modal#223]
Hello, 
I am having multiple model popup in my single main screen. So I want every popup as a separate component. (So code reusability and cleanness can maintain.) And from my main screen, I want to open that multiple popup as a component.

Let say, My popup1 is as a separate component as below.

```
import Modal from "react-native-modal";
class Popup1 extends Component {
    render() {
        return (
            <Modal >
            // Other stuff like button and textbox
            </Modal>
        );
    }
}
```
Same like above I have Popup2, Popup3 and Popup4.
Now My main screen looks like below.

```
import Popup1 from '../Popup1/Popup1.js'
import Popup2 from '../Popup2/Popup2.js'
class MainScreen extends Component {
    render() {
        return (
            // Other Component
            <Popup1 isVisible={this.state.isPopup1Visible}></Popup1>
            <Popup2 isVisible={this.state.isPopup2Visible}></Popup2>
            // Other Component
            );
    }
}
```

Now, I don't know how to handle events from MainScreen and Popup component. And also pass parameter and details between this popup and main screen.
Please help me out of this.

**Comment by mmazzarolo** [comment]
@vivekshah-zymr you can just pass all the props of the Modal to your custom component using the spread operator:  

```javascript
import Modal from "react-native-modal";

class Popup1 extends Component {
    render() {
        return (
            <Modal {...this.props}>
            // Other stuff like button and textbox
            </Modal>
        );
    }
}
```

Give it a try and let me know if it works for you!

Also, closing the issue since it's not an issue :)
