### ISSUE TITLE
Modal flicker on close [iOS]

### ISSUE THREAD

**Issue by stefanc96** [react-native-community/react-native-modal#232]
When i close a modal on iOS with nativeDriver , this causes a flicker at the end which i think it is because the children component it is rendered one more time.

**Comment by hoboman313** [comment]
I'm seeing the same problem. How did you solve it?

**Comment by Ilario17** [comment]
How did you solve this issue?

**Comment by stefanc96** [comment]
I've changed from use this module to react-native-popup-dialog

**Comment by stefanc96** [comment]
But don't use nativeDriver to remove flicker

**Comment by Ilario17** [comment]
Thank you, I already tried to use useNativeDriver={false} but this not solve the issue.

**Comment by jtanner** [comment]
`useNativeDriver={true}` fixed it for me.
