### ISSUE TITLE
Opening another modal using onModalHide not working.

### ISSUE THREAD

**Issue by rendomnet** [react-native-community/react-native-modal#234]
For example I have modal with several menu items which will open another System modals like Camera or Share.

Modal --> [ Camera --> Camera modal, Share ---> Share modal] 

When I click on camera I want to close current Modal screen and launch Camera modal.
Or when I click Share item in Modal I want to close current modal and the open Share.

I don't want several modal screens at the same time.
Right now when I use onModalHide={()=> openCamera()} it will just crash ui.
I cant open another modals from onModalHide, but I thought onModalHide is perfect safe place to launch other modals?

**Comment by mmazzarolo** [comment]
> I cant open another modals from onModalHide, but I thought onModalHide is perfect safe place to launch other modals?  

It should work. 
Are you sure this is a react-native-modal issue? Could you try adding a small delay (like 1s) in the `onModalHide` before opening the camera just to check if it fixes the issue? 
If it does fix the issue it should be worth checking if moving the `onModalHide` as a callback of [this setState](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js#L398) completely fixes the issue.

**Comment by mmazzarolo** [comment]
@rendomnet any news?

**Comment by rendomnet** [comment]
@mmazzarolo for now I cant test it because this issue  was forced me to not use react-native-modal. You can try it on Share modal  https://facebook.github.io/react-native/docs/share or [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) with this modals I had problems.
I think there is some conflict with animations... when several modals are on screen.
I don't like using timeouts because it feels like hack.

**Comment by mmazzarolo** [comment]
> You can try it on Share modal facebook.github.io/react-native/docs/share or react-native-image-crop-picker with this modals I had problems.  

The share API is working fine for me on a production app (triggered in `onModalHide`) 🤔  

> I don't like using timeouts because it feels like hack. 

I'm not saying you should use it, I was just suggesting to try it to see if it was a timing issue.

**Comment by mmazzarolo** [comment]
Closing for inactivty, @rendomnet let me know if you have a chance to check that.

**Comment by EricWiener** [comment]
I'm having a similar issue. I followed your advice and added a 1-second delay and it works now, but this doesn't seem like the ideal situation.

**Comment by ethanyuwang** [comment]
Same issue here

**Comment by AlexeyJersey** [comment]
Same issue.
I'm trying to open react-native Share modal from react-native-modal and using onModalHide callback.
After RNModal closes - Share modal appears for some ms and disappears immediately.
setTimeout(() => {}, 0) - helped, but seems like ugly hack.

**Comment by inepineee** [comment]
I am currently facing the same issue on iOS with alerts. I am trying to show an alert in the onHide callback. The alert is visible for a ms before disappearing. 

Using setTimeout in the callback works, but I don't like doing that
