### ISSUE TITLE
How to dim part of the screen no the whole when opening the modal 

### ISSUE THREAD

**Issue by reemtariqq** [react-native-community/react-native-modal#235]
I want to dim part of the screen, not the whole when opening the modal, which means let the bottom menu clickable and not to be under the opacity .4 which is related to the background, any idea how?

I tried to change the height and the width which applied on it the dimming with opacity but it wasn't clickable

**Comment by mmazzarolo** [comment]
Unfortunately the react-native modal used under the hood will cover the entire screen (since it's a modal).  
I think what you want here is an absolutely positioned view instead to cover just the interested part of the screen.

**Comment by hungcuiga1** [comment]
Hi @reemtariqq . Now, Have you solved it yet? Thank you
