### ISSUE TITLE
Modal to fit containerWidth, containerHeight instead of deviceWidth, deviceHeight

### ISSUE THREAD

**Issue by serfgy** [react-native-community/react-native-modal#237]
Hi, I understand that the point of a modal is to cover the device width and height, but in the event of a user requirement for container width and height, you mentioned that you can override backdrop style. What are the options if you do not wish to fork the repository and maintain the code?

For example, is this how you would 'override' with the code below? (in actual code, not in the modal lib)

```
<Modal>
    <View style={[styles.modal,{width: X, height: X}]}></View>
</Modal>
```

The actual desired effect is as seen with react-native-modalbox, where the modal takes up the full size of the container it is in, what should we configure to achieve as close to that?

**Comment by mmazzarolo** [comment]
Hi!
It think the margin suggestion at #129 might be what you’re looking for. 
If it does, please let me know so that we can add it to the the readme :)

**Comment by serfgy** [comment]
Thanks for replying!

I am actually looking along the lines of this:
https://github.com/maxs15/react-native-modalbox/commit/15488d4cccb252212f0603f632c0766d20774c70

I am not sure how to replicate this behaviour in react native modal

**Comment by mmazzarolo** [comment]
Ha! Got it. 
Overriding the backdrop style is not officially exposed because even if you override it the content below it won't be clickable.  
Could you share your use-case?

**Comment by serfgy** [comment]
![image](https://user-images.githubusercontent.com/20569525/51242083-10530b00-19ba-11e9-870d-3930cb117c29.png)
![image](https://user-images.githubusercontent.com/20569525/51242090-19dc7300-19ba-11e9-94a1-2f3deaa5fc3d.png)
As mobile devices get bigger, there may be cases where a modal would not be expected to fit the entire screen, but rather its parent container. An option such as fullScreen={true} would cover this exhaustively 👍

**Comment by mmazzarolo** [comment]
Gotcha, yeah it makes sense... but unfortunately the react-native original modal (the one used under the hood in this component) will always be full screen :/
