### ISSUE TITLE
react-native-modal doesn't behave well with react-native-webview

### ISSUE THREAD

**Issue by Nermin-K** [react-native-community/react-native-modal#240]
react-native-modal works fine but when trying to render `<WebView>` inside the `<Modal>` the `backdropColor` is white instead of black and the modal cover the whole screen till I scroll the `<WebView>`. Once I scroll the `<WebView>` everything works fine! 

**before scrolling**
![screenshot_2019-01-24-19-14-37-011_com growthhack](https://user-images.githubusercontent.com/30387225/51696241-a962d100-200d-11e9-807c-051ab0b965c1.png)
**after scrolling**
![screenshot_2019-01-24-19-14-46-847_com growthhack](https://user-images.githubusercontent.com/30387225/51696247-b089df00-200d-11e9-9789-838cc5a884af.png)

**Modal**
`<Modal 
                isVisible={this.state.modalVisible}
                onBackButtonPress={() => this.setModalVisible(false)}
                onBackdropPress={() => this.setModalVisible(false)}
                >
                    <View style={styles.modal}>
                        <View style={styles.modalTop}>
                            <Image source={require('../../assets/icons/logo.png')} style={styles.smallIcon} />
                            <Text style={styles.modalTopText} >About App</Text>
                        </View>
                        <About />
                        <View style={styles.modalBottom}>
                            <Text style={styles.modalBottomText} onPress={() => this.setModalVisible(false)}>CLOSE</Text>
                        </View>
                    </View>
                </Modal>`

`modal: { 
        flex: 1,
        backgroundColor: '#fff',
        borderRadius: 5
    },
    modalTop: {
        height: 50,
        flexDirection: 'row',
        marginTop: 15,
        marginLeft: 20,
    },
    modalTopText: {
        color: '#000',
        fontSize: 20,
        fontWeight: '300',
        marginTop: 8,
    },
    modalBottom: {
        height: 35,
        marginTop: 15,
    },
    modalBottomText: {
        color: '#b13230',
        textAlign: 'right',
        marginRight: 10,
        fontSize: 15
    }`

**About**
here is what is inside `<About />` in the Modal
`<WebView
        ref={(ref) => { this.webview = ref; }}
        source={{ uri: 'https://growthhacktoolkit.com/android/about.html' }}
        style={{ flex: 1 }}
        scalesPageToFit={true}
      />`

- "react-native": "0.57.8"
- "react": "16.6.3"
- "react-native-webview": "^3.1.2"
- "react-native-modal": "^7.0.2"
- android
- redmi note 4 - android version 7.0
- windows 10

**Comment by mmazzarolo** [comment]
Hey @Nermin-K , thank you for adding all the required informations in the issue 🙏 
First of all, could you try changing the `WebView` style to: 
```js
style={{ 
  flex: 1,
  margin: 40,
}}
```
and let me know if it still covers then entire screen before scrolling? 
(I'm not saying this should be the real solution to the issue, I'm just trying to understand what is happening).

**Comment by mmazzarolo** [comment]
Also, could you try playing around with `modal: { flex: 1, backgroundColor: '#fff', borderRadius: 5 }` by adding a margin here as well?

**Comment by mmazzarolo** [comment]
And one last: could you try it on iOS and/or a different Android device?

**Comment by mmazzarolo** [comment]
@Nermin-K thanks for reporting in. Since it seems to be a react-native's own modal issue I'll close this but feel free to post more info if you get any news.

**Comment by iamandiradu** [comment]
I'm also having the same issue with Modal and WebView :(. Hope to find a fix for this :).

**Comment by simonsisay** [comment]
Try wrapping the webview inside a view. 
<Modal>
    <View>
          <WebView />
    </View>
</Modal>

and apply style to the view that is wrapping the webView component.

**Comment by c19354837** [comment]
Update `react-native-webview` to `5.8.2` will fix these issue.

**Comment by cyb3rsalih** [comment]
Now have same problem with `"react-native-webview": "^10.9.0"`

This style solves my problem.
```
style={{ 
  flex: 1,
  margin: 40,
}}
```

But, I see glitchy animations on screen, like flickering status bar.

Have you any idea @mmazzarolo . 
Thanks.
