### ISSUE TITLE
Using it with a carousel

### ISSUE THREAD

**Issue by dnish** [react-native-community/react-native-modal#245]
Hey,
I'm trying to use this plugin with https://github.com/archriss/react-native-snap-carousel. The carousel is located within the modal. I'm using the "swipe down" gesture to close the modal, and left and right swipe to switch between the images within the carousel. The problem is that I'm not able to control the carousel anymore when it is located within the modal. It seems that the modal "overrides" the left and right swipe gestures. So my question is: Is it possible to use plugins that depend on swipe gestures within a modal that uses the swipe down gesture?

**Comment by mmazzarolo** [comment]
Hey @dnish , sorry for answering late. 
Please see #236 , the issue seems to be the same 👍 
Let me know if the new beta release has solved your issue.
