### ISSUE TITLE
Avoid keyboard

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-community/react-native-modal#25]
How can I avoid the keyboard with the modal? I tried KeyboardAvoidingView but that doesn't seem to do anything

**Comment by mmazzarolo** [comment]
I had the same issue when I started working on it and it [is still open on react-native issues](https://github.com/facebook/react-native/issues/10138).  
Did you find any workaround?

**Comment by RWOverdijk** [comment]
@mmazzarolo I just added a marginBottom and it then moves out of the way

**Comment by mmazzarolo** [comment]
Oh. That's nice 👍

**Comment by RWOverdijk** [comment]
It's still something to keep in mind, though. It's not a fix but a workaround :)
