### ISSUE TITLE
Keyboard pushes model input outside of view

### ISSUE THREAD

**Issue by canastro** [react-native-community/react-native-modal#252]
# Problem description
I have a modal with an input, when I focus the input the keyboard pushes the full modal up and makes the input not visible. Check video: https://monosnap.com/file/8CpXW2O7JgASLqUa545tJ0ECxsryai

I tried with the native modal and the problem persists.

# Expected behaviour
Should only push the view slightly up to make sure that the input is not behind the keyboard (as it usually happens when using KeyboardAvoidingView.

# Code Snippet

**Styles:**
```js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  modal: {
    margin: 0
  },
  wrapper: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'white',
    padding: 20,
    height: 550
  },
  ...
});
```

**JSX:**
```js
<Modal
    avoidKeyboard={false}
    style={styles.modal}
    isVisible={isOpen}
    onBackButtonPress={this.props.onCancel}
    onBackdropPress={this.props.onCancel}
>
    <View style={styles.wrapper}>
        <FormInput
            label="Quantity"
            type="number"
            required
            onChange={this.handleInputChange}
            value={this.state.quantity}
            error={errors.quantity}
        />
        ....
    </View>
</Modal>
```

# Versions
```
    "react": "16.6.3",
    "react-native": "0.58.3",
    "react-native-modal": "^7.0.2",
```

**Comment by mmazzarolo** [comment]
Hey @canastro , thanks for reporting the issue following the template 🙏 

Unfortunately the issue is not related to the `react-native-modal` package, it's just how the keyboard works on Android.  
I would suggest looking for a way to change the behaviour by searching for the `android:windowSoftInputMode` docs.

**Comment by vikramkh** [comment]
This happens for iOS as well. I think this should be reopened

**Comment by Elgert** [comment]
to me it happens only on Android, in iOS only the 'KeyboardAvoidingView' is pushed up, while in android the whole modal is pushed up

**Comment by aniruddhashevle** [comment]
This will help you: https://github.com/react-native-community/react-native-modal/issues/344#issuecomment-629400548
