### ISSUE TITLE
Swipe doesn't work 

### ISSUE THREAD

**Issue by jjanelee97** [react-native-community/react-native-modal#253]
Was working before but recently I'm getting this error when I try to swipe down on the modal.  The modal works when I close with the proper button but swiping returns this error: 
any ideas?
<img width="374" alt="screen shot 2019-02-15 at 7 10 25 am" src="https://user-images.githubusercontent.com/16146269/52855885-bc3e6200-30f0-11e9-822b-3f4dfa32ea58.png">

**Comment by jjanelee97** [comment]
<img width="827" alt="screen shot 2019-02-15 at 7 12 14 am" src="https://user-images.githubusercontent.com/16146269/52855960-06274800-30f1-11e9-93a3-8b6f647dc75a.png">

**Comment by mmazzarolo** [comment]
Hey @jjanelee97 could please follow the issue template? Thanks!

### When reporting a bug, please be sure to check if the issue still persists with react-native original modal:
Under the hood `react-native-modal` uses react-native original [Modal component](https://facebook.github.io/react-native/docs/modal.html).  
Before reporting a bug, try swapping `react-native-modal` with react-native original Modal component to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal` swap described above
- [ ] A descriptive title
- [ ] What version of `react-native-modal` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] **Most important of all:** An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)


### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

### Please note by far the quickest way to get a new feature is to file a Pull Request.
