### ISSUE TITLE
Modal goes up from pressing a TextInput on Android

### ISSUE THREAD

**Issue by Pazamozaurus** [react-native-community/react-native-modal#254]
Hey people.
I have a modal which contains a TextInput. When I press on the TextInput, the whole Modal goes up (I didn't use the AvoidKeyboard property when defining the modal, and I also tried to explicitly set it to false.
Here is the code of the render function of my component.

`

        return (
            <Modal isVisible={this.state.isVisible} backdropOpacity={0.4} onBackdropPress={() => this.setState({ isVisible: false })} onBackButtonPress={() => this.setState({ isVisible: false })} >
                <View style={styles.container}>
                    <View style={styles.divider}>
                        ...
                    </View>
                    <TextInput style={{backgroundColor: 'white'}}/>
                </View>
            </Modal>
        );
    }`

And when I press on the TextInput, the whole Modal goes up.
Here's what My modal looks like before
![before](https://user-images.githubusercontent.com/28194625/52949933-61be3380-3386-11e9-949f-54293666a2d9.png)

And here's how to looks like when I press on the textinput

![after](https://user-images.githubusercontent.com/28194625/52950166-faed4a00-3386-11e9-8451-2fba13315292.png)

I also should mention that when I used the regular react-native's Modal component instead of the react-native-modal component this problem didn't occur and when I pressed on the textinput, the modal stayed the same and didn't move (well, react-native's Modal component has its own problems which is why I tried to use this component instead, but at least it proved me that the problem is not in some of my other code around my modal component).

The device I worked on is Android Samsung J7, and I use the react-native-modal version 7.0.2
Thanks for the help! :)

**Comment by mmazzarolo** [comment]
Hi!
Did you already tried changing the Android [`softInputMode`](https://developer.android.com/guide/topics/manifest/activity-element#wsoft) in the manifest?

**Comment by Pazamozaurus** [comment]
> Hi!
> Did you already tried changing the Android [`softInputMode`](https://developer.android.com/guide/topics/manifest/activity-element#wsoft) in the manifest?
> [This might help you as well](https://github.com/react-native-community/react-native-modal/issues/91).

Thanks! Currently my app is still in early stages so I'm working with Expo, from which it seems there is no easy way to change the manifest file because to my understanding Expo manages these files internally.
Is there any other way/hack to do it through the code?

**Comment by mmazzarolo** [comment]
@Pazamozaurus not sure on that honestly 🤔Do you know if you're having the issue on standard RN as well?

**Comment by sal-g** [comment]
Did you figure it out?

**Comment by galzate-blumer** [comment]
I have the same issue, @mmazzarolo did you solve it?

**Comment by jxzy999** [comment]
I have the same issue, how to deal with it ? please help

**Comment by vitolipari** [comment]
I have the same issue

**Comment by fikretsengul** [comment]
I have the same issue.
