### ISSUE TITLE
Is it possible to close the modal automatically or by a timer?

### ISSUE THREAD

**Issue by AdamLee321** [react-native-community/react-native-modal#255]
I have been trying to close the modal automatically, but it doesn't seem to be working. 

I have tried: 

onModalShowing() {
    this.setTimeout(() => {
      this.setState({
        modalVisible: false,
      })
    }, 200)
  }

However this doesn't work, any ideas?

**Comment by mmazzarolo** [comment]
Yep, it's totally doable and you're on the right path. Try playing a bit with it by changing the delay and make sure the setState is invoked correctly.  
Closing since this is not a real issue (and doesn't follow the issue template.
