### ISSUE TITLE
Ability to have custom backdrop?

### ISSUE THREAD

**Issue by SvetlinStaev** [react-native-community/react-native-modal#263]
Hi,

I was wondering whether there are any plans on exposing the backdrop view as a prop to the modal to we can have custom ones. The main idea here would be for blurred backdrops which are quite popular on the iOS platform. At the moment, I can only modify the backdrop styles but blurred backdrop would require changing the underlying `View` to a `BlurView` from `react-native-blur`.

**Comment by mmazzarolo** [comment]
@SvetlinStaev no real plans right now but that's a nice 
I "think" it shouldn't be too complex to implement (unless you want to blur the background progressively). 

I'll keep the issue open.  

P.S.: If you're interested we're actively looking for helpers/maintainers #261
