### ISSUE TITLE
Screen is fully covered using react native QRCode on Galaxy

### ISSUE THREAD

**Issue by chohonest** [react-native-community/react-native-modal#273]
I am using react-native-modal 9.0.0 and react-native-qrcode 0.2.7, when I generate a QR code in the modal on galaxy devices the modal occupy the entire screen. 
this is what is expected: 

![20190325_114907](https://user-images.githubusercontent.com/28066428/54938804-1f43c580-4ef5-11e9-940a-e5829de5c94a.jpg)

this is what I get with Galaxy devices:

![Screenshot_20190325-114440_Expo](https://user-images.githubusercontent.com/28066428/54938943-65008e00-4ef5-11e9-9609-35a10ee7d1f9.jpg)

without passing in the QRcode generator I get the expected outcome:

![Screenshot_20190325-114558_Expo](https://user-images.githubusercontent.com/28066428/54938966-6e89f600-4ef5-11e9-8b36-6df7dfa31782.jpg)

```return (
      <Modal
        isVisible={this.state.isModalVisible}
        onBackButtonPress={() => this._toggleModal()}
        onBackdropPress={() => this.setState({ isModalVisible: false })}
        onSwipeComplete={() => this.setState({ isModalVisible: false })}
        swipeDirection="down"
        style={{
          alignItems: 'center',
          flex: 1,
          backgroundColor: 'white',
          borderRadius: 10,
          marginTop: 60,
          marginBottom: 60,
        }}
      >
        <View style={{ position: 'absolute', flexDirection: 'row', width: width - (width * 0.2), borderBottomWidth: 0.5, alignSelf: 'center', justifyContent: 'center', top: 20 }}>
          <Text style={{ padding: 20, fontSize: 18 }}>{this.state.title}</Text>
          <View style={{ right: 0, position: 'absolute' }}>
            <Icon
              type='materialicon'
              name='cancel'
              size={30}
              onPress={() => this._toggleModal()}
            />
          </View>
        </View>
        <View>
          <QRCode
            value={
              JSON.stringify(this.state.item)
            }
            size={width - (width * 0.5)}
            bgColor='black'
            fgColor='white'
          />
        </View>

      </Modal>
    );

**Comment by mmazzarolo** [comment]
Hi @chohonest , since the Modal works correctly without your custom component I would ask for help on StackOverflow about you question (or, if you think this really is a react-native-modal issue, please fill an issue following the template and add a reproducible repo).  
Thank you!
