### ISSUE TITLE
react native modal is showing  2 times.

### ISSUE THREAD

**Issue by sunihegde** [react-native-community/react-native-modal#275]
I have modal in side FlatList. and its showing two times.
pls check below code.

import { Modal} from "react-native";

  setModalVisible(visible) {
    this.setState({ modalVisible: visible });
  }

<FlatList
  data={this.state.buses}
  renderItem={({ item }) => (
    <View style={{ margin: 15 }}>
      <Modal
        animationType="slide"
        transparent={false}
        visible={this.state.modalVisible}
        onRequestClose={() => {
          alert("Modal has been closed.");
        }}
      >
        <View style={{ marginTop: 10 }}>
          <TouchableOpacity
            onPress={() => {
              this.setModalVisible(!this.state.modalVisible);
            }}
          >
            <Icon name="close" style={{ fontSize: 24 }} />
          </TouchableOpacity>
          <Separator bordered>
            <Text>Cancellation time</Text>
          </Separator>

          <View>
            <View>
              <ListItem>
                <Text>
                  {" "}
                  Between 0 days 1 hours and 0 hours before journey time 96.0%
                </Text>
              </ListItem>
            </View>
          </View>
        </View>
      </Modal>
      <TouchableOpacity
        onPress={() => {
          this.setModalVisible(true);
        }}
      >
        <View>
          <Text style={[styles.reviewText, styles.secondary1]}>
            CancellationPolicy:
            {item.CancellationPolicy}
          </Text>
        </View>
      </TouchableOpacity>
    </View>
  )}
/>;

**Comment by rewieer** [comment]
That is because you use a single boolean flag but you mount one modal for every item of your FlatList.
Either use one boolean flag per item of your flatlist or use a single modal and adapt its content to the currently selected item (preferred solution).

This is unrelated to `react-native-modal`, please use StackOverflow for proper help about such cases.
