### ISSUE TITLE
The header of bottom modal disappear

### ISSUE THREAD

**Issue by huylv-teko** [react-native-community/react-native-modal#277]
When i create a modal like here, it works fine but when the content increase, the UI seems not correct (the header disappeared). I dont want to set the fix height to the modal because i want it's height always wrap the content.

```
<Modal
        isVisible={this.state.visible}
        style={styles.bottomModal}
        onSwipeComplete={this.onClose}
        onBackdropPress={this.onClose}
        swipeDirection="down"
        avoidKeyboard
      >
      <View style={{backgroundColor: 'white'}}>
        <ModalHeader />
        {this.renderModalContent(numOfItems)}
        </View>
      </Modal>
```
Here is the complete example
https://snack.expo.io/@huylv177/react-native-modal-slidingfrombottom

**Comment by mmazzarolo** [comment]
Hi @huylv-teko , this seems to be more of a styling question. 
Have you tried playing with the `minHeight`/`flexShrink` props of both the `ModalHeader` or with the `maxWidth` of the content?

**Comment by huylv-teko** [comment]
To be honest i found an answer for my question, just add  maxHeight to the view inside Modal.
But then there is a new problem, if there is a ScrollView inside my modal, i can not swipe it easily with 
```
swipeDirection="down"
propagateSwipe={true}
```
The example: https://snack.expo.io/@huylv177/react-native-modal-slidingfrombottom

**Comment by mmazzarolo** [comment]
glad you fixed the first issue :)
@huylv-teko please continue the discussion on #236
