### ISSUE TITLE
Put modal and its content under (zIndex) Header?

### ISSUE THREAD

**Issue by kylanhurt** [react-native-community/react-native-modal#28]
Hi, I am working on a project and am finding it very difficult to get the modal to be put *underneath* (in a zIndex / elevation manner) the Header that I have. The header is in Native Base so I don't know if this is an issue with Native Base or react-native-modal.

![image](https://cloud.githubusercontent.com/assets/6249205/26272491/6f58251a-3cce-11e7-8010-66faa237a72d.png)

That is what it currently looks like and it seems that no matter how I adjust the zIndex or elevation of the components, I cannot get anything to really go on-top of the modal... any help would be appreciated.

**Comment by mmazzarolo** [comment]
Hello @kylanhurt !
Could you try swapping the `react-native-modal` with [react-native's modal](https://facebook.github.io/react-native/docs/modal.html) and see if the problem persists?

**Comment by kylanhurt** [comment]
@mmazzarolo The problem persists. The only way I can figure out to do it is to us the native modal, give it transparency and then put a marginTop equal to the height of the header. It seems very hacky, IMO and even more hacky when you consider that I cannot get the modal to "slide" in from the top especially when you consider that it will have to slide *on-top / over* the header.

Very disappointing.

**Comment by mmazzarolo** [comment]
@kylanhurt that's sad :(
Maybe you should try open an issue in the react-native official repo? You can link this issue if needed.  

Is adding a customizable top margin prop to react-native-modal really that bad in your opinion? 🤔
