### ISSUE TITLE
display location of modal

### ISSUE THREAD

**Issue by ductuan10081992** [react-native-community/react-native-modal#280]
Hi everybody. I want to display modal at the bottom of the screen. Is there any way to accomplish this? Please show me. Thanks very much

**Comment by mmazzarolo** [comment]
Hi @ductuan10081992 ! Please check [this modal](https://github.com/react-native-community/react-native-modal/blob/290ba79d5e0cdd07bcc8e83b76d7c1d39dac6f83/example/Example.js#L104) from the example 👍
