### ISSUE TITLE
How to set timeout for modal ? 

### ISSUE THREAD

**Issue by jake41** [react-native-community/react-native-modal#281]
Hi,

Is there a way to make the modal disappear after a certain timeout value ? If it is there, which method should I invoke for that ? 

Lets say after 5s I want my modal to automatically disappear from the screen. 

Thanks

**Comment by mmazzarolo** [comment]
Hi, `react-native-modal` is a controlled component, which means you're in charge of showing/hiding the modal whenever you want. 
If you want to hide the modal automatically after a certain amount of time you can switch from `true` to `false` to its `isVisible` props using a `setTimeout` for example.

**Comment by jake41** [comment]
Okay. Thanks for the clarification @mmazzarolo
