### ISSUE TITLE
Alert over react-native over react-native-modal design issue in Android devices

### ISSUE THREAD

**Issue by akhilsanker** [react-native-community/react-native-modal#284]
Hi,
I am using react native awesome alert to display over react native modal. But in iOS, it is displaying correctly but in Android, it is not displaying as required.
I have attached screenshots of both ios and android.

In iOS
![Simulator Screen Shot - iPhone XS Max - 2019-04-06 at 11 47 08](https://user-images.githubusercontent.com/32122016/55665934-daa91a00-5864-11e9-993b-4f4867971860.png)

In Android
![Screenshot_2019-04-06-11-48-33-85_26cbd1f9a7b69f50215755ae755376c6 (1)](https://user-images.githubusercontent.com/32122016/55665939-f7455200-5864-11e9-9bb5-280f19584a4a.png)

My environment is as follows:
"react": "16.6.3",
"react-native": "0.57.8",
"react-native-awesome-alerts": "^1.2.0",
"react-native-modal": "^7.0.2",

My code is as follows:

      <Modal isVisible={this.state.opt_modal} style={{backgroundColor: 'white', overflow: 'hidden', marginVertical: 50 }} >
        <View style={{position: 'absolute' , top: 10, right: 20}}>
           <Button style={{backgroundColor: 'white', elevation: 0}} onPress={() => this.close_modal()}>
         <Image style={{width: 25, height: 25, opacity: 0.3}} source={require('../../assets/cancel-music.png')} />
         </Button>
       </View>
       <View style={{flexDirection: 'row', justifyContent: 'center',alignItems: 'center'}}>
       <Text style={{ marginVertical: 10, fontSize: 19, flexWrap: 'wrap', flex: 1, marginHorizontal: 25}}>Bitte gib den an deine E-Mail-Adresse gesendeten Code ein.</Text>
      </View>
      <View style={{flexDirection: 'row', }}>
         <OtpInputs handleChange={(opt)=> this.setState({opt})}  numberOfInputs={4} />
       </View>
       <View style={{flexDirection: 'row' }}>
       <Button bordered style={{flex: 1, justifyContent: 'center', borderRadius: 20, marginVertical: 20,marginHorizontal: 25, borderColor: '#FA872D', backgroundColor: 'white', borderWidth: 5, elevation: 2}}
	onPress={() => this.authenticate()}>
	    <Text style={{color: '#FA872D', fontWeight: 'bold' }}>Verifizieren</Text>
     </Button>
        </View>
        <View style={{flexDirection: 'row' }}>
          <Button bordered style={{flex: 1, justifyContent: 'center', borderRadius: 20, marginVertical: 20,marginHorizontal: 25, borderColor: '#FA872D', backgroundColor: 'white', borderWidth: 5, elevation: 2}}
	onPress={() => this.resend_otp()}>
	       <Text style={{color: '#FA872D', fontWeight: 'bold' }}>Code noch einmal senden</Text>
      </Button>
      </View>
     <AwesomeAlert
         show={showAlert_invalid_otp}
         showProgress={false}
         message="Ungültiger Code!"
         closeOnTouchOutside={false}
         closeOnHardwareBackPress={false}
         showConfirmButton={true}
         confirmText="OK"
         confirmButtonColor="#FA872D"
         onConfirmPressed={() => {
        this.hideAlert_invalid_otp();
        }}
    />
    </Modal>

Is there any workaround to solve this problem?

Thanks

**Comment by mmazzarolo** [comment]
Hey @akhilsanker , I have no idea of how `react-native-awesome-alerts` works, but if it uses react-native's `Modal` [it won't work correctly with this library :/](https://github.com/react-native-community/react-native-modal#i-cant-show-multiple-modals-at-the-same-time).

**Comment by akhilsanker** [comment]
Hi @mmazzarolo,

Thanks for the reply. But it is showing correctly in iOS devices and have the issue in all Android devices.
Do you have any suggestion for this type of behavior?

Thanks

**Comment by mmazzarolo** [comment]
@akhilsanker if it's using the Modal I don't have any workaround unfortunately. You might wanna try the JS version of the modal which uses portal #145

**Comment by erhanbicer** [comment]
because of the **elevation** feature in android gives error in this way
