### ISSUE TITLE
swipeable area

### ISSUE THREAD

**Issue by Aleksandern** [react-native-community/react-native-modal#286]
Hello.

Is it possible to specify the height of the swipeable area to close modals?

<img width="161" alt="Screenshot 2019-04-12 at 14 50 45" src="https://user-images.githubusercontent.com/5274465/56021096-ccf70700-5d32-11e9-8885-1ef807ef51cf.png">

**Comment by rewieer** [comment]
At the moment is it not, but PRs are welcome to support this feature :)

**Comment by rabanos-rvc** [comment]
up
