### ISSUE TITLE
Question about bottom modal example

### ISSUE THREAD

**Issue by AlexMachin1997** [react-native-community/react-native-modal#288]
Hi,

I've come across your library and it looks excellent.

I would like to use this in my application, but I'm a little confused about the examples shown, specifically the bottom modal.

How would I position the modal at the bottom? is there a prop for this or would I have to position absolute it to the bottom of the screen

**Comment by mmazzarolo** [comment]
Hi!
Please check the [boom Modal example](https://github.com/react-native-community/react-native-modal/blob/290ba79d5e0cdd07bcc8e83b76d7c1d39dac6f83/example/Example.js#L63) in the example app 👍

**Comment by AlexMachin1997** [comment]
Oh ok.

It just wasn't very clear at first. In the docs it shows visible is a bool, only after looking into the examples, it seems you set the visible equal to a number which then returns a modal component based on the number.

This could be mentioned in the docs 👍

**Comment by mmazzarolo** [comment]
It’s not a number! The number is us d only for applying different styles in the example

**Comment by AlexMachin1997** [comment]
Ok. Configured the modal, but for some reason, the backdrop isn't appearing.

```
        <Modal
          visible={this.state.isModalVisible}
          style={styles.bottomModal}
          onBackdropPress={() => this.setState({ isModalVisible: false })}
          backdropColor="black"
          hasBackdrop={true}
          deviceWidth={deviceWidth}
          deviceHeight={deviceHeight}
        >
          <View style={styles.modalContent}>
            <Text>Hello!</Text>
            <TouchableOpacity
              onPress={() => this.setState({ isModalVisible: false })}
            >
              <View style={styles.button}>
                <Text>Close</Text>
              </View>
            </TouchableOpacity>
          </View>
        </Modal>
```

**Comment by wangdanting** [comment]
This can be achieved。
`<Modal isVisible={true} swipeDirection='down' style={{ justifyContent: 'flex-end' }}>
          <View style={{ backgroundColor: '#fff' }}>
            <Text>bottom half</Text>
          </View>
        </Modal>`

**Comment by wangdanting** [comment]
> Hi,
> 
> I've come across your library and it looks excellent.
> 
> I would like to use this in my application, but I'm a little confused about the examples shown, specifically the bottom modal.
> 
> How would I position the modal at the bottom? is there a prop for this or would I have to position absolute it to the bottom of the screen

The following code can be implemented。

```javascript
<Modal isVisible={true} swipeDirection='down' style={{ justifyContent: 'flex-end' }}>
  <View style={{ backgroundColor: '#fff' }}>
      <Text>bottom half</Text>
   </View>
</Modal>
```

**Comment by Rainymood** [comment]
Leaving a comment for the next one... documentation is still vague on how to implement a `BottomHalfModal` :)

**Comment by Chiagozielam** [comment]
Yeah. Nice work. But currently, the documentation is somewhat not clear about the implementation of the bottom half modal

**Comment by vinhnglx** [comment]
A small enhancement from @wangdanting 's code, the modal will full width

```javascript
      <Modal
        isVisible={isModalVisible}
        swipeDirection="down"
        style={{ justifyContent: 'flex-end', margin: 0 }}>
        <View style={{ backgroundColor: '#fff', height: Dimensions.get('screen').height / 1.5 }}>
          <Text>bottom half</Text>
          <Button title="Hide modal" onPress={toggleModal} />
        </View>
      </Modal>
```
![Simulator Screen Shot - iPhone 12 - 2021-04-17 at 16 26 41](https://user-images.githubusercontent.com/1997137/115106860-c5117380-9f99-11eb-87ec-9436d1dda06b.png)
