### ISSUE TITLE
Toast not showing over modal in iOS

### ISSUE THREAD

**Issue by Rinkuk1993** [react-native-community/react-native-modal#289]
Issue found on plugin version - 9.0.0

Issue is - https://github.com/magicismight/react-native-root-toast/issues/83

Looks like it is happening as this plugin uses the Native modal. 
Is there a possibility of adding js modal for fixing the issue?

**Comment by mmazzarolo** [comment]
Hey @Rinkuk1993 there's a WIP about a JS rewrite of the modal in [this pinned issue](https://github.com/react-native-community/react-native-modal/issues/145).  
We're open to feedback, suggestions and proposal (unfortunately I haven't had enough time lately to work on it).

**Comment by bohehe** [comment]
just use overScreen: false to resolve it

**Comment by edanedison** [comment]
Where is ‘overScreen’ listed anywhere as an attribute?

**Comment by IsaacGluck** [comment]
*coverScreen
but it worked, thanks @bohehe

**Comment by EmpireJones** [comment]
The coverScreen change didn't work for me, but I got it working with react-native-simple-toast by configuring the viewControllerBlacklist as described in their readme:


> Note on viewControllerBlacklist: this is an iOS-only option, it is ignored on android. When presenting the Toast, we need to find the presented ViewController (VC). The Toast will be presented in that VC. For Example, let's say you're showing a ReactNative.Modal in your app - in that case, the presented VC is a RCTModalHostViewController.
> 
> If you present a Toast while that Modal is shown, and then hide the Modal, the Toast will disappear together with the Modal.
> 
> viewControllerBlacklist allows to say what VCs should not be considered when Toast is shown. This is to allow to work around issues where Toast would be displayed weirdly in an Alert or would hide too quickly when shown in a RCTModalHostViewController.
