### ISSUE TITLE
Scrollview in modal jumps back to offset:0 on second touch

### ISSUE THREAD

**Issue by jasongaare** [react-native-community/react-native-modal#290]
#### Note
I am aware of the existence of #236 -- I am opening this issue as a particular piece of that larger issue, and also as an issue to reference directly while developing a specific fix. If it makes more sense to close this issue in favor of #236 I understand

#### Setup
- react-native-modal: 9.0.0
- react-native: 0.55.3 (I know a little behind...)

#### Issue
The method for patching through the gestures from the panResponder to a ScrollView ref is well-executed and works in most cases that I've encountered. However, I noticed that when the list is scrolled, then the user releases their touch, then scrolls again - the list always jumps back to `offset: 0`

The issue can be found here:
https://github.com/react-native-community/react-native-modal/blob/5aed0556c2df117048b290acf42b445ed87cded4/src/index.js#L242-L248

L243 uses the gestureState distance to set the offset of the ScrollView, so with each new touch, that gestureState is a new one with a new `dy` - which always begins at zero. 

Further, whenever the user swipes in the direction of the `swipeDirection` prop from the `react-native-modal`, even if the ScrollView is not at the top, it begins to dismiss the modal (i.e. once I have scrolled down the list, I can not scroll back to the top of it)

It can be little tricky to see what is happening here without seeing my finger, but this is a video with an example: https://i.imgur.com/zvEPlsw.mp4. Note that "Share Photo" is the first item in the ScrollView, and it repeatedly jumps back to that item when I start a new touch on the modal. (You can also see I cannot scroll back to the top of the list).

#### What is expected
When there is a `scrollTo` prop and `ScrollView` child inside the Modal, it needs to maintain the scrollOffset anytime the user ends their pan (i.e. in `onPanResponderRelease`). Then this "last resting offset" should be used to determine the offset for the `scrollTo` function. 

That way the user can scroll their list and move it as they would expect, but once the list hits the top the panResponder "flips" to dismissing the modal.

**Comment by agusvazquez** [comment]
Hello!

I am having the same issue with the latest version (11.3.0) but only on iOS. On android it works ok.

**Comment by atifaziz1** [comment]
Hi!!

I am still facing the issue on android, ios is working fine.
