### ISSUE TITLE
IOS - cannot show the modal again after put the state into false

### ISSUE THREAD

**Issue by helloeyesimple** [react-native-community/react-native-modal#295]
Hi,

First of all,
Sorry for opening a new issue regarding my old one because I cannot seems to open it again. Feel free to delete which one you think the best.

My old Issue [#294](https://github.com/react-native-community/react-native-modal/issues/294)

I'm encountering an issue when using IOS (Physical Device) with platform IOS 12.0,
When I put the state into _false_, and try to showing again using state _true_, it cannot seems showing at all. I'm totally using the example from example folder [here](https://github.com/react-native-community/react-native-modal/blob/master/example/Example.js)
Please see my detailed issue description below.

### When reporting a bug, please be sure to check if the issue still persists with react-native original modal:
Under the hood `react-native-modal` uses react-native original [Modal component](https://facebook.github.io/react-native/docs/modal.html).  
Before reporting a bug, try swapping `react-native-modal` with react-native original Modal component to check if the problem persists.  
> There is nothing wrong with original react-native Modal component.

### When reporting a bug, please be sure to include the following:
- [x] The outcome of the `react-native-modal` swap described above
> Cannot showing the modal again after putting the state into "false", and try getting it back using state "true". Totally using the code from example and nothing else.

- [x] What version of `react-native-modal` you're using, and the platform(s) you're running it on (iOS, Android, device)

> {
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-modal": "^10.0.0"
  },
  "devDependencies": {
    "babel-jest": "24.7.1",
    "babel-preset-react-native": "4.0.1",
    "jest": "24.7.1",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

> No Podfile
> Platform: IOS 12

- [x] The behavior you expect to see, and the actual behavior
> When pressing the button, the modal does not showing.

```
import React, { Component } from "react";
import {
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import Modal from "react-native-modal";

export default class Example extends Component {
  state = {
    visibleModal: null,
  };

  renderButton = (text, onPress) => (
    <TouchableOpacity onPress={onPress}>
      <View style={styles.button}>
        <Text>{text}</Text>
      </View>
    </TouchableOpacity>
  );

  renderModalContent = () => (
    <View style={styles.modalContent}>
      <Text>Hello!</Text>
      {this.renderButton("Close", () => this.setState({ visibleModal: null }))}
    </View>
  );

  handleOnScroll = event => {
    this.setState({
      scrollOffset: event.nativeEvent.contentOffset.y,
    });
  };

  handleScrollTo = p => {
    if (this.scrollViewRef) {
      this.scrollViewRef.scrollTo(p);
    }
  };

  render() {
    return (
      <View style={styles.container}>
        {this.renderButton("Default modal", () =>
          this.setState({ visibleModal: 1 }),
        )}
        {this.renderButton("Sliding from the sides", () =>
          this.setState({ visibleModal: 2 }),
        )}
        {this.renderButton("A slower modal", () =>
          this.setState({ visibleModal: 3 }),
        )}
        {this.renderButton("Fancy modal!", () =>
          this.setState({ visibleModal: 4 }),
        )}
        {this.renderButton("Bottom half modal", () =>
          this.setState({ visibleModal: 5 }),
        )}
        {this.renderButton("Modal that can be closed on backdrop press", () =>
          this.setState({ visibleModal: 6 }),
        )}
        {this.renderButton("Swipeable modal", () =>
          this.setState({ visibleModal: 7 }),
        )}
        {this.renderButton("Scrollable modal", () =>
          this.setState({ visibleModal: 8 }),
        )}
        <Modal isVisible={this.state.visibleModal === 1}>
          {this.renderModalContent()}
        </Modal>
        <Modal
          isVisible={this.state.visibleModal === 2}
          animationIn="slideInLeft"
          animationOut="slideOutRight">
          {this.renderModalContent()}
        </Modal>
        <Modal
          isVisible={this.state.visibleModal === 3}
          animationInTiming={2000}
          animationOutTiming={2000}
          backdropTransitionInTiming={2000}
          backdropTransitionOutTiming={2000}>
          {this.renderModalContent()}
        </Modal>
        <Modal
          isVisible={this.state.visibleModal === 4}
          backdropColor={"red"}
          backdropOpacity={1}
          animationIn="zoomInDown"
          animationOut="zoomOutUp"
          animationInTiming={1000}
          animationOutTiming={1000}
          backdropTransitionInTiming={1000}
          backdropTransitionOutTiming={1000}>
          {this.renderModalContent()}
        </Modal>
        <Modal
          isVisible={this.state.visibleModal === 5}
          onSwipeComplete={() => this.setState({ visibleModal: null })}
          swipeDirection={["up", "left", "right", "down"]}
          style={styles.bottomModal}>
          {this.renderModalContent()}
        </Modal>
        <Modal
          isVisible={this.state.visibleModal === 6}
          onBackdropPress={() => this.setState({ visibleModal: null })}>
          {this.renderModalContent()}
        </Modal>
        <Modal
          isVisible={this.state.visibleModal === 7}
          onSwipeComplete={() => this.setState({ visibleModal: null })}
          swipeDirection={["down"]}>
          {this.renderModalContent()}
        </Modal>
        <Modal
          isVisible={this.state.visibleModal === 8}
          onSwipeComplete={() => this.setState({ visibleModal: null })}
          swipeDirection="down"
          scrollTo={this.handleScrollTo}
          scrollOffset={this.state.scrollOffset}
          scrollOffsetMax={400 - 300} // content height - ScrollView height
          style={styles.bottomModal}>
          <View style={styles.scrollableModal}>
            <ScrollView
              ref={ref => (this.scrollViewRef = ref)}
              onScroll={this.handleOnScroll}
              scrollEventThrottle={16}>
              <View style={styles.scrollableModalContent1}>
                <Text>Scroll me up</Text>
              </View>
              <View style={styles.scrollableModalContent2}>
                <Text>Scroll me up</Text>
              </View>
            </ScrollView>
          </View>
        </Modal>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  button: {
    backgroundColor: "lightblue",
    padding: 12,
    margin: 16,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 4,
    borderColor: "rgba(0, 0, 0, 0.1)",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 22,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 4,
    borderColor: "rgba(0, 0, 0, 0.1)",
  },
  bottomModal: {
    justifyContent: "flex-end",
    margin: 0,
  },
  scrollableModal: {
    height: 300,
  },
  scrollableModalContent1: {
    height: 200,
    backgroundColor: "orange",
    alignItems: "center",
    justifyContent: "center",
  },
  scrollableModalContent2: {
    height: 200,
    backgroundColor: "lightgreen",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

- [x] **Most important of all:** An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
> Totally using the example code
Also available on my repo https://github.com/helloeyesimple/react-native-modal-test

**Comment by rewieer** [comment]
Sadly I don't have an iOS device yet (I'm receiving an iOS 10 Iphone 7 soon but i'm not sure the bug will appear if it's iOS 12 specific). In all cases I clearly have no idea how this can be directly related to react-native-modal.

**Comment by helloeyesimple** [comment]
@rewieer 
I'm testing using old IOS devices - Iphone 5s. It is upgradeable to IOS 12.
If what you were referring this does not concern react-native-modal, might you have any pointer that would be the cause?

**Comment by rewieer** [comment]
Can you try if it works on `9.0.0` ?

**Comment by helloeyesimple** [comment]
v9.0.0 does not works either.
I'm using Xcode Version 10.1 (10B61) btw

**Comment by rewieer** [comment]
So it's not a regression. The problem being it works perfectly fine at home.
Did you try to investigate by updating the code a little bit, seeing if the event is even propagated ? Might be related to some touch event failing or something

**Comment by helloeyesimple** [comment]
Did you try to use my repo to see if it's working properly?
I've tried putting log onPress event, and it is capturing properly

```
onPress(){
    console.log("on press");

    var el = this;
    this.setState({ 
      visibleModal: 1 
    }, function(){
      console.log(el.state.visibleModal);
    });
  }

  renderButton = (text, onPress) => (
    <TouchableOpacity onPress={onPress}>
      <View style={styles.button}>
        <Text>{text}</Text>
      </View>
    </TouchableOpacity>
  );

  renderModalContent = () => (
    <View style={styles.modalContent}>
      <Text>Hello!</Text>
      {this.renderButton("Close", () => this.setState({ visibleModal: null }))}
    </View>
  );

  render() {
    return (
      <View style={styles.container}>
        {this.renderButton("Default modal", () =>
          this.onPress()
        )}
        <Modal isVisible={this.state.visibleModal === 1}>
          {this.renderModalContent()}
        </Modal>
      </View>
    );
  }
```

And here's the output
![image](https://user-images.githubusercontent.com/24649774/57006944-18545500-6c0f-11e9-9d59-628685208613.png)

**Comment by helloeyesimple** [comment]
Try to tinkering with the code a bit on src/index.js
And found out this.contentRef is returning undefined. I wonder why though.

```
open = () => {

    this.isTransitioning = true;
    if (this.backdropRef) {
      this.backdropRef.transitionTo(
        { opacity: this.props.backdropOpacity },
        this.props.backdropTransitionInTiming
      );
    }

    // This is for resetting the pan position,otherwise the modal gets stuck
    // at the last released position when you try to open it.
    // TODO: Could certainly be improved - no idea for the moment.

    if (this.state.isSwipeable) {
      this.state.pan.setValue({ x: 0, y: 0 });
    }

    console.log("this.contentRef");
    console.log(this.contentRef);
    
    if (this.contentRef) {

      this.props.onModalWillShow && this.props.onModalWillShow();
      this.contentRef[this.animationIn](this.props.animationInTiming).then(
        () => {
          this.isTransitioning = false;
          if (!this.props.isVisible) {
            this.close();
          } else {
            this.props.onModalShow();
          }
        }
      );
    }
  };
```

If I tried using componentWillProps function, it is working properly!
But it's been marked as UNSAFE. I wonder why?

```
componentWillReceiveProps(nextProps) {
    if (!this.state.isVisible && nextProps.isVisible) {
      this.setState({ isVisible: true, showContent: true });
    }
    if (
      this.props.animationIn !== nextProps.animationIn ||
      this.props.animationOut !== nextProps.animationOut
    ) {
      const { animationIn, animationOut } = buildAnimations(nextProps);
      this.animationIn = animationIn;
      this.animationOut = animationOut;
    }
    if (
      this.props.backdropOpacity !== nextProps.backdropOpacity &&
      this.backdropRef
    ) {
      this.backdropRef.transitionTo(
        { opacity: nextProps.backdropOpacity },
        this.props.backdropTransitionInTiming
      );
    }
  }
```

**Comment by mmazzarolo** [comment]
@helloeyesimple FYI I just tested the `example` (the one available in this repo) and it is working fine for me. 
Could you try it?

**Comment by mmazzarolo** [comment]
I would also suggest you to try [this other simple example](https://github.com/react-native-community/react-native-modal#a-complete-example) if you haven't already.

**Comment by helloeyesimple** [comment]
@mmazzarolo 
Both examples (the one available in this repo and the other simple example) does not work for me.
Only by using componentWillReceiveProps it's working flawlessly.

**Comment by mmazzarolo** [comment]
@helloeyesimple I see you're still on an old version of React and React-Native, mind updating and checking again?

**Comment by helloeyesimple** [comment]
@mmazzarolo 
Will try updating the React & RN version later. As I can't seem to find the correct dependencies for v0.58.4.

Let's say it's working, but can't really say it's the correct solution for the older version of RN.
And why is componentWillReceiveProps is marked as UNSAFE?

**Comment by mmazzarolo** [comment]
It's because `componentWillReceiveProps` [is deprecated](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change).  
We're open to PR to update it!

**Comment by vlatri** [comment]
Hey, any news / possible hot fixes?

**Comment by MorgadoKnivet** [comment]
This problem happens to me when hasBackdrop={false}. 
`    <View  style = {styles.preContainer} pointerEvents={"box-none"}  >
            
            <Modal
              animationIn='slideInUp'
              animationOut='slideOutDown'
              animationInTiming={700}
              animationOutTiming={700}
             // backdropTransitionInTiming={500}
              isVisible ={this.state.isVisible}
         //     backdropColor='#fff'
             //backdropOpacity={1}
              style={styles.modal}
              coverScreen={false}
              hasBackdrop={false}
              onBackdropPress = {this.props.onBackdropPress}
              onSwipeStart ={ this.onSwipeStart}
              onModalWillHide = {this.props.onModalWillHide}
            //  onModalHide = {() => console.log("onModaHide")}
           //   onSwipeCancel = {() => console.log("SwipeCancel")}
              swipeDirection={['down']}
          //   scrollOffset = {}
              //scrollOffsetMax = {196}
              scrollTo={this.handleScrollTo}
              onSwipeComplete={() =>console.log("onSwipeComplete")}
            //  onSwipeMove ={(percentageShown)=> this.calcEffectPorcent(percentageShown)}
            
             // deviceHeight={screenHeight}
            > 
        
          { <FlatList 
                keyboardShouldPersistTaps={'handled'}
                style = {styles.FlatList} 
                data={this.state.places} 
                renderItem={this.renderItem} 
                keyExtractor={this._keyExtractor}
          /> }

            </Modal>  

          </View>`

react-native-cli: 2.0.1
react-native: 0.59.4

**Comment by NghiaHanoi** [comment]
Try to force re-render  by using :

> this.forceUpdate() 

-> this mean the Component keeping the Modal.

**Comment by Sivakumar415** [comment]
How this issue fixed please anyone tell
