### ISSUE TITLE
Multiple modals not working in react native

### ISSUE THREAD

**Issue by linigithub** [react-native-community/react-native-modal#30]
When tapping on first modal window i need to open a second modal to the user. i implemented the same but the second modal not opening. Sometime it opens and disappears. any suggestions would be helpful.

**Comment by linigithub** [comment]
Sorry , its fixed by using setTimeout method. this is a great library.

**Comment by temitope** [comment]
Another idea for  fixing this is to have multiple views share the same modal component but only display the desired view based on state you are keeping. Sometimes the settimeoit feels like it can be unstable

**Comment by sqlProvider** [comment]
is this working? I can't still show two modal in same time.

**Comment by mmazzarolo** [comment]
@sqlProvider it should work
also, this issue is related to react-native's original modal and is not specific to react-native-modal :(

**Comment by wkoutre** [comment]
@sqlProvider The only way I can have two modals at the same time is by nesting the second inside the first.

In my case, the second modal is a confirmation box based on something being done in the first modal.

**Comment by sqlProvider** [comment]
@wkoutre @mmazzarolo 
I close first modal when second modal is showed. After second modal done I set first modal's visible. Fixed but so hackable.

**Comment by cccRaim** [comment]
@wkoutre hey, when I use `Modal`, the second is not work when the first is show, so `overlays` is impossible.

**Comment by wkoutre** [comment]
@cccRaim, is this when you're nesting the second Modal inside the first? That's the only way I've found success for this.

**Comment by slorber** [comment]
I don't use this lib but according to my tests, stacking modals on top of each others work fine on Android only :(

**Comment by lukewlms** [comment]
I was able to fix this by **only** setting the second modal's `isVisible: true` **after** the first modal is fully hidden (onModalHide).  Trying to show the second one before the first one is fully dismissed results in a frozen UI state or no modal.

If nesting, make sure you don't show the inner nested modal until the outer modal is **fully** shown, if you show it before that again you'll get bad behavior.  *The parent must be fully shown before the child modal is set to visible.*  At least that's our experience.

**Comment by slorber** [comment]
thanks for reporting that @lukewlms  this will certainly be useful to someone. In my app I've choosen to go with a react-navigation StackNavigator and it seems fine so far?

**Comment by kalwaniyash** [comment]
@lukewlms Solution: i faced a similar issue and have build a wrapper on top of react-native-modal which handles this for you. If a modal is already open then it'll close the modal automatically for you and show the new modal. It won't lead to a frozen UI state even if the first modal is visible and the second one is trying to open.
Let me know if you still require it. I am planning to publish it on npm soon.

**Comment by jpmasud** [comment]
Hey @kalwaniyash would be great if you could share your solution for this!

**Comment by jenskuhrjorgensen** [comment]
@kalwaniyash I'm also having problems presenting a modal on top of another modal - it works pretty straight forward on Android, but not on iOS. I'm also very interested in seeing your solution! 😃

**Comment by AnkitPat** [comment]
Please share solution for this.

**Comment by Zilleabbas10** [comment]
Any one able to solve the above issue in IOS. Stuck in it. @jenskuhrjorgensen have you solve it ??

**Comment by mmazzarolo** [comment]
Hey guys, [that's a limit of react-native](https://github.com/react-native-community/react-native-modal#i-cant-show-multiple-modals-at-the-same-time)

**Comment by kalwaniyash** [comment]
@Zilleabbas10 @AnkitPat @jenskuhrjorgensen @jpmasud 
check out this library [@kalwani/react-native-modal](https://www.npmjs.com/package/@kalwani/react-native-modal)
This should make it work for you. Let me know if you are still facing any issues.

**Comment by brayanL** [comment]
I imagine that it must be difficult to satisfy the two platforms, but this is terrible in IOS.

**Comment by mmazzarolo** [comment]
Just to clarify: you should NOT use `setTimeout`. 
- If you want to show one modal after another you should show the second one in the `onModalHide` callback of the first one
- If you want to show two modals at the same time you won't be able to do it right now because one `Modal` component of react-native (that is "extended" by `react-native-modal`) can be shown on screen

**Comment by mikecappie** [comment]
I had this issue on iOS while it was working fine on Android. I just moved the second modal inside the first one and this has resolved the issue. Thanks for the thread.

**Comment by jake41** [comment]
Hi folks, 

When you have multiple modals, set the `isVisible` param true for the first modal and show it, then on the `onModalHide` param of this modal, you can set the `isVisible` param for the second modal. Feel free to bug me for more clarity! . 

 ```
       <Modal
          isVisible={this.state.firstModalVisible}
          onBackdropPress={() => this.setState({ firstModalVisible: false })}
          animationIn="fadeIn"
          animationOut="fadeOut"
          backdropOpacity={0}
          hideModalContentWhileAnimating={true}
          useNativeDriver={false}
          onModalHide={() => {
            //We first close the helper modal, now we check if there is
            //message being set, if yes then show the simple-popup modal
            if (this.state.message != "") this.setState({ secondModalvisible: true });
            console.log("Heper modal closed");
          }}
        >
```

**Comment by Luyao61** [comment]
> Hi folks,
> 
> When you have multiple modals, set the `isVisible` param true for the first modal and show it, then on the `onModalHide` param of this modal, you can set the `isVisible` param for the second modal. Feel free to bug me for more clarity! .
> 
> ```
>      //My first modal
>       <Modal
>          isVisible={this.state.firstModalVisible}
>          onBackdropPress={() => this.setState({ firstModalVisible: false })}
>          animationIn="fadeIn"
>          animationOut="fadeOut"
>          backdropOpacity={0}
>          hideModalContentWhileAnimating={true}
>          useNativeDriver={false}
>          onModalHide={() => {
>            //This function is invoked when the first modal is closed. Now here
>            //set the state for the second Modal.
>            this.setState({ secondModalvisible: true });
>            console.log("First modal closed");
>          }}
>        >....</Modal>
> 
>      //My second modal
>      <Modal
>          isVisible={this.state.secondModalvisible}
>          onBackdropPress={() => this.setState({ secondModalvisible: false })}
>          animationIn="fadeIn"
>          animationOut="fadeOut"
>          backdropOpacity={0}
>          hideModalContentWhileAnimating={true}
>          useNativeDriver={false}
>          onModalHide={() => {console.log("Second modal closed")}}
>       > .... </Modal>
> ```

Hi, 
I have a question. I hope you can answer it.
The context is: I have a button_1 opens Modal1. Inside Modal1, there is button_2 which opens Modal_2. Each button has `onClick` that toggles Modal's `isVisible` field.

My dom looks like
```
<View>
    // button_1
    <MyButtonComponent>
        <Button>
        </Button>
        // Modal_1
        <Modal>
             // button_2
            <MyButtonComponent>
                <Button>
                </Button>
                // Modal_2
                <Modal>               
                </Modal>
            </MyButtonComponent>
        </Modal>
    <MyButtonComponent>
</View>
```
Now if I click button_1 then click button_2, Modal_2 will open on top of Modal_1. What I want to achieve is that when I click button_2, Modal_1 will go away, and Modal_2 will open.
If I use `onModalHide` to set Modal_1 `isVisible=false`, then Modal_2 will never show up. I guess this is expected, because if the parent is gone, then the child will not be rendered.  
Only each button component knows the content in the Modal. What should I do in this case? 

Thanks,

**Comment by kalwaniyash** [comment]
@Luyao61 There are multiple approaches you can take here.
1. Move the second modal out of the first modal, but keep the second button inside the first modal. This way when you close the first modal, the second modal can work independently according to the state of your component
```
<MyButtonComponent>
 
<Button1>
 </Button1>
 
<Modal1>
    <Button2>
    </Button2>
 </Modal1>
 
<Modal2>
 
</Modal2>
</MyButtonComponent>
```
2. Overlay second modal on top of first modal and hide it ( make opacity of first modal to 0 etc) and open second modal inside first modal and close both modal on second modal close.

**Comment by thanhluantl2304** [comment]
> > Hi folks,
> > When you have multiple modals, set the `isVisible` param true for the first modal and show it, then on the `onModalHide` param of this modal, you can set the `isVisible` param for the second modal. Feel free to bug me for more clarity! .
> > ```
> >      //My first modal
> >       <Modal
> >          isVisible={this.state.firstModalVisible}
> >          onBackdropPress={() => this.setState({ firstModalVisible: false })}
> >          animationIn="fadeIn"
> >          animationOut="fadeOut"
> >          backdropOpacity={0}
> >          hideModalContentWhileAnimating={true}
> >          useNativeDriver={false}
> >          onModalHide={() => {
> >            //This function is invoked when the first modal is closed. Now here
> >            //set the state for the second Modal.
> >            this.setState({ secondModalvisible: true });
> >            console.log("First modal closed");
> >          }}
> >        >....</Modal>
> > 
> >      //My second modal
> >      <Modal
> >          isVisible={this.state.secondModalvisible}
> >          onBackdropPress={() => this.setState({ secondModalvisible: false })}
> >          animationIn="fadeIn"
> >          animationOut="fadeOut"
> >          backdropOpacity={0}
> >          hideModalContentWhileAnimating={true}
> >          useNativeDriver={false}
> >          onModalHide={() => {console.log("Second modal closed")}}
> >       > .... </Modal>
> > ```
> 
> Hi,
> I have a question. I hope you can answer it.
> The context is: I have a button_1 opens Modal1. Inside Modal1, there is button_2 which opens Modal_2. Each button has `onClick` that toggles Modal's `isVisible` field.
> 
> My dom looks like
> 
> ```
> <View>
>     // button_1
>     <MyButtonComponent>
>         <Button>
>         </Button>
>         // Modal_1
>         <Modal>
>              // button_2
>             <MyButtonComponent>
>                 <Button>
>                 </Button>
>                 // Modal_2
>                 <Modal>               
>                 </Modal>
>             </MyButtonComponent>
>         </Modal>
>     <MyButtonComponent>
> </View>
> ```
> 
> Now if I click button_1 then click button_2, Modal_2 will open on top of Modal_1. What I want to achieve is that when I click button_2, Modal_1 will go away, and Modal_2 will open.
> If I use `onModalHide` to set Modal_1 `isVisible=false`, then Modal_2 will never show up. I guess this is expected, because if the parent is gone, then the child will not be rendered.
> Only each button component knows the content in the Modal. What should I do in this case?
> 
> Thanks,

Thanks, that's very helpful!

**Comment by JohnTheo13** [comment]
Multiple modals issue is only reproducible in ios device,
for flows where onHIdeModal is not useful, you can make one modals state conditional for which modal to show:
{modal1 ? <Modal1 isVisible ... : <Modal2 isVisible ...

**Comment by mioppong** [comment]
> @sqlProvider The only way I can have two modals at the same time is by nesting the second inside the first.
> 
> In my case, the second modal is a confirmation box based on something being done in the first modal.

THIS SOLVED IT EVERYONE USE THIS GUYS ANSWER!!!! GENIUS IDEA

**Comment by sqlProvider** [comment]
> > @sqlProvider The only way I can have two modals at the same time is by nesting the second inside the first.
> > In my case, the second modal is a confirmation box based on something being done in the first modal.
> 
> THIS SOLVED IT EVERYONE USE THIS GUYS ANSWER!!!! GENIUS IDEA

Thanks bro :)

**Comment by yerycs** [comment]
Is there any way to open multiple modals without nesting?

**Comment by yash-kalwani** [comment]
Hey @yerycs ran into the same issue and decided to create a library that solves this problem. Check if this package helps you out https://www.npmjs.com/package/@kalwani/react-native-modal

**Comment by intergalacticspacehighway** [comment]
Created a PR for the fix

https://github.com/facebook/react-native/pull/31498

**Comment by b3coded** [comment]
Thanks @intergalacticspacehighway, tested on my project with `patch-package` and it worked 🎉 
here is the patch file that I used:

`react-native+0.64.1.patch`

```
diff --git a/node_modules/react-native/React/Views/RCTModalHostViewManager.m b/node_modules/react-native/React/Views/RCTModalHostViewManager.m
index 91d83aa..8c53efe 100644
--- a/node_modules/react-native/React/Views/RCTModalHostViewManager.m
+++ b/node_modules/react-native/React/Views/RCTModalHostViewManager.m
@@ -78,10 +78,22 @@ RCT_EXPORT_MODULE()
   if (_presentationBlock) {
     _presentationBlock([modalHostView reactViewController], viewController, animated, completionBlock);
   } else {
-    [[modalHostView reactViewController] presentViewController:viewController
-                                                      animated:animated
-                                                    completion:completionBlock];
-  }
+
+      UIViewController *lastPresentedViewController = modalHostView.reactViewController;
+      UIViewController *presentedViewController = nil;
+
+
+      while (lastPresentedViewController != nil) {
+          presentedViewController = lastPresentedViewController;
+          lastPresentedViewController = lastPresentedViewController.presentedViewController;
+      }
+
+
+      [presentedViewController presentViewController:viewController
+                                                           animated:animated
+                                                         completion:completionBlock];
+    }
+
 }
 
 - (void)dismissModalHostView:(RCTModalHostView *)modalHostView

```

**Comment by formaldehydeson** [comment]
any update on this?

**Comment by eldirb21** [comment]
> > > Hai teman-teman, 
> > > Ketika Anda memiliki beberapa modal, atur `isVisible`param menjadi true untuk modal pertama dan tunjukkan, lalu pada `onModalHide`param modal ini, Anda dapat mengatur `isVisible`param untuk modal kedua. Jangan ragu untuk mengganggu saya untuk kejelasan lebih lanjut! .
> > > ```
> > >      //My first modal
> > >       <Modal
> > >          isVisible={this.state.firstModalVisible}
> > >          onBackdropPress={() => this.setState({ firstModalVisible: false })}
> > >          animationIn="fadeIn"
> > >          animationOut="fadeOut"
> > >          backdropOpacity={0}
> > >          hideModalContentWhileAnimating={true}
> > >          useNativeDriver={false}
> > >          onModalHide={() => {
> > >            //This function is invoked when the first modal is closed. Now here
> > >            //set the state for the second Modal.
> > >            this.setState({ secondModalvisible: true });
> > >            console.log("First modal closed");
> > >          }}
> > >        >....</Modal>
> > > 
> > >      //My second modal
> > >      <Modal
> > >          isVisible={this.state.secondModalvisible}
> > >          onBackdropPress={() => this.setState({ secondModalvisible: false })}
> > >          animationIn="fadeIn"
> > >          animationOut="fadeOut"
> > >          backdropOpacity={0}
> > >          hideModalContentWhileAnimating={true}
> > >          useNativeDriver={false}
> > >          onModalHide={() => {console.log("Second modal closed")}}
> > >       > .... </Modal>
> > > ```
> > 
> > 
> > Hai, 
> > saya punya pertanyaan. Saya harap Anda bisa menjawabnya. 
> > Konteksnya adalah: Saya punya button_1 membuka Modal1. Di dalam Modal1, ada button_2 yang membuka Modal_2. Setiap tombol memiliki `onClick`yang mengaktifkan `isVisible`bidang Modal .
> > dom saya terlihat seperti
> > ```
> > <View>
> >     // button_1
> >     <MyButtonComponent>
> >         <Button>
> >         </Button>
> >         // Modal_1
> >         <Modal>
> >              // button_2
> >             <MyButtonComponent>
> >                 <Button>
> >                 </Button>
> >                 // Modal_2
> >                 <Modal>               
> >                 </Modal>
> >             </MyButtonComponent>
> >         </Modal>
> >     <MyButtonComponent>
> > </View>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now if I click button_1 then click button_2, Modal_2 will open on top of Modal_1. What I want to achieve is that when I click button_2, Modal_1 will go away, and Modal_2 will open.
> > If I use `onModalHide` to set Modal_1 `isVisible=false`, then Modal_2 will never show up. I guess this is expected, because if the parent is gone, then the child will not be rendered.
> > Only each button component knows the content in the Modal. What should I do in this case?
> > Thanks,
> 
> Thanks, that's very helpful!

hello, if i may ask. how to make it simple, if i need more modal, it will need many states/properties, how to make it be 0ne state for many modals

**Comment by nandorojo** [comment]
I think there might be a light at the end of this tunnel.

`react-native-screens` is adding a `WindowView` component for iOS. It's functionally similar to the RN `<Modal />`: it renders on top of the entire app's UI, while maintaining context in the react tree.

And the best part: it allows _multiple_ window views to open at a time 👀

I recommend checking out the PR here: https://github.com/software-mansion/react-native-screens/pull/1096

**Comment by mmazzarolo** [comment]
Very cool @nandorojo , thanks for sharing!
(There's still the problem on the Android side though, right?)

**Comment by nandorojo** [comment]
@mmazzarolo You're probably right. I don't have much experience with Android. Does it have the same issue with multiple modals? If so, we could ask to add android support on that PR.

**Comment by mmazzarolo** [comment]
It has been a while since the last time I tried it but tep, the issue should be mostly the same (happens with native dialog as well).

**Comment by matheusmirandaferreira** [comment]
I have two modals and I can't encapsulate them, so I wrap the first with the state that controls the `isVisible` of the second

{!secondModalIsVisible && 
  <Modal isVisible={fisrtModalIsVisible}>
    ...
  <Modal>
}

<Modal isVisible={secondModalIsVisible}>
  ...
<Modal>

**Comment by mattddean** [comment]
This bug is still present, and while the workarounds listed above work, they are just that: workarounds. Can the bug be fixed at its root? Based on the fact that sleeping for a certain number of milliseconds works, I wonder if the issue is related to the animations of the modals. Is it possible that there is a bug in this library where two animations cannot be running at the same time?

**Comment by kaelwebdev** [comment]
For me the multiple modals in iOS didn't work, BUT then I was able to make it work. 

In my first modal I have an "OK" button so there I call a function that does:

`()=>{setShowModal(false); setShowModal2(true)}`

General idea:
```
const [showModal, setShowModal] = useState(false);
const [showModal2, setShowModal2] = useState(false);
...
<Modal>
<MyContent setShowModal={setShowModal}  setShowModal2={setShowModal2}/>
<Modal>
```
PD: MyContent is a component that I made, which has the content of the modal, in this case the "OK" button. In other people's case it could be the close button, the idea is the same.

**Comment by mp3por** [comment]
For me there is still a problem. 

I have a loading modal with a simple loading indicator which I show when something is loading. The problem is when my model is shown and then a system modal (LocationPermission for example) is shown on top. I can see the system modal but when i select an option, it closes but my modal does not close and I can not interact with it.

What to do ?

**Comment by Felipe-Tomazetti** [comment]
> @sqlProvider The only way I can have two modals at the same time is by nesting the second inside the first.
> 
> In my case, the second modal is a confirmation box based on something being done in the first modal.

I used the nested modals, but the second modal only shows for a brief momento >1s and disappears. Any way to make it longer?

**Comment by Felipe-Tomazetti** [comment]
> For me the multiple modals in iOS didn't work, BUT then I was able to make it work.
> 
> In my first modal I have an "OK" button so there I call a function that does:
> 
> `()=>{setShowModal(false); setShowModal2(true)}`
> 
> General idea:
> 
> ```
> const [showModal, setShowModal] = useState(false);
> const [showModal2, setShowModal2] = useState(false);
> ...
> <Modal>
> <MyContent setShowModal={setShowModal}  setShowModal2={setShowModal2}/>
> <Modal>
> ```
> 
> PD: MyContent is a component that I made, which has the content of the modal, in this case the "OK" button. In other people's case it could be the close button, the idea is the same.

I tried this one and the nested modal, still got the above problem

**Comment by Giasinit** [comment]
I've found the solution: The secondary Modal code should be placed inside the Primary Modal. This resolves the issue.

Here's the suggested example:

```jsx
<Modal
    animationType='fade'
    transparent={true}
    visible={this.state.modalVisibility}>

    {/* Secondary Modal */}
    <Modal
        animationType='fade'
        transparent={true}
        visible={this.state.secondaryModalVisibility}>

        <View style={[styles.modalContainer, modalBackgroundStyle]}>
            <View style={styles.innerContainer}>

                {this.secondaryContent()}

            </View>
        </View>
    </Modal>

    {/* Primary Modal */}
    <View style={[styles.modalContainer, modalBackgroundStyle]}>
        <View style={styles.innerContainer}>

            {this.mainContent()}

        </View>
    </View>
</Modal>
```

The solution was found at: [https://stackoverflow.com/a/35055128/18025486](https://stackoverflow.com/a/35055128/18025486)

**Comment by Wlknurl1** [comment]
Volkan ural

**Comment by bzozoo** [comment]
<ModalA>
   <ModalB/>
</ModalA>

This nested component solution is working for me on iOS too

**Comment by paufau** [comment]
For those still looking for a solution:

You could try this library. It’s the native solution with no limits on the number of modals: [https://github.com/paufau/react-native-multiple-modals](https://github.com/paufau/react-native-multiple-modals)

**Comment by cesargdm** [comment]
Looks like in latest React Native version 0.76, simple `<Modal />` iteration is supported.

**Comment by fariya12** [comment]
> I've found the solution: The secondary Modal code should be placed inside the Primary Modal. This resolves the issue.
> 
> Here's the suggested example:
> 
> <Modal
>     animationType='fade'
>     transparent={true}
>     visible={this.state.modalVisibility}>
> 
>     {/* Secondary Modal */}
>     <Modal
>         animationType='fade'
>         transparent={true}
>         visible={this.state.secondaryModalVisibility}>
> 
>         <View style={[styles.modalContainer, modalBackgroundStyle]}>
>             <View style={styles.innerContainer}>
> 
>                 {this.secondaryContent()}
> 
>             </View>
>         </View>
>     </Modal>
> 
>     {/* Primary Modal */}
>     <View style={[styles.modalContainer, modalBackgroundStyle]}>
>         <View style={styles.innerContainer}>
> 
>             {this.mainContent()}
> 
>         </View>
>     </View>
> </Modal>
> The solution was found at: https://stackoverflow.com/a/35055128/18025486

Thank you so much for the quick fix! This solution worked perfectly for me. Really appreciate your help 🙏
