### ISSUE TITLE
Border radius change the button color inside the Modal

### ISSUE THREAD

**Issue by camiloperezv** [react-native-community/react-native-modal#301]
Using the Modal fo react-native it does not happen and in IOS it does not happen either.

- [x] What version of `react-native-modal` 
 - 10.0.0 on Android Nexus_5X emulator
- [x] What packages or other dependencies you're using 
 - `react-native-elements` `1.0.0` Button
- [x] The behavior you expect to see, and the actual behavior
When I add a Button tag like this:
```
<Button
    buttonStyle={{backgroundColor:'ff0000', borderRadius:10}}
    title='hello world'
/>
````
I want to see the button with the right color, but if I use borderRadius, the color become darker and only happen inside the Modal. The other app buttons works.
- [x] **Most important of all:** An *isolated* 

```
<Modal isVisible style={{justifyContent: 'center', alignItems: 'center'}}>
        <Button
          buttonStyle={{backgroundColor:'#ff0000', borderRadius:10}}
          title='This color is not the real color'
        />
        <Button
          buttonStyle={{backgroundColor:'#ff0000'}}
          title='this Button works'
        />
</Modal>
```
This is an example of a button using `borderRadius:30`
<img width="249" alt="Captura de pantalla 2019-05-05 a la(s) 9 57 23 p  m" src="https://user-images.githubusercontent.com/8787377/57204976-d3b71980-6f80-11e9-8e98-b7850aa4dfcc.png">

This is exactly the same button element with `borderRadius:0`
<img width="258" alt="Captura de pantalla 2019-05-05 a la(s) 9 57 32 p  m" src="https://user-images.githubusercontent.com/8787377/57204985-e29dcc00-6f80-11e9-9097-4eeab986f8de.png">

**Comment by mmazzarolo** [comment]
@camiloperezv thanks for filling in the template 👍 
I think your problem is caused by the fact that `react-native-modal` uses a default "view" to render the content; this "view" style can be customized using the modal `style` props, so could you try changing your example above with:
```js
<Modal isVisible style={{justifyContent: 'center', alignItems: 'center', backgroundColor: 'transparent'}}>
```

**Comment by camiloperezv** [comment]
No, it does not works
```
<Modal isVisible style={{justifyContent: 'center', alignItems: 'center', backgroundColor: 'transparent'}}>
        <Button
          buttonStyle={{backgroundColor:'#ff0000', borderRadius:10}}
          title='This color is not the real color'
        />
        <Button
          buttonStyle={{backgroundColor:'#ff0000'}}
          title='this Button works'
        />
</Modal>
```
<img width="228" alt="Captura de pantalla 2019-05-06 a la(s) 6 23 02 a  m" src="https://user-images.githubusercontent.com/8787377/57222219-6aa6c480-6fc7-11e9-8294-242f313f7db4.png">

**Comment by mmazzarolo** [comment]
Hm, could you also try playing with the backdrop opacity (`backdropOpacity`) to see if it is causing the issue?
I think the issue might be related to [how react-native-elements handles the radius with a native touchable interface](https://github.com/react-native-training/react-native-elements/blob/2573e6f1420a8e36fe9ab98e6177de5b0f07c026/src/buttons/Button.js#L63) (maybe the touchable interface doesn't work well with a translucent background?
Another thing I would try is adding a colored background to see if it fixes the issue (just to understand what it's causing it):
```
<Modal isVisible style={{justifyContent: 'center', alignItems: 'center', backgroundColor: 'white'}}>
  <View style={{ backgroundColor: 'white' }}>
        <Button
          buttonStyle={{backgroundColor:'#ff0000', borderRadius:10}}
          title='This color is not the real color'
        />
        <Button
          buttonStyle={{backgroundColor:'#ff0000'}}
          title='this Button works'
        />
  </View>
</Modal>
```

**Comment by SamLucas** [comment]
An alternative solution to solve this detail is to place a `<View>` with a background `rgba(0,0,0,0.01)` as the first one after Modal.

**Comment by amirulasrof** [comment]
+1

**Comment by emilmammadov** [comment]
> Same thing happened to me when borderRadius is applied

@amirulasrof Removing the borderRadius solved my problem. Thanks. React-Native has problems with borderRadius on Android side. I faced one more time with the borderRadius situation.

**Comment by Razorholt** [comment]
Use `react-native-button` instead. Here is an example of my code:

```
<Button
     style={{ fontSize: 18, color: "#fff" }}
     containerStyle={{
          height: 50,
          paddingRight: 20,
          paddingLeft: 20,
          width: 130,
          borderRadius: 28,
          overflow: "hidden",
          justifyContent: "center",
          backgroundColor: "#156aa7"
     }}
     disabledContainerStyle={{ backgroundColor: "#c1c1c1" }}
     onPress={() =>
          navigation.navigate("CreateListScreen", {
               screen: route.key
          })
     }
>Create</Button>
```
If you want to use borderRadius with an Image, then include `resizeMode="cover"`

Hope it helps.
