### ISSUE TITLE
Understandable example for horizontal scroll

### ISSUE THREAD

**Issue by Hirbod** [react-native-community/react-native-modal#307]
Hi,

I've spent ours to implement horizontal scrolling (having Animated.ScrollView inside the modal), but everything I tried failed. I can only scroll my horizontal component only when I use 2 fingers, not if I use 1.

I have a animated slider inside the modal which I want to close swiping up / down and slide trough if I swipe right/left.

I can't get it work. I used "propagateSwipe", "scrollHorizontal" but there is no way for me to get it work.

Is there any understandable example for this?

**Comment by cjroth** [comment]
Hey, there's been an ongoing issue with scrolling inside of the modal. (#236)

Check out this PR: https://github.com/react-native-community/react-native-modal/pull/308
