### ISSUE TITLE
Animation Definitions Must Have At Least Two Values

### ISSUE THREAD

**Issue by jesster2k10** [react-native-community/react-native-modal#309]
![Screenshot 2019-05-19 at 09 05 47](https://user-images.githubusercontent.com/6454286/57979418-4e6a4500-7a15-11e9-86d8-9d26d727dc78.png)

Installing the library via yarn and importing it into my app like so causes it to crash, the code is:

```js
import React from 'react'
import { SafeAreaView, Text } from 'react-native'
import styled from 'styled-components/native'
import metrics from 'styles/metrics'
import Modal from 'react-native-modal'

type CardOverlayProps = {
  visible: boolean,
}

const CardOverlay = ({ visible }: CardOverlayProps) => {
  return (
    <Modal isVisible={visible}>
      <Container>
        <Card>
          <Text>A</Text>
        </Card>
      </Container>
    </Modal>
  )
}
```

When I add the "import Modal" line the app crashes with an error along the lines:

`Animation definitions must have at least two values`.
 Once I remove it, everything works. The original Modal component works to.

**Comment by jesster2k10** [comment]
I was able to track down the issue to this line of code in the `src/index.js` file:

`import * as animatable from 'react-native-animatable';`

**Comment by jesster2k10** [comment]
Okay,

So I found how to fix this. The error in fact was with the react-native-animatable library in the `registry.js` file in this particular function

`export function initializeRegistryWithDefinitions(definitions)`

I found for some reason that `{__esModule:true }` was being included in that definitions array which led to the whole two values error as that was a boolean.

So to fix it I just added a check in the function there

```js
 export function initializeRegistryWithDefinitions(definitions) {
  Object.keys(definitions).forEach(animationName => {
    console.log(definitions);
    if (animationName !== '__esModule') { // this got rid of the crash
      registerAnimation(
        animationName,
        createAnimation(definitions[animationName]),
      );
    }
  });
}
```

I'll close this and open a PR in the original library

**Comment by mmazzarolo** [comment]
Thanks @jesster2k10 !

**Comment by kuzkokov** [comment]
Hi, @jesster2k10 
I faced the same problem. It seems, that the problem isn't in any of the libraries, but rather in the `@babel/plugin-transform-modules-commonjs`. It's adding `__esModule: true` to exported object, this why this error is happening.
Probably, there are some settings for this module, but so far I just removed it from my `babel.config.js`, and Modal is working great.

**Comment by jesster2k10** [comment]
Yeah I’ve had a number of problems with that plugin and other libraries but
without enabling it my hot reloading wouldn’t work so I went ahead and made
a fork of the library including the change so I can keep using this and my
hot reloading

**Comment by hallya** [comment]
This did not fix the issue in my case sadly:

> Okay,
> 
> So I found how to fix this. The error in fact was with the react-native-animatable library in the `registry.js` file in this particular function
> 
> `export function initializeRegistryWithDefinitions(definitions)`
> 
> I found for some reason that `{__esModule:true }` was being included in that definitions array which led to the whole two values error as that was a boolean.
> 
> So to fix it I just added a check in the function there
> 
> ```js
>  export function initializeRegistryWithDefinitions(definitions) {
>   Object.keys(definitions).forEach(animationName => {
>     console.log(definitions);
>     if (animationName !== '__esModule') { // this got rid of the crash
>       registerAnimation(
>         animationName,
>         createAnimation(definitions[animationName]),
>       );
>     }
>   });
> }
> ```
> 
> I'll close this and open a PR in the original library

That did:

```js
export function initializeRegistryWithDefinitions(definitions) {
  Object.keys(definitions).forEach(animationName => {
    const animation = typeof definitions[animationName] === 'function'
      ? definitions[animationName]()
      : definitions[animationName];
    registerAnimation(
      animationName,
      createAnimation(animation)
    );
  });
}
```
