### ISSUE TITLE
How to make it stay at the bottom of the screen

### ISSUE THREAD

**Issue by matheusrezende** [react-native-community/react-native-modal#31]
want to make the modal show at the bottom of the screen like in the Bottom Half example, but i dont know what styles to apply, tried bottom: 0 but it didn't work

**Comment by mmazzarolo** [comment]
Hello @matheusrezende , you can find the source code of that example [here](https://github.com/react-native-community/react-native-modal/tree/master/example/src).

**Comment by matheusrezende** [comment]
Thank you @mmazzarolo!

**Comment by jitenderchand1** [comment]
Link is broken

**Comment by mmazzarolo** [comment]
@jitenderchand1 it was just the example dir of this project
