### ISSUE TITLE
RN modal transparency does not work in Android

### ISSUE THREAD

**Issue by nes123** [react-native-community/react-native-modal#311]
Anyone else experience that? The native modal cover the entire screen with white background. I have tried to use `<Modal transparent/> `and `<Modal transparent={true}/>` with no luck

**Comment by mmazzarolo** [comment]
not sure I understand what you're trying to achieve, have you tried disabling the backdrop? `hasBackdrop={false}`

**Comment by nes123** [comment]
Yes I disabled. But still the background is not transparent. It seems a problem with react native Modal. It happens just in Android and also when I am using react native modal and not react-native-modal package

**Comment by kenyontu** [comment]
I made this [Expo Snack](https://snack.expo.io/@kenyontu/transparent-react-native-modal-backdrop) that shows a modal without backdrop and I didn't have this issue.
Could you describe how you are building your modal? Or even better, make a snack reproducing the issue.

**Comment by xgenem** [comment]
Perhaps @nes123 confused this to be part of the package `react-native` and not the `react-native-modal` package.

**Comment by nes123** [comment]
It ended up to be a problem with the definition in the styles.xml file. It is not a bug in the package. Sorry for the false alarm

**Comment by mmazzarolo** [comment]
no problem! thanks for reporting back @nes123

**Comment by WouterFlorijn** [comment]
@nes123 could you tell us what you changed in `styles.xml`?
