### ISSUE TITLE
Background ui doesnt change when modal is ui

### ISSUE THREAD

**Issue by aliazizi** [react-native-community/react-native-modal#314]
When I open modal I add set a timer to change background ui when timer is finished the background changes not show throuth transparent box.

## Environment

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
      Memory: 526.88 MB / 7.92 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - D:\watchman\watchman.EXE
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

## Platforms

Android

## Versions

- Android: 7
- react-native-modal: 11.0.1
- react-native: 0.59.8
- react: 16.8.6

**Comment by eyalabadi98** [comment]
I'm having kinda the same issue, where I cant update the screen by making state or prop changes

**Comment by mmazzarolo** [comment]
👋 Please follow the entire issue template before submitting the issue (needs a reproducible example)
