### ISSUE TITLE
hasBackdrop = false - inactive Backdrop area

### ISSUE THREAD

**Issue by ezha86** [react-native-community/react-native-modal#316]
Hi all.
Im using "react-native-modal": "11.0.1"

i set hasBackdrop to false but cant interact with Backdrop area, im actually trying to show modal over map, but if modal is open i cant click or swipe on the map.

is this expected behavior ?

**Comment by mmazzarolo** [comment]
👋 
> is this expected behavior ?
Yep, it is. A modal, by definition, will always cover the entire screen, regardless of showing or not the backdrop.  
I guess that instead of a modal you should look into an absolutely positioned view.

**Comment by ezha86** [comment]
thanks.

**Comment by pixelize** [comment]
@ezha86 i have the same use case, a modal and a map behind. What solution did you found to solve this pease ? :)

**Comment by ezha86** [comment]
@pixelize  i ended up with https://github.com/octopitus/rn-sliding-up-panel
