### ISSUE TITLE
coverScreen doesn't work for me

### ISSUE THREAD

**Issue by Ashkan-Oliaie** [react-native-community/react-native-modal#318]
I needed a modal so I'll be able to manipulate the background stuff but when I use coverScreen=false the modal just get rendered somewhere in the screen and I can interact with that meanwhile I can interact with the background components but not the Modal itself

**Comment by mmazzarolo** [comment]
Please follow the issue template before submitting an issue (this is more of an issue than a question). Thank you!

**Comment by Christopher-Marim** [comment]
Estou enfrentando o mesmo problema, como proceder?
