### ISSUE TITLE
Control if modal is closed

### ISSUE THREAD

**Issue by QuevedoIB** [react-native-community/react-native-modal#322]
## Is there any way to control if the modal closing transition finished outside of the modal component?

I'd like to call the optionPress function once the modal is hidden but I don't manage to make it.

The reason: react-native-document-picker crashes on iOS when you call it because modal is not hidden, for now I'm delaying the function with a setTimeOut but thats a bad practice I'd like to avoid using.

**Comment by mmazzarolo** [comment]
The `onModalHide` prop is called when the modal transition has completed.
