### ISSUE TITLE
Is it possible to set each swipe direction has own onSwipeComplete?

### ISSUE THREAD

**Issue by AidenJongheeLee** [react-native-community/react-native-modal#325]
## Ask your Question
Hello, 
This is an awesome library but I'm trying to add when the user swipes modal it expands modal and swipes down to close. In the document, I can set multiple directions but It looks like I can set only one onSwipeComplete. Is there any other way to do this?
Thanks

**Comment by rewieer** [comment]
Hello !
This can easily be implemented. I don't have time right now, but a PR would be most welcome. It consists just of passing the current swipe direction to the "onSwipeComplete" function.
@mmazzarolo what do you think ?

**Comment by mmazzarolo** [comment]
Same for me, we're open to PR for new features 👍

**Comment by KarthikSiddarth** [comment]
I am interested in implementing this feature.

**Comment by kenyontu** [comment]
@KarthikSiddarth #319 implements this feature. It's already approved, but missing an update in the README file.

**Comment by mmazzarolo** [comment]
Pr above is merged, mind reviewing #331 ?
