### ISSUE TITLE
Modal moves the view on the page

### ISSUE THREAD

**Issue by haileymattingly** [react-native-community/react-native-modal#326]
When the modal is opening the view on the page it is opening over shifts up slightly and when the modal is closed it does not move back down either. HELP! I've been staring at this for two days.

**Comment by mmazzarolo** [comment]
Hey @haileymattingly ! I'm sorry but for support you should probably ask this question on stackoverflow.   
If you think this is an issue with the module please create an issue following the issue template. Thank you!
