### ISSUE TITLE
React Native modal does not work with snackbar

### ISSUE THREAD

**Issue by FahadRS** [react-native-community/react-native-modal#329]
I am using react native modal with the react-native-snack-bar https://github.com/cooperka/react-native-snackbar, i have a scenario in which when user perform any action in the modal i need to hide the modal and show the snackbar, problem which i am facing is that when i hide the modal snackbar also hides. i have also tried to show the snackbar in onModalHide event but still modal and snackbar both hide

`onModalHide(){
    Snackbar.show({
      title: 'Hello world',
      duration: Snackbar.LENGTH_SHORT
    });
 }`

only workaround which is working for me is to show the snackbar after 1-2 seconds with time out

` setTimeout(this.showSnackbar.bind(null, index),1000); `

Is there any way i can show the snackbar after closing the modal without using timeout

**Comment by mmazzarolo** [comment]
Hey @FahadRS ! Could you try swapping replacing `react-native-modal` with react-native's own Modal component and see if the issue is still there?
