### ISSUE TITLE
undefined is not an object evaluating  (_reactnative.Modal.propTypes.animationType)

### ISSUE THREAD

**Issue by akshay1293** [react-native-community/react-native-modal#330]
I have recently updated my react-native app to RN 0.55.0 to RN 0.59.0. After updating app, it crashes on initial screen saying.

undefined is not an object evaluating  (_reactnative.Modal.propTypes.animationType)

![Screenshot_20190706-143210](https://user-images.githubusercontent.com/25977775/60754223-93fdc400-9ffb-11e9-96a8-f5672e7993d8.jpg)

here is my app dependencies:

"dependencies": {
    "react": "16.8.0",
    "react-native": "0.59.0",
    "react-native-actionsheet": "2.4.2",
    "react-native-communications": "2.2.1",
    "react-native-custom-actionsheet": "0.0.4",
    "react-native-flexi-radio-button": "0.2.2",
    "react-native-google-signin": "0.12.0",
    "react-native-htmlview": "0.13.0",
    "react-native-keep-awake": "3.1.0",
    "react-native-material-textinput": "1.1.0",
    "react-native-modal": "11.1.0",
    "react-native-simple-dialogs": "0.3.1",
    "react-native-textarea": "1.0.2",
    "react-navigation": "2.5.1",
    "react-redux": "5.0.7",
    "redux": "4.0.0",
    "yarn": "1.7.0"
  },
  "devDependencies": {
    "@babel/core": "7.3.4",
    "@babel/runtime": "7.3.4",
    "babel-jest": "24.4.0",
    "jest": "24.4.0",
    "metro-react-native-babel-preset": "0.53.0",
    "react-test-renderer": "16.8.3"
  }

Any help is appreciated,
Thanks.

**Comment by wagnermengue** [comment]
try update:
`"react-native-simple-dialogs": "latest",`
and npm i

**Comment by mmazzarolo** [comment]
@wagnermengue thanks for the suggestion.
@akshay1293 could you please try @wagnermengue solution? If you're still facing this issue please create a new issue here (following the entire issue template). Thank you!

**Comment by liplylie** [comment]
For me, downgrading to a version of react-native below 0.58 worked. React-native > 0.58 does not support Modal.propTypes. 

https://github.com/raynor85/react-native-modal-wrapper/issues/14

**Comment by mmazzarolo** [comment]
@liplylie thanks for reporting it

**Comment by Natkarock** [comment]
> @liplylie thanks for reporting it

Hello! are you going to fix this problem? not working on RN 0.59

**Comment by mmazzarolo** [comment]
I'll try to work on fixing it by the end of this week @Natkarock 
If anyone is willing to send a PR it would probably speed up the process 👍

**Comment by Natkarock** [comment]
Sorry. In my case problem was in another library. This library is working correctly.

**Comment by mmazzarolo** [comment]
Just had some free time to check it, `react-native-modal` doesn't seem to be using `Modal.propTypes` so I guess it was just caused by the other libraries. 
Closing!

**Comment by waheedakhter** [comment]
@Natkarock  @mmazzarolo  can you plz explain what exactly was causing this issue? and how to solve this?

**Comment by Natkarock** [comment]
> @Natkarock @mmazzarolo can you plz explain what exactly was causing this issue? and how to solve this?

In my case problem was in other library. This is bug of other library

**Comment by Dheeeraj** [comment]
> @Natkarock @mmazzarolo can you plz explain what exactly was causing this issue? and how to solve this?

For me react-native-linkedin caused this error
I sloved it by opening node_modules/react-native-linkedin/index.js of my project and searched for 'Modal.propTypes.animationType' replaced it with a default value 'fade'.

**Comment by gouravrc** [comment]
> try update:
> `"react-native-simple-dialogs": "latest",`
> and `npm i`

Thanks mate! It worked. But I wonder, why it just stated _reactnative.Modal.propTypes.animationType = undefined. 
react-native-simple-dialogs not using react-native-modal as dependency.
