### ISSUE TITLE
blinking screen while close the popup screen.

### ISSUE THREAD

**Issue by JsonAveza** [react-native-community/react-native-modal#333]
## Versions

- Android:
- iOS:
- react-native-modal:
- react-native:
- react:

**Comment by tonyJinhuagu** [comment]
麻烦问下，我也出现了这个问题

**Comment by soutot** [comment]
> 麻烦问下，我也出现了这个问题

Check this, it fixed for me https://github.com/react-native-modal/react-native-modal/issues/268#issuecomment-493464419
