### ISSUE TITLE
Allow for a more customizable backdrop then the current customBackdrop

### ISSUE THREAD

**Issue by leqphi** [react-native-community/react-native-modal#337]
## Versions

- Android:
- iOS:
- react-native-modal:
- react-native:
- react:

## Description

We have an accessibility problem with the backdrop. When opening a modal with a backdrop, the backdrop becomes the first focused element on Android. This happens because TouchableWithoutFeedback wraps the backdrop.

If we are able to create a fully custom backdrop, we will have more control to work with accessibility issues.

**Comment by mmazzarolo** [comment]
#336
