### ISSUE TITLE
onBackdropPress does not work on version 11

### ISSUE THREAD

**Issue by hungdev** [react-native-community/react-native-modal#341]
## Platforms
IOS
## Versions

- Android: i didnt test on android
- iOS: Ipad pro 3rd emulator
- react-native-modal: 11.3.1
- react-native:0.60.4
- react:16.8.6

## Description
onBackdropPress does not work on version 11
After that i rollback to version 10.0.0, it works fine for me.

**Comment by mmazzarolo** [comment]
Weird, should work on #338 .
Could you please follow the entire issue template and provide an isolated reproducible example? 
[Are you using a custom backdrop?](https://github.com/react-native-community/react-native-modal#the-custom-backdrop-doesnt-dismiss-the-modal-on-press)

**Comment by hungdev** [comment]
yes, sorry about miss read docs.
