### ISSUE TITLE
Why not just set content transparent while `hideModalContentWhileAnimating`?

### ISSUE THREAD

**Issue by mrzie** [react-native-community/react-native-modal#343]
I saw that `hideModalContentWhileAnimating` hide content view after closing animation end by rendering an empty `View`.But that may effect the lifecycle of children.

Why not just set `{opacity: 0}` instead?

**Comment by mmazzarolo** [comment]
Mainly because if I recall correctly `opacity: 0` was still rendering the component tree (if I recall correctly), so it wouldn't have solved the performance issues. 
Don't know if now RN has changed that behaviour though...

**Comment by rewieer** [comment]
Yes, setting the opacity to 0 **doesn't** unmount the component.

**Comment by mrzie** [comment]
> Mainly because if I recall correctly `opacity: 0` was still rendering the component tree (if I recall correctly), so it wouldn't have solved the performance issues.
> Don't know if now RN has changed that behaviour though...

That's right.
And as I know `hideModalContentWhileAnimating` is made for fixing the problem that using `useNativeDriver` might lead to some nasty flashes.
[Workaround for the flashes when useNativeDriver={true} #116](https://github.com/react-native-community/react-native-modal/pull/116)

In this case, I thought if using `opacity: 0` brings fewer side effects and be more friendly to existing projects.

**Comment by mmazzarolo** [comment]
> In this case, I thought if using opacity: 0 brings fewer side effects and be more friendly to existing projects.  

You could try it by manually setting the content opacity to 0 when you set `isVisible` to `false` and back to 1 when you set `isVisible` to `true`... That said, I have no idea what kind of benefit you might have with that. Let me know!
