### ISSUE TITLE
adding backdrop and coverScreen makes the animation not smooth

### ISSUE THREAD

**Issue by Ashkan-Oliaie** [react-native-community/react-native-modal#345]
## Environment
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
    Memory: 1.07 GB / 7.92 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - G:\Native apps\Styleey\node_modules\.bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      Android NDK: 19.1.5304403
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501

## Platforms
Android

## Versions
- react-native-modal:  11.3.1
- react-native: 0.60.5

## Description
when Modal is opening and closing everything is smooth untill I add "coverScreen" or "hasBackdrop" 
they makes the animation not smooth and laggy somehow

I've tested it on react-native Original Modal and everything is fine there

do remove lagginess I disabled backDrop and coverScreen , but when I remove coverScreen , the Buttn component from "react-native-paper" comes in front of the modal .... weired

**Comment by Ashkan-Oliaie** [comment]
I couldn't find a solution so I had to make the react-native-paper Button "outlined", so it won't appear on the screen, I think i has something to do with elevation .

**Comment by mmazzarolo** [comment]
@Ashkan-Oliaie I think you're probably right. The native elevation property on Android sometimes doesn't work well within a modal. 
I'm closing it for now, but feel free to create a new issue if you can submit a minimal reproducible example/repo of the bug (without `react-native-paper`). 
Thank you!
