### ISSUE TITLE
Modal and Header

### ISSUE THREAD

**Issue by phillipcmittmann** [react-native-community/react-native-modal#346]
So im havin some troubles trying to render both a custom Header and the Modal on the same screen. When the Modal is supposed to be visible, he appears off-screen. My code is something like this:

<View style={{ flex: 1 }}>
    <Header />

    <ScrollView>
        ...
    <ScrollView>
</View>

Any idea how to style this?

**Comment by mmazzarolo** [comment]
👋 the best place for this kind of questions is StackOverflow. I would suggest you to post it there, tag it as `react-native` and add a reproducible example of your problem.
