### ISSUE TITLE
web support ?

### ISSUE THREAD

**Issue by flieks** [react-native-community/react-native-modal#347]
not sure if this should be put in expo issues or here but when building for web, the modal works partly:
https://web-build-emy6a8m2f.now.sh

normally it shouldn't show by default (because isVisible is false at first)

**Comment by rewieer** [comment]
This repo depends on the native React-Modal for the modal itself. 
It seems on the web, react-native-web uses it's own modal component, so I believe this shouldn't work.

**Comment by vladp** [comment]
I am trying to use with react-native-web.
It works when modal needs to be displayed 'within' a particular component (eg within scroll view).
However, when I need modal to cover the whole screen within the browser, it does not work and instead is resized to be confined within parent's view dimention.

`coverScreen` setting does not seem to do anything

**Comment by emac3** [comment]
@rewieer react-native-web does not implement the [Modal](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Modal/index.js) component, but there are interesting discussions [here](https://github.com/react-native-community/react-native-modal/issues/145) and [here](https://github.com/react-native-community/react-native-modal/issues/261).

**Comment by izakfilmalter** [comment]
FYI react-native-web@0.14.0 now supports Modal. Currently testing this lib for web, and everything is working well from what I can tell so far..
