### ISSUE TITLE
isVisible can not work but I use ternary operator

### ISSUE THREAD

**Issue by liyaolin** [react-native-community/react-native-modal#349]
I use Modal is ok  but the mehod of opening is something wrong, I use prop isVisible by state, but it can not show,and when I use  ternary operator, it works, but dont have Animation effects wen it hide
eg.  can not work
`  state = {
    visible: false,
  }
  render() { 
    return (
      <View style={styles.container}>
        <Button title="Show modal" onPress={this.openHandle.bind(this)} />
        <Modal
            isVisible={this.state.visible}
            onBackdropPress={this.closeHandle.bind(this)}
            style={styles.bottomModal}>
            <View style={{height: 200, backgroundColor: '#fff'}}>
              <Text>test modal</Text>
            </View>
          </Modal>
      </View>
    )
  }
  openHandle(){
    this.setState({
      visible: true
    })
  }
  closeHandle(){
    this.setState({
      visible: false
    })
  }`

but if I use ternary operator, it is ok
`  state = {
    visible: false,
  }
  render() { 
    return (
      <View style={styles.container}>
        <Button title="Show modal" onPress={this.openHandle.bind(this)} />
        {
            this.state.visible ? <Modal
            isVisible={this.state.visible}
            onBackdropPress={this.closeHandle.bind(this)}
            style={styles.bottomModal}>
            <View style={{height: 200, backgroundColor: '#fff'}}>
              <Text>test modal</Text>
            </View>
          </Modal> : null
       }
      </View>
    )
  }
  openHandle(){
    this.setState({
      visible: true
    })
  }
  closeHandle(){
    this.setState({
      visible: false
    })
  }`

who can tell me why?

**Comment by rewieer** [comment]
That's because you are mounting and unmounting based on your ternary operator. You should put your ternary operator as a isVisible props.
For further help, please ask on forums and stackoverflow.

**Comment by liyaolin** [comment]
> That's because you are mounting and unmounting based on your ternary operator. You should put your ternary operator as a isVisible props.
> For further help, please ask on forums and stackoverflow.


sorry, I do not know what you mean, but the first code is running good by RN`s Modal, https://reactnative.cn/docs/modal/

**Comment by mmazzarolo** [comment]
@liyaolin please follow the example in the README and see if it works

**Comment by liyaolin** [comment]
> @liyaolin please follow the example in the README and see if it works

yes,I use  the `A complete example`  code to run but cannot appear modal, and I add ternary operator,it is ok, press the button the modal is appear!

**Comment by xiayuanquan** [comment]
me too! Very doubtful and annoying。。。

**Comment by negrudev** [comment]
+1
