### ISSUE TITLE
Full width for the modal

### ISSUE THREAD

**Issue by rawadrifai** [react-native-community/react-native-modal#351]
Hi, is it possible to have the modal occupy the full width of the screen? I'm sure it is, just can't figure it out.

**Comment by gie3d** [comment]
I think the reason that the modal doesn't show the full width is because of it has a default margin. if you want the full width, you may set the marginHorizontal to 0 and then you got the full width.

`
<Modal style={{marginHorizontal: 0}}><YourComponent /></Modal>
`

**Comment by rawadrifai** [comment]
I added margin:0 and it worked. Thank you.

**Comment by Aryk** [comment]
I actually found it here...but for those wondering it's in the documentation too:

https://github.com/react-native-modal/react-native-modal#the-modal-is-not-covering-the-entire-screen
