### ISSUE TITLE
BackdropOpacity does not work with open modal

### ISSUE THREAD

**Issue by joaodematejr** [react-native-community/react-native-modal#353]
## Environment

<! - System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 962.37 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 21, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.1
      System Images: android-25 | Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1 ->

## Platforms

<! - Android ->

## Versions

<! - Please add the used versions / branches ->

- Android: API 28 Android 9
- iOS: - 
- react-native-modal: ^11.3.1
- react-native: 0.60.5
- react: 16.8.6

## Description

 I am trying to change the 'backdropOpacity' with open modal, but not updating value would be a bug? 

![Gravação-de-Tela-2019-09-17-às-17 43 35](https://user-images.githubusercontent.com/17418041/65078482-7772f600-d973-11e9-9d1e-bc994dc24eb1.gif)

![Captura de Tela 2019-09-17 às 17 51 00](https://user-images.githubusercontent.com/17418041/65078671-e18b9b00-d973-11e9-90ba-56d2dca6b60b.png)
![Captura de Tela 2019-09-17 às 17 51 17](https://user-images.githubusercontent.com/17418041/65078677-e3edf500-d973-11e9-8803-cf5dd5905d0e.png)
![Captura de Tela 2019-09-17 às 17 51 56](https://user-images.githubusercontent.com/17418041/65078684-e7817c00-d973-11e9-9f1b-6a554e4807dd.png)

**Comment by mmazzarolo** [comment]
👋 @joaodematejr ! Thanks for submitting the issue. 
Could you please follow the issue template and add a minimal reproducible example of the issue? Thank you.

**Comment by joaodematejr** [comment]
Updated to version 11.4.0 the problem has been fixed

**Comment by joaodematejr** [comment]
import React, {useState} from 'react';
import {Text, SafeAreaView, View, Button} from 'react-native';
import Modal from 'react-native-modal';

export default function HelloWorldApp() {
    const [modal, setModal] = useState(false);
    const [colorOpacityModal, setColorOpacityModal] = useState(0.9);
    return (
        <SafeAreaView
            style={{
                flex: 1,
                justifyContent: 'center',
                alignItems: 'center',
            }}>
            <Button title="Open Modal" onPress={() => setModal(true)} />
            <Modal
                isVisible={modal}
                backdropColor="black"
                backdropOpacity={colorOpacityModal}
                supportedOrientations={['portrait', 'landscape']}
                hideModalContentWhileAnimating={true}
                onSwipeComplete={() => setModalVisibleCam(false)}
                swipeDirection={['down']}
                onRequestClose={() => {
                    setModalVisibleCam(false);
                }}
                style={{
                    borderRadius: 1,
                    margin: 0,
                    justifyContent: 'center',
                    borderColor: 'rgba(0, 0, 0, 0.1)',
                }}>
                <View>
                    <Button
                        title="Close modal"
                        onPress={() => setModal(false)}
                    />
                    <Button
                        title="Change color"
                        onPress={() => setColorOpacityModal(0.1)}
                    />
                </View>
            </Modal>
        </SafeAreaView>
    );
}

**Comment by joaodematejr** [comment]
@mmazzarolo thanks !
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17418041/65425393-3f8d0800-dde4-11e9-9500-9243cf405e1b.gif)

**Comment by mmazzarolo** [comment]
Glad it was fixed! :)
