### ISSUE TITLE
getting componentWillRecieveProps deprecation message for withAnimateable component

### ISSUE THREAD

**Issue by TheRogue76** [react-native-community/react-native-modal#354]
## Environment

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 5.13 GB / 15.43 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312

## Platforms

Android

## Versions

- Android:9
- iOS:-
- react-native-modal:11.3.1
- react-native:0.60.5
- react:16.8.6

## Description

Hi. even tho the release notes for 11.2.0 says it removed the usage of componentWillRecieveProps, i still get the deprecation message in 11.3.1.

## Reproducible Demo

![Capture](https://user-images.githubusercontent.com/40071952/65371433-d1780200-dc78-11e9-82b0-8e13846671e2.PNG)

code:

import React, {Component} from 'react';
import { 
  Text, 
  View,
  Button,
  StyleSheet
} from 'react-native';
import Modal from 'react-native-modal';

export default class App extends Component {
  state = {
    isModalVisible : false
  };

  toggleModal = () => {
    this.setState({
      isModalVisible: !this.isModalVisible
    });
  };
  render() {
    return (
      <View style={styles.main}>
        <Button title="Show Modal" onPress={this.toggleModal}></Button>
        <Modal isVisible={this.state.isModalVisible}>
          <View style={styles.modalView}>
            <Text>Hello</Text>
            <Button title="Hide Modal" onPress={this.toggleModal}></Button>
          </View>
        </Modal>
      </View>
    );
  }
}

const styles= StyleSheet.create({
  main : {
    flex : 1
  },
  modalView :{
    flex : 1
  }
});

**Comment by mmazzarolo** [comment]
Waiting for https://github.com/oblador/react-native-animatable/pull/280 to be merged in to fix the waning.
