### ISSUE TITLE
How can I set width & height of modal ?

### ISSUE THREAD

**Issue by nlshuynguyen** [react-native-community/react-native-modal#358]
## Ask your Question

How can I set width & height of view modal? I try margin in style but it not work well. I want to set width & height view so when I rotate phone the view modal will not too big.
![Screen Shot 2019-10-10 at 2 26 33 PM](https://user-images.githubusercontent.com/53550422/66547710-01287480-eb6a-11e9-82b9-69776f0a5ad6.png)
![Screen Shot 2019-10-10 at 2 26 39 PM](https://user-images.githubusercontent.com/53550422/66547711-01287480-eb6a-11e9-891d-d6ad0caa7723.png)

**Comment by rewieer** [comment]
Questions related to how to use the project must be posted on StackOverflow, where it'll also help other people with the same problem.

**Comment by Multi-Thinker** [comment]
+1 same issue, adding style on View in Modal never seems to work.

**Comment by mikeymop** [comment]
I resolved this by putting a `<View>` inside the modal and resizing that.
eg:

```jsx
<Modal
      isVisible={isVisible}
      onBackdropPress={() => setVisible(false)}
    >
      <View style={{maxHeight: 400}}>
          ...
        <View>
            {children}
        </View>
      </View>
    </Modal>
```
