### ISSUE TITLE
onSwipeComplete not working when presentationStyle is pageSheet

### ISSUE THREAD

**Issue by danielfein** [react-native-community/react-native-modal#360]
### When reporting a bug, please be sure to check if the issue still persists with react-native original modal:
Under the hood `react-native-modal` uses react-native original [Modal component](https://facebook.github.io/react-native/docs/modal.html).  
Before reporting a bug, try swapping `react-native-modal` with react-native original Modal component to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [x] The outcome of the `react-native-modal` swap described above
- [x] A descriptive title
- [x] What version of `react-native-modal` you're using, and the platform(s) you're running it on (iOS, Android, device)
11.4.0
- [x] What packages or other dependencies you're using
-- This is most relevant
- [x] The behavior you expect to see, and the actual behavior
- [x] **Most important of all:** An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
-- see below

### When you open an issue for a feature request, please add as much detail as possible:
onSwipeComplete not working when presentationStyle is pageSheet
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem

Currently, when you use presentationStyle="pageSheet" or "formSheet" and attempt to call onSwipeComplete or onModalHide or onModalWillHide, none are called. This leads to the rest of the component being unaware that the modal has been closed and does not change the state for modal-visibility monitoring.

This is a problem for obvious reasons, and sample code looks like this, none of the shown functions are being called:

```
     <Modal presentationStyle="pageSheet"  isVisible={infoModalVisible}
                onSwipeComplete={() => this.setInfoModalViewVisible(false)}
                onModalHide={() => this.setInfoModalViewVisible(false)} 
                onModalWillHide={() => console.log("DFF")}
                >
```

**Comment by levelingup** [comment]
How do you get presentationStyle to work correctly? I get a warning message saying the modal doesn't support it.

**Comment by sabaoonbedar** [comment]
#solved 
For the problem there is a simple solution what you all need to do is: 
1. Design a button in react native
2. In the constructor state code add this code:
constructor(){
super();
this.state={

isVisible:false

}
3. Now move to the button and add this as onPress event:
  this.showmodal(show=false)
  this.showmodal(show=true)

Reference function/helper function that you can take work with:

showmodal = show =>{

    this.setState({isVisible:show});
    
      }
