### ISSUE TITLE
error screen once upgrade to v11.5.0

### ISSUE THREAD

**Issue by yeong0809** [react-native-community/react-native-modal#366]
## Environment
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 48.98 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.8.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.3 => 0.61.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Platforms
Both platforms iOS and Android

## Versions
- Android: All
- iOS: All
- react-native-modal: v11.5.0
- react-native: 0.61.3
- react: 16.9.0

## Description
**Error**
Unable to resolve module `./modal` from `node_modules/react-native-modal/dist/index.js`:   None of these files exist:   * node_modules/react-native-modal/dist/modal(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)   * node_modules/react-native-modal/dist/modal/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)  RCTFatal __28-[RCTCxxBridge handleError:]_block_invoke _dispatch_call_block_and_release _dispatch_client_callout _dispatch_main_queue_callback_4CF __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ __CFRunLoopRun CFRunLoopRunSpecific -[NSRunLoop(NSRunLoop) runMode:beforeDate:] -[NSRunLoop(NSRunLoop) runUntilDate:] +[RNSplashScreen show] -[AppDelegate application:didFinishLaunchingWithOptions:] -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] -[UIApplication _runWithMainScene:transitionContext:completion:] __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke _performActionsWithDelayForTransitionContext -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] -[FBSSceneImpl _didCreateWithTransitionContext:completion:] __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke _dispatch_client_callout _dispatch_block_invoke_direct __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ -[FBSSerialQueue _performNext] -[FBSSerialQueue _performNextFromRunLoopSource] __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ __CFRunLoopDoSources0 __CFRunLoopRun CFRunLoopRunSpecific GSEventRunModal UIApplicationMain main start 0x0

## Reproducible Demo
The error shows up once when react-native start is bundling react-native-modal

![Simulator Screen Shot - iPhone 5s - 2019-11-01 at 17 20 03](https://user-images.githubusercontent.com/31876283/68015162-8bc54500-fccc-11e9-8be2-02c8b2dc0fa4.png)

**Comment by mjmasn** [comment]
Looks like the "main" and "types" paths in `package.json` point to `dist/` but the "files" array only includes `src/` and `typings/`
