### ISSUE TITLE
Use ModalProps and make default props optional?

### ISSUE THREAD

**Issue by quyenhoa** [react-native-community/react-native-modal#368]
I'm writing a wrapper of react-native-modal, I want to use ModalProps type.
From v11.5 all default props in ModalProps are required, so I can't use ModalProps anymore.
Is there a way to make this work for my purpose?

**Comment by rewieer** [comment]
Yes, not all props should be required so there's still a bit of work to be done on our side.

**Comment by Sakarisson** [comment]
I'm also currently facing a similar issue, which is blocking me from upgrading the library.

@rewieer Would it be okay if I took a crack at fixing this issue? I can probably make a PR sometime this week.

**Comment by leethree** [comment]
any update on this?

**Comment by nabati** [comment]
The updated version of the library is not really usable for people who are using TypeScript right now.

**Comment by rewieer** [comment]
@Sakarisson @leethree @nabati PR are most welcome if you happen to have time and a solution to fix it

**Comment by malyfko** [comment]
@quyenhoa use Partial<ModalProps> (TS)

**Comment by thenrikie** [comment]
`Partial<ModalProps> & Pick<ModalProps, "children" | "isVisible">` should do
