### ISSUE TITLE
[iOS] Modal cannot be dismissed when pressed on backdrop

### ISSUE THREAD

**Issue by kmvkrish** [react-native-community/react-native-modal#377]
## Environment
ReactNative: 0.61.4
ReactJS: 16.9
**React-Native-Modal: 11.5.3**

## Platforms
**iOS: 12.3.1**

## Versions
**React-Native-Modal: 11.5.3**

- Android:
- iOS: 12.3.1
- react-native-modal: 11.5.3
- react-native: 0.61.4
- react: 16.9.0

## Description

In a bare-bones application, when tried to dismiss the modal by tapping on the backdrop the modal is not dismissed. When observed, the "**onBackdropPress**" method is never executed in iOS.

## Reproducible Demo

1. Create a demo project using `react-native init rnmodaldemo`
2. Move into the directory and install the react-native-modal dependency.
3. In the App.js file, add the code to show the modal.
4. Add a method that updates the state to hide the modal -> `this.setState({ .isModalVisible: false })`
5. run `pod install` in the iOS directory
6. Run the command `react-native run-ios`
7. Press/tap on the backdrop of the modal. onBackdropPress method is never executed for iOS.

Full source code for App.js file:

```
import React from 'react';
import {SafeAreaView, View, Text} from 'react-native';

import ReactNativeModal from 'react-native-modal';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isModalVisible: true,
    };
  }

  onBackgropPress = () => {
    this.setState({
      isModalVisible: false,
    });
  };

  render() {
    return (
      <SafeAreaView>
        <ReactNativeModal
          backdropOpacity={0.4}
          onBackdropPress={this.onBackdropPress}
          isVisible={this.state.isModalVisible}>
          <View
            style={{
              height: 240,
              width: 320,
              backgroundColor: 'white',
              padding: 10,
              alignItems: 'center',
              textAlign: 'center',
            }}>
            <Text style={{color: 'black', fontSize: 16, fontWeight: 'bold'}}>
              Modal is presented.
            </Text>
          </View>
        </ReactNativeModal>
      </SafeAreaView>
    );
  }
}
```

**Comment by brandojones** [comment]
You named the function "onBackgropPress" but you'll need it to be "onBackdropPress"
(misspelled "drop" on the function name)

**Comment by RichardLindhout** [comment]
@brandojones No he can name it whatever he wants but the name is right to the library.

**Comment by RichardLindhout** [comment]
library -> onBackdropPress
file ->       onBackdropPress={this.onBackdropPress}

**Comment by mahdidavoodi7** [comment]
anyone fixed this problem ?

**Comment by rewieer** [comment]
Doesn't seem to be happening anymore
