### ISSUE TITLE
Modal dont work while debugging is active

### ISSUE THREAD

**Issue by Skynear2** [react-native-community/react-native-modal#379]
## Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 419.83 MB / 3.91 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312

## Platforms

Android

## Versions

- Android: 8.1.0

- react-native-modal: 11.3.1
- react-native: 0.60.5
- react: 16.8.6

## Description

All components that use react-native-modal work perfectly even with animations. The problem exists when remote debug mode is active. The modal does not open at all.

## Reproducible Demo

Create any screen that has a modal and try to open it using any button with remote debug mode enabled.

**Comment by mmazzarolo** [comment]
Hey @Skynear2 , unfortunately IIRC this is a react-native's modal problem and with can't fix it from our side.

**Comment by kubilaytural** [comment]
> Hey @Skynear2 , unfortunately IIRC this is a react-native's modal problem and with can't fix it from our side.

Is that really your answer? I haven't encountered such problems in other libraries. I think you should handle this issue.
