### ISSUE TITLE
Simultaneous opening of modals causes unexpected freeze.

### ISSUE THREAD

**Issue by tankpower1** [react-native-community/react-native-modal#382]
## Platforms

Both

## Versions

- react-native-modal: 11.4.0
- react-native: 0.61.2
- react: 16.10.1

## Description

Simultaneous opening of modals causes unexpected freeze of one of the modals.

Example:

Have 2 buttons, click them at the same time, one of the modals will freeze and can not be opened again.

I have tried using setTimeout and InteractionManager.runAfter.. but they dont seem to work.

Help will be appreciated.

**Comment by mmazzarolo** [comment]
https://github.com/react-native-community/react-native-modal#i-cant-show-multiple-modals-one-after-another

**Comment by CoenWarmer** [comment]
I've read the documentation, and am aware of this limitation.

Just so I understand, how can https://github.com/jacklam718/react-native-modals allow the opening of multiple modals and React Native Modal (singular) cannot?
