### ISSUE TITLE
Not able to run anmation while opening or closing the modal 

### ISSUE THREAD

**Issue by hrithik2322** [react-native-community/react-native-modal#384]
here is my modal component  
 <Modal
          animationIn="slideInRight"
          animationOut="slideOutRight"
          visible={this.state.modalVisible}
          onRequestClose={() =>
            this.props.closeModal(this.state.selectedCountry)
          }>      
still when the modal is visble i dont see any animation in there .Can anyone help?

**Comment by mmazzarolo** [comment]
Hi @hrithik2322 , please follow the issue template before submitting a new issue.
