### ISSUE TITLE
No JS files fetched on install

### ISSUE THREAD

**Issue by Eddiwar** [react-native-community/react-native-modal#385]
Hi All,

I am having difficulting installing this library. After running the following
```
npm i react-native modal
```

I get a directory in node modules but only with the readme, license, and package.json. No JS files are fetched which ends up giving me module not found issues. Does anyone have some advice? 

Cheers.

**Comment by mmazzarolo** [comment]
Hey @Eddiwar , it's `npm i react-native-modal`, not `npm i react-native modal`... But I assume it was just a typo on your post. 
Have you tried from a new project, to make sure everything is working on your side?

**Comment by waqaramjad** [comment]
facing same issue

**Comment by Eddiwar** [comment]
> Hey @Eddiwar , it's `npm i react-native-modal`, not `npm i react-native modal`... But I assume it was just a typo on your post.
> Have you tried from a new project, to make sure everything is working on your side?

Hi mmazzarolo, apologies for the typo and have isolated it to be a local problem with my project setup. it installs correctly in a fresh react-native project.
