### ISSUE TITLE
How can I create a draggable resizable modal , similar to Google Drive ?

### ISSUE THREAD

**Issue by Arvi128** [react-native-community/react-native-modal#389]
![resizable-modal](https://user-images.githubusercontent.com/16080505/71895301-b6bd9080-3176-11ea-924a-be0508407685.gif)

## Ask your Question
How do I create a modal similar to this ?  Is there any way to adjust height dynamically while using swipe gestures ?

**Comment by Arvi128** [comment]
After some searching, I found out a library that solves my purpose : 
[](https://github.com/osdnk/react-native-reanimated-bottom-sheet) . However, this implementation in react-native-modal would be really helpful.

**Comment by timothystewart6** [comment]
Agreed.  I am actually using `react-native-reanimated-bottom-sheet` however was hoping `react-native-modal` supported this.

**Comment by rewieer** [comment]
I've been implementing a bottom sheet in my projects using RNM. It's possible but requires a little bit of work.

**Comment by KristineTrona** [comment]
I found this comment here very helpful on how to combine RN Modal with react-native-reanimated-bottom-sheet and create the effect you want:

https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/243#issuecomment-644091552
