### ISSUE TITLE
Have modal not take up entire viewable screen: QUESTION

### ISSUE THREAD

**Issue by fxfactorial** [react-native-community/react-native-modal#39]
Looking to use this but constrained within a limited part of the screen rather than the entire viewable screen, perhaps this is an oxymoron of using a modal? 

I've given the modal specific sizing but it ignores it and still takes up the entire UI.

**Comment by Leminur** [comment]
I am having the same problem as well!

**Comment by mmazzarolo** [comment]
Hi!
Yes, you can use it as a full screen component, you just need to override the modal's margin by applying a style with `margin: 0` to the `style` prop of the modal. 
Example:
```
const style =  StyleSheet.create({
  modal: {
    backgroundColor: 'white',
    margin: 0, // This is the important style you need to set
    alignItems: undefined,
    justifyContent: undefined,
  }

...


<Modal isVisible={true} style={styles.modal}>
  <View style={{ flex: 1 }}>
    <Text>Hello!</Text>
 </View>
</Modal>
```

let me know if it works for you :)

**Comment by Leminur** [comment]
@mmazzarolo it's working fullscreen, but we want the contrary, we want the modal to be like a windowed screen, like a second window above the first one, just like in the example images the wiki have.

margin: 0 does not change that, the margin only affects the content inside the modal.

**Comment by veb** [comment]
@Leminur can't you do:
```
  modal: {
    backgroundColor: 'white',
    margin: 15, /
    alignItems: undefined,
    justifyContent: undefined,
  }
```

![image](https://user-images.githubusercontent.com/376245/27714936-231cdda0-5d88-11e7-9908-e69627aa02ec.png)

**Comment by Leminur** [comment]
Sorry! It something else that got me there:

backdropColor = {'white'}
     backdropOpacity = {1}

I should have paid attention to that, thanks anyway!

**Comment by mmazzarolo** [comment]
Honestly the issue you were having is still unclear to me 🤔 
Glad you fixed it though, feel free to post here again if you're still in trouble on the matter.

**Comment by cauldyclark15** [comment]
Is there a way to limit the scope of backdrop? As of now, it is occupying 100% of the screen, is it possible to make it like 90%?

**Comment by Paul-Lategan** [comment]
No idea why this is so difficult to just say the modal should take up x% of the height of the screen.  It should be built into React Native.  A common use case would be for a toast notification that appears *above modals*.

**Comment by mmazzarolo** [comment]
> Is there a way to limit the scope of backdrop? As of now, it is occupying 100% of the screen, is it possible to make it like 90%?

Not possible right now. If you're interested it might be done by editing the backdrop style [here](https://github.com/react-native-community/react-native-modal/blob/5837b70f7002cfe2e005adcb041e2bbbd0c9982a/src/index.js#L470). What's the use case though? 
A modal *should always be drawn on top of all the content*, otherwise it won't be a modal.

> No idea why this is so difficult to just say the modal should take up x% of the height of the screen. It should be built into React Native. A common use case would be for a toast notification that appears above modals.

See message above.  
Currently react-native doesn't allow using multiple modals/dialog at the same time 😞   
Even if it is a known bug and not a feature it is (in my opinion) a good side effects since having multiple modals and dialog is a bad UX (again, in my opinion), especially on mobile.

**Comment by cauldyclark15** [comment]
@mmazzarolo I agree and thanks for the response, backdrop restyling is a good workaround. A use case might be rare, as I wanted to access bottom tabs to control Modal content without hiding it. Anyway thanks for the response!

**Comment by krestaino** [comment]
@cauldyclark15 I am working on an app where I want 2 buttons to still be clickable over the backdrop, just like you wanted access to your bottom tabs. Did you find a workaround for this? I've tried to manually set the height of the backdrop, but it doesn't seem to be working for me.

**Comment by cauldyclark15** [comment]
@krestaino yes, I created a submenu using `TouchableWithoutFeedback` with an empty `Text` as a child and computed height. Whenever this is tapped, it will be closed like a backdrop.



```javascript
{showSubmenu && (
    <TouchableWithoutFeedback
        onPressIn={this._onCloseSubmenu}
        onPress={this._onCloseSubmenu}
     >
       <View
          style={{
            height: deviceHeight - 60 - (deviceHeight * submenuHeight) / 100,
            width: deviceWidth,
            backgroundColor: 'transparent',
            position: 'absolute',
            left: 0,
            top: 0,
            }}
            >
              <Text> </Text>
       </View>
     </TouchableWithoutFeedback>
 )}
```

**Comment by SiddharthChoudhary** [comment]
> Hi!
> Yes, you can use it as a full screen component, you just need to override the modal's margin by applying a style with `margin: 0` to the `style` prop of the modal.
> Example:
> 
> ```js
> const styles =  StyleSheet.create({
>   modal: {
>     backgroundColor: 'white',
>     margin: 0, // This is the important style you need to set
>     alignItems: undefined,
>     justifyContent: undefined,
>   }
> 
> ...
> 
> 
> <Modal isVisible={true} style={styles.modal}>
>   <View style={{ flex: 1 }}>
>     <Text>Hello!</Text>
>  </View>
> </Modal>
> ```
> 
> let me know if it works for you :)

Dude! He is not asking to make modal appear as a full screen, that's actually the thing troubling him.

**Comment by SiddharthChoudhary** [comment]
> @Leminur can't you do:
> 
> ```
>  <Modal isVisible={this.state.visibleModal === 1} style={styles.modal}>
>   {this._renderModalContent()}
>  </Modal>
> 
>   modal: {
>     backgroundColor: 'white',
>     margin: 15, 
>     alignItems: undefined,
>     justifyContent: undefined,
>   }
> ```
> ![image](https://user-images.githubusercontent.com/376245/27714936-231cdda0-5d88-11e7-9908-e69627aa02ec.png)

How did you do it bro?

**Comment by jakebern** [comment]
This was helpful for me: https://github.com/react-native-community/react-native-modal/issues/79#issuecomment-338412126

**Comment by BenjErgizerBunny** [comment]
I've tried #79 but that hasn't worked for me.  

@Leminur Can you let us know how you fixed it?!

**Comment by BenjErgizerBunny** [comment]
I was able to solve the issue by changing the Modal prop transparent to true.  Here's the description from the documentation:

"The transparent prop determines whether your modal will fill the entire view. Setting this to true will render the modal over a transparent background."

I don't believe the modal tag accepts a style prop, I should be wrong because I'm not 100% on react-native yet but I didn't see it in the [documentation](https://facebook.github.io/react-native/docs/modal#transparent).  

```
  render(){
    return(

        <Modal

          animationType="slide"
          transparent={true}
          visible={this.state.modalVisible}


          onRequestClose={() => {
            Alert.alert('Modal has been closed.');
            console.log('Modal has been closed');
          }
        }>
          <View style={styles.modalView}>
        
          </View>
        </Modal>

    )
  }
}



const styles = StyleSheet.create({
  modalView: {
    backgroundColor: 'white',
    width: windowWidth*0.8,
    height: windowHeight*0.7,
    alignSelf: 'center',
    top: windowHeight*0.15,
    borderRadius: windowHeight*0.03,
    alignItems: 'center'
  },
```
![simulator screen shot - iphone xr - 2019-01-29 at 14 15 57](https://user-images.githubusercontent.com/33185282/51933933-7420ff00-23d0-11e9-9b23-441a5d3eb275.png)

**Comment by NachoJusticia** [comment]
@BenjErgizerBunny your example also works fine with the`react-native` original `Modal` component, thanks 👍

**Comment by eneasharrais85** [comment]
The only way I was abble to use the modal on screen and set a dim background for the components bellow was as follow:
`<Modal
          animationType="fade"
          transparent={true}
          visible={templateModalVisible}
          onRequestClose={() => {
            this.setTemplateModalVisible(!templateModalVisible);
          }}>
          <View style={local_styles.TemplateModalContainer}>
            <View style={local_styles.TemplateModalContent}>
              <Text>Hello World!</Text>

              <TouchableHighlight
                onPress={() => {
                  this.setTemplateModalVisible(!templateModalVisible);
                }}>
                <Text>Hide Modal</Text>
              </TouchableHighlight>
            </View>
          </View>
        </Modal>

  TemplateModalContainer:{
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  TemplateModalContent:{
    width: '80%',
    height: '70%',
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
  },
`

**Comment by eneasharrais85** [comment]
The only way I made it work was by using a View inside a View inside the modal:

`        <Modal
          animationType="fade"
          transparent={true}
          visible={templateModalVisible}
          onRequestClose={() => {
            this.setTemplateModalVisible(!templateModalVisible);
          }}>
          <View style={local_styles.TemplateModalContainer}>
            <View style={local_styles.TemplateModalContent}>
              <Text>Hello World!</Text>

              <TouchableHighlight
                onPress={() => {
                  this.setTemplateModalVisible(!templateModalVisible);
                }}>
                <Text>Hide Modal</Text>
              </TouchableHighlight>
            </View>
          </View>
        </Modal>`

`  TemplateModalContainer:{
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  TemplateModalContent:{
    width: '80%',
    height: '70%',
    backgroundColor: colors.grayScale0,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
  },`

**Comment by NoumanSakhawat** [comment]
> Hi!
> Yes, you can use it as a full screen component, you just need to override the modal's margin by applying a style with `margin: 0` to the `style` prop of the modal.
> Example:
> 
> ```js
> const styles =  StyleSheet.create({
>   modal: {
>     backgroundColor: 'white',
>     margin: 0, // This is the important style you need to set
>     alignItems: undefined,
>     justifyContent: undefined,
>   }
> 
> ...
> 
> 
> <Modal isVisible={true} style={styles.modal}>
>   <View style={{ flex: 1 }}>
>     <Text>Hello!</Text>
>  </View>
> </Modal>
> ```
> 
> let me know if it works for you :)

Work Perfectly for me

**Comment by amoizesmail** [comment]
> Sorry! It something else that got me there:
> 
> backdropColor = {'white'}
> backdropOpacity = {1}
> 
> I should have paid attention to that, thanks anyway!

Thanks for this.

**Comment by EhsanSarshar** [comment]
just add `margin: 0` to your modal style

**Comment by sriramkakara** [comment]
Latest version has 'coverScreen' prop, which you can set to false.

**Comment by JeremyBradshaw7** [comment]
> Latest version has 'coverScreen' prop, which you can set to false.

0.61.5? Or 0.62 release candidate?

**Comment by nssanghvi90** [comment]
> Latest version has 'coverScreen' prop, which you can set to false.
coverScreen prop worked for me

**Comment by raikk** [comment]
Yes, just add `margin: 0` to modal style

```
          <Modal 
          style={{margin: 0}} //<----------
          >

               <View style={{ height:"80%", borderTopStartRadius: 10, borderTopEndRadius: 10, backgroundColor:"white", 
                  width:"100%",marginTop:300,flex: 1 }}>
               ...
              </View>
          </Modal>
```

**Comment by MahmoudAziz1996** [comment]
I fixed that issue by adding below code
`<Modal
            backdropColor={'transparent'}
            style={{ margin: 0, backgroundColor: 'rgba(0,0,0,.6)' }}
        >`

![image](https://user-images.githubusercontent.com/49672934/106363225-f5992800-632f-11eb-8e15-fb06eab94ee0.png)

**Comment by Saujanmgr** [comment]
Guys, if its for android ... you can use the code:  statusBarTranslucent={true} in Modal.

Example:
 <Modal
      statusBarTranslucent={true}
      animationType="fade"
      transparent={false}>
</Modal>

**Comment by Jona-md** [comment]
I left here an example that works well. You must wrap the code inside the Modal component with a View and then set margin. If you wanna a set an opacity background you must use another View component and set his background color using RGBA's transparency in order to avoid use opacity that will make opaque all inside it (even your Modal's pop-up).


```js

import React, { useState } from 'react';
import { Text, View, StyleSheet, Button, Modal } from 'react-native';

export default function App() {

    const [modalVisible, setModalVisible] = useState(false);
    

    return (
        <View style={styles.container}>

            <Modal
                transparent={true}
                visible={modalVisible}
                onRequestClose={() => setModalVisible(true)}
            >
              <View  style={{ backgroundColor: 'rgba(0,0,0,0.4)', flex:1}}>
                    <View style={{ backgroundColor: 'orange', padding: 40, margin: 80}}>
                        <Text>This is a modal</Text>
                        <Button title='close'
                            onPress={() => setModalVisible(false)} />
                    </View>

                </View>
            </Modal>

            <Button
                title="Press me"
                onPress={() =>setModalVisible(true)}
            />

        </View>
    );
}


const styles = StyleSheet.create({
    container: {
        backgroundColor: 'rgb(25, 90, 90)',
        flex: 1,
    }
});




```

**Comment by TharinduNilanga** [comment]
> > Hi!
> > Yes, you can use it as a full screen component, you just need to override the modal's margin by applying a style with `margin: 0` to the `style` prop of the modal.
> > Example:
> > ```js
> > const styles =  StyleSheet.create({
> >   modal: {
> >     backgroundColor: 'white',
> >     margin: 0, // This is the important style you need to set
> >     alignItems: undefined,
> >     justifyContent: undefined,
> >   }
> > 
> > ...
> > 
> > 
> > <Modal isVisible={true} style={styles.modal}>
> >   <View style={{ flex: 1 }}>
> >     <Text>Hello!</Text>
> >  </View>
> > </Modal>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > let me know if it works for you :)
> 
> Dude! He is not asking to make modal appear as a full screen, that's actually the thing troubling him. Please don't write anything just to increase your role in the discussions here



> > Hi!
> > Yes, you can use it as a full screen component, you just need to override the modal's margin by applying a style with `margin: 0` to the `style` prop of the modal.
> > Example:
> > ```js
> > const styles =  StyleSheet.create({
> >   modal: {
> >     backgroundColor: 'white',
> >     margin: 0, // This is the important style you need to set
> >     alignItems: undefined,
> >     justifyContent: undefined,
> >   }
> > 
> > ...
> > 
> > 
> > <Modal isVisible={true} style={styles.modal}>
> >   <View style={{ flex: 1 }}>
> >     <Text>Hello!</Text>
> >  </View>
> > </Modal>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > let me know if it works for you :)
> 
> Dude! He is not asking to make modal appear as a full screen, that's actually the thing troubling him. Please don't write anything just to increase your role in the discussions here

Its working thank you

**Comment by satyakabiroffical** [comment]
The modal is not covering the entire screen
The modal style applied by default has a small margin.
If you want the modal to cover the entire screen you can easily override it this way:

```
<Modal style={{ margin: 0 }}>...</Modal>
```

**Comment by allenben746** [comment]
For those looking at this thread in current time (2024), this worked for me:
```
import Modal from "react-native-modal";
....
modalContent: {
    height: 100,
    backgroundColor: "white",
    padding: 22,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 4,
    borderColor: "rgba(0, 0, 0, 0.1)"
}
....
const [isVisible, setIsVisible] = useState(false);
....
<Modal style={{ backgroundColor: 'transparent'}} isVisible={isVisible}>
    <View style={styles.modalContent}>
        <Text>Modal text.</Text>
        <Pressable onPress={() => { setIsVisible(false) }}>
            <Text>Ok</Text>
        </Pressable>
    </View>
</Modal>
```

**Comment by fluffydonkey** [comment]
# Modal that Fills a Percentage of the Parent's Height
The use case for this is to create a modal that doesn't cover the entire screen, a design pattern commonly seen in apps like Uber Eats and Airbnb.

# Requirements
- The React Native Modal component must have the transparent prop set to true (reference: https://reactnative.dev/docs/modal#transparent)
- A child view within the Modal must have its top value set to a number representing the desired distance from the top of the screen.

# Example
In this example, the height is set to 100% so that the modal behaves like a bottom sheet with no gap between itself and the bottom of the screen. To illustrate this behavior, you can change the height to a smaller value like 40%, and you'll see the modal disconnected from the bottom of the screen.

```jsx
import { Modal, Text, View } from 'react-native'

export const MyModal = (props) => {

    return (
        <Modal visible={true} animationType="slide" transparent={true}>
            <View
                style={[
                    {
                        height: '100%',
                        top: 100
                    },
                ]}
            >
                <Text>content</Text>
            </View>
        </Modal>
    )
}

```

<img width="476" alt="Screenshot 2024-05-10 at 10 14 37 AM" src="https://github.com/react-native-modal/react-native-modal/assets/111311384/9b7f5719-dabd-43ce-a217-361c43de37f0">
