### ISSUE TITLE
Setting swipeable area instead of whole children in modal

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-modal#391]
## Ask your Question

is it currently possible to swipe (to close modal) only portion of children view within modal to close the modal? At the moment I can swipe the whole component in modal. 

What I would like to do is just make close handle so that users can only swipe by clicking on the handle only, not the whole child.

**Comment by rewieer** [comment]
Modal will show and hide given the isVisible prop. You have to handle the animation yourself and toggle the isVisible prop.

**Comment by cglacet** [comment]
Even if it's not in the plans, any idea how to have a temporary solution on the user side to modify the default behaviour?
