### ISSUE TITLE
Problem with using modal with redux

### ISSUE THREAD

**Issue by MasoudShah** [react-native-community/react-native-modal#392]
I want to show and hide modal using redux, and as a result, modal visibility depends on component props. It has a very common use case. For example I want to show modal by clicking on a flatlist Item and that modal exists in the containing list component. When I call redux function, the props get updated and the modal shows up but the transparent background doesn't get dimmed. How can I overcome this problem.

**Comment by thiagog3** [comment]
Same issue here.

**Comment by SilvioLuis** [comment]
Same here!
