### ISSUE TITLE
Modal is not opening/closing immediately

### ISSUE THREAD

**Issue by anukulRST** [react-native-community/react-native-modal#393]
I have put a calendar in a modal and the modal is opening on a click of a button, But the modal takes approx 1 second(not immediate)  to open and close(closing modal on onBackdropPress()). Animation and everything else is working fine just the modal is not opening/closing immediately. 

react-native-modal version : ^11.5.3
react-native version : 0.59.10

**Comment by mmazzarolo** [comment]
Hey @anukulRST 👋 
Could you please follow the issue template before creating a new issue? Thanks!

**Comment by mppperez** [comment]
same here - is there any other issue with this topic or is a new one still needed? interestingly it only affects specific devices. I've got 2 huawei p20 pro for testing and on one everything works as expected and at the other the modal opens and is closing immediately. Only one modal is affected... not all.

Any help would be appreciated.

**Comment by mppperez** [comment]
Ok... nvm. Bitdefender was the reason: it seems that they are closing that specific Modal... not sure why, but they do.

**Comment by DonOzOn** [comment]
same here , anyone know the what i was wrong 
```
      <Modal
                isVisible={isVisible}
                backdropTransitionOutTiming={0}
                useNativeDriver={true}
                animationOut={'fadeOut'}
                onBackdropPress={  this.backToWelcome}
                onRequestClose={() => {
                    this.backToWelcome()
                }}
                style={{ justifyContent: 'flex-end', margin: 0 }}
                onDismiss={this.back}>
```
