### ISSUE TITLE
Keyboard is pushing modal contents above the keyboard (Android)

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-modal#396]
## Platforms

Android

## Versions

- Android:
- iOS:
- react-native-modal: 11.5.3
- react-native: 0.61.5
- react: 16.9.0

## Description

Contents(children) of the Modal is pushed above the keyboard on Android. I have already applied

```
android:windowSoftInputMode="adjustPan" 
```
This issue only seems to happen to contents inside the modal, as other components behaves fine when keyboard is shown using adjustPan
 
## Reproducible Demo

![image](https://user-images.githubusercontent.com/34116285/74305156-6ef7dd80-4da2-11ea-9806-52a996e2d254.png)

The navigation bar and menu contents(except add Favorite dialog) should not be pushed above keyboard but should be underneath(not visible) the keyboard instead.

```
<Modal
        isVisible={this.props.moreShown}
        backdropColor="rgba(0,0,0,0.4)"
        onBackdropPress={() => {
          this.setState({showAddFavorite: false});
          toggleModal();
        }}
        animationInTiming={200}
        animationIn="slideInUp"
        backdropTransitionOutTiming={0}
        hideModalContentWhileAnimating
        style={styles.modalStyle}
        useNativeDriver>
        <GuideModal isVisible={showGuide} setShowGuide={this.setShowGuide} />
        <AddFavDialog
          isVisible={showAddFavorite}
          toggleDialog={this.toggleAddFavorite}
        />
        <View style={{position: 'absolute', bottom: 0, width: '100%'}}>
          <View style={styles.barContainer}>
             <MenuContents/>
          </View>
          <DummyNavBar toggleModal={this.props.toggleModal} />
        </View>
      </Modal>
    );
  }
}
```

My guess is that 'android:windowSoftInputMode="adjustPan" ' is not affecting the contents that are inside RN modal component.

**Comment by SergAlexAnd** [comment]
@panda0603 Do you solve this issue?

**Comment by engrwaqasali** [comment]
still Facing issue in android with `android:windowSoftInputMode="adjustPan" `
