### ISSUE TITLE
Visual bug when closing the modal

### ISSUE THREAD

**Issue by acerbastimur** [react-native-community/react-native-modal#398]
When closing the modal, it hangs for a second on Android devices.
![74217309-26fc8c00-4cb8-11ea-9a3d-fac3fee445de](https://user-images.githubusercontent.com/33218120/74330380-a23a6c80-4da2-11ea-95a4-f52f384590f2.gif)

## My code:
```javascript
 <Modal
          isVisible={WinModalStore.isWinPrizeModalOpened}
          swipeDirection={['down']}
          hardwareAccelerated
          swipeThreshold={200}
          hasBackdrop
          propagateSwipe
          backdropOpacity={0.1}
          animationOut="slideOutDown"
          animationOutTiming={350}
          onBackdropPress={() => {
            WinModalStore.isWinPrizeModalOpened = false;
          }}
          // eslint-disable-next-line react-native/no-inline-styles
          style={{
            margin: 0,
          }}
          onSwipeComplete={() => {
            WinModalStore.isWinPrizeModalOpened = false;
          }}>
          <WinPrize navigation={navigation} />
        </Modal>
````
## Environment
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 481.56 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 28, 29
      Build Tools: 23.0.1, 23.0.2, 25.0.1, 26.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Platforms

Android

## Versions

 "react-native-modal": "^11.5.3"

**Comment by AndresMaya13** [comment]
Try using useNativeDriver in "true", works for me.
