### ISSUE TITLE
Backdrop does not appear when modal appears

### ISSUE THREAD

**Issue by AngeloGiurano** [react-native-community/react-native-modal#399]
## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 989.82 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8

## Platforms

Both

## Versions

- Android: 8.0.0
- iOS: 13.3
- react-native-modal: 11.5.1
- react-native: 0.59.8
- react: 16.8.3

## Description

The backdrop does not appear as soon as the modal appears, it appears just after touching the modal

## Reproducible Demo

 ```
const ConfirmationModal = ({ onCancel, onConfirm, visible, title, description }) => (
  <Modal
    animationType="slide"
    visible={visible}
    backdropColor="black"
    backdropOpacity={0.5}
    swipeDirection="down"
    transparent
  >
    <View style={styles.main}>
      <Text style={styles.title}>{title}</Text>
      <Text style={styles.description}>{description}</Text>
      <View style={styles.actions}>
        <Button
          onPress={onCancel}
          containerStyle={styles.cancelButton}
          textStyle={styles.cancelButtonText}
        >
          Cancel
        </Button>
        <Button
          onPress={onConfirm}
          containerStyle={styles.confirmButton}
          textStyle={styles.confirmButtonText}
        >
          Confirm
        </Button>
      </View>
    </View>
  </Modal>
)
```

![modal-backdrop](https://user-images.githubusercontent.com/6850571/74428248-ed16bb80-4e58-11ea-9e2a-eeb617b0422a.gif)

**Comment by llaneiro** [comment]
same here, any updates?

**Comment by rewieer** [comment]
The props `visible` is wrong, it's `isVisible`.
Because all the props are passed to the actual modal, it will be shown, but the backdrop wont load.

**Comment by AngeloGiurano** [comment]
Thank you, that actually was the issue 🤦‍♂

**Comment by isimple4** [comment]
Thanks for the info! Came from the official Modal, but also didn't notice the difference.

**Comment by Vasault** [comment]
thank you so much, so many days without a solution and it was a typo
