### ISSUE TITLE
black screen on Android

### ISSUE THREAD

**Issue by yash2code** [react-native-community/react-native-modal#40]
using it with flatlist

```javascript

 <Card 
                    containerStyle={{borderColor: 'transparent'}}>

                    <ListItem
                      badge={{ value: 3, badgeTextStyle: { color: 'red' }, badgeContainerStyle: { marginTop: 10, color:'orange' } }}
                      roundAvatar
                      title={`${item.name.first} ${item.name.last}`}
                      subtitle={item.email}
                      avatar={
                        <TouchableOpacity onPress ={ () => this._showModal()  }>
                        <Avatar
                        medium
                       // onPress ={ () => this._showModal()  }
                        rounded
                        source={{ uri: item.picture.thumbnail }} 
                      // style={{borderRadius:25, height:50, width:50 }}
                         />
                         </TouchableOpacity>
                             }
                    
                      containerStyle={{borderBottomWidth: 0, padding:0 }}
                    />
                    <Modal isVisible={this.state.isModalVisible}>
                      <View>
                        <Text>Hello!</Text>
                      </View>
                   </Modal>
                   
      </Card>

```

**Comment by mmazzarolo** [comment]
What is your `ListItem`in the snippet?  
Could you provide an example repo or a more detailed example? Thanks.

**Comment by mmazzarolo** [comment]
Closing, feel free to create a new issue if needed 👍

Also, please be aware that I created the following "new issue template" that, if followed correctly, will speed up a lot the issue resolution:

---

### When reporting a bug, please be sure to check if the issue still persists with react-native original modal:
Under the hood `react-native-modal` uses react-native original [Modal component](https://facebook.github.io/react-native/docs/modal.html).  
Before reporting a bug, try swapping `react-native-modal` with react-native original Modal component to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior


### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

### Please note by far the quickest way to get a new feature is to file a Pull Request.

**Comment by yash2code** [comment]
sure , will be on it soon :) Tnx for response!

**Comment by PramodVemulapalli** [comment]
I ran into a similar issue and thought this might help you. The backdropOpacity parameter which is defaulted to 0.7 seems to create drastically different background transparencies for Android and Ios. 
I ended up fixing it by using a platform specific parameter as shown below. 
`
<View>
        <Modal
          isVisible={this.props.error != ''}
          animationIn={'slideInLeft'}
          animationOut={'slideOutRight'}
          style={styles.bottomModal}
          backdropOpacity={Platform.OS === 'android'? 0.5 : 0.7}
        >
          {this.renderModalContent()}
        </Modal>
      </View>
`

**Comment by roblingle** [comment]
Thanks @PramodVemulapalli. I had to use 0.1 for Android.

**Comment by mmazzarolo** [comment]
Thanks @PramodVemulapalli, but I guess it might be device-specific 🤔
