### ISSUE TITLE
Modal View resizes automatically when keyboard opens (Android)

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-modal#402]
## Platforms

Android

## Versions

- react-native-modal: 11.5.3
- react-native: 0.61.5
- react: 16.9.0

## Description

I'm using Modal component, which contains multiple views as child. The View has some TextInput elements. When the keyboard pops up, the modal view resizes to fit into the remaining space above the keyboard, and reverts back when keyboard closes(checked by giving borderWidth), but I don't want the Modal to resize when keyboard opens.

This does not happen for IOS. And also, it does not happen in non-modal Views for Android.

I have windowSoftInputMode="adjustPan" set in my android Manifest, but it doesn't seem to be applied on the Modal.

Tried applying fixed height to the Modal, and full screen height to modal's child view as well, but doesn't work

## Reproducible Demo

TextInput within a modal.

Before keyboard pops:
![image](https://user-images.githubusercontent.com/34116285/74607422-3185ae00-511c-11ea-814a-7999ad9b9980.png)

After keyboard pops:
![image](https://user-images.githubusercontent.com/34116285/74607430-39455280-511c-11ea-9238-a54352fabada.png)

notice how the view indicated by red border resizes as keyboard pops.

**Comment by panda0603** [comment]
so this is not a bug but intended?

**Comment by rewieer** [comment]
@panda0603 I believe this is related to the way react-native layout views, so this is more related to styling and, in general, react-native itself.

**Comment by ajaysaini-sgvu** [comment]
@panda0603 How did you resolve this ?
