### ISSUE TITLE
Random crash on android

### ISSUE THREAD

**Issue by tankpower1** [react-native-community/react-native-modal#404]
##Platforms

Android

## Versions

- Android: 28
- react-native-modal: 11.5.3
- react-native: 0.61.5
- react: 16.12.0

## Description

Randomly when opening/closing a modal crashes the app only on android devices.

**Comment by callaars** [comment]
@mmazzarolo I experience this as well. Consistently to be honest. What do you need from me to debug this?

**Comment by michaelVictoriaDev** [comment]
Why is this closed ? still get the same error.

**Comment by rewieer** [comment]
We lack stacktrace and contextual information about the error. Please provide a reproducible repository so we can fix it :)

**Comment by michaelVictoriaDev** [comment]
I solved the issue, I try to comment each View of my modal, The app crash due of justifycontent: left is null, I hope some developers help this.

**Comment by rewieer** [comment]
`justifycontent`isn't a valid property.

**Comment by michaelVictoriaDev** [comment]
Hi @rewieer sorry for confusion here some snippet

I try to comment of each  VIEW to see why is the app crash, and then i found out that `justifyContent: 'left'` is null,

there's no logs or error logs only app crash that's why it's hard to find.

  ```
   <Modal isVisible={this.state.showModalLost}
    backdropColor={'rgba(0,0,0,.4)'}
    onBackdropPress={() => {
        this.setState({
            showModalLost: false
        })
    }}
>


    <View style={{ backgroundColor: colors.WHITE }}>
        <View style={{ flexDirection: 'row', backgroundColor: colors.PRIMARY_COLOR, height: 40, justifyContent: 'left', alignItems: 'center', paddingHorizontal: 14 }}>
            <View><Text style={{ color: colors.WHITE }}>Mark as Lost</Text></View>
        </View>
    </View>

</Modal>
```
