### ISSUE TITLE
move from react-native-animatable to react-native-reanimated

### ISSUE THREAD

**Issue by magickasoft** [react-native-community/react-native-modal#405]
## Ask your Question
we expect a transfer to more flexible animation mechanisms

**Comment by vamshi9666** [comment]
I made a similar component , which i am planning to publish soon. [link to source code](https://github.com/vamshi9666/reanimated-ui/tree/reanimated-modal)

**Comment by rewieer** [comment]
Reanimated is a library that uses native dependencies. As of now RNM doesn't impose any native dependency to its users, so we cannot use it.

**Comment by magickasoft** [comment]
@rewieer check this 
https://github.com/react-native-community/react-native-modal/blob/master/package.json#L51

**Comment by rewieer** [comment]
@magickasoft care to elaborate on what i'm supposed to check ?
