### ISSUE TITLE
Modal wrapped by TouchableWithoutFeedback not working

### ISSUE THREAD

**Issue by EhsanSarshar** [react-native-community/react-native-modal#407]
I am trying to dismiss the keyboard when someone tap on the modal. but the TouchableWithoutFeedback onPress not trigger.

`<TouchableWithoutFeedback  onPress={dismiss}><Modal /></TouchableWithoutFeedback>`

**Comment by zcramos** [comment]
The touchable should be inside the modal, not the other way around.
