### ISSUE TITLE
How to do fade in fade out animation?

### ISSUE THREAD

**Issue by JuniusAng** [react-native-community/react-native-modal#41]
Hi, any idea to better fade in and fade out? i didn't find the reference for fade animation so now we are currently modified the animations.js with fadeIn and fadeOut entry that modify opacity props like this

```
function makeFadeTransition(transitionType, fromValue, toValue){
  return {
    from: {
      [transitionType]: fromValue,
    },
    to: {
      [transitionType]: toValue,
    },
  };
}
export const fadeIn = makeFadeTransition('opacity', 0, 1);

export const fadeOut = makeFadeTransition('opacity', 1, 0);
```

**Comment by mmazzarolo** [comment]
Hi @JuniusAng 
isn't setting this enough?
```javascript
animationIn={'fadeIn'}
animationOut={'fadeOut'}
```

**Comment by JuniusAng** [comment]
so actually we do not need to add another entry manually? my bad, i should tried to do that in different way before submitting an issue.

**Comment by mmazzarolo** [comment]
No worries man, glad it works.
You can take a look at [react-native-animatable](https://github.com/oblador/react-native-animatable) for all the available animations (it was at the bottom of the README.md).

**Comment by buddhiv** [comment]
> Hi @JuniusAng
> isn't setting this enough?
> 
> ```js
> animationIn={'fadeIn'}
> animationOut={'fadeOut'}
> ```

It works, even though the documentation of react-native-modal or in the code we can't find it. I think anything from react-native-animatable works since they have used that. I went through some.
