### ISSUE TITLE
Warning `useNativeDriver` & Animated.event second argument - 0.62.0-rc-5

### ISSUE THREAD

**Issue by dsznajder** [react-native-community/react-native-modal#410]
## Environment

- Not related

## Platforms

- Android & iOS

## Versions

- Android: 29.0.2
- iOS: 13.3
- react-native-modal: 11.5.4
- react-native: 0.62.0-rc.5
- react: 16.11.0

## Description

With `swipeDirection="down"` when modal is closed with swipe on release candidate for RN (tested on 0.62.0-rc.5, but most likely will happen on every 62 rc) console shows warnings as `Animated` now requires `useNativeDriver` param to be defined. Additionally, `Animated.event` now requires a second argument for options:

- [Animated.event lines](https://github.com/react-native-community/react-native-modal/blob/master/src/modal.tsx#L483)
Screen:
<img width="639" alt="Screenshot 2020-03-08 at 13 10 59" src="https://user-images.githubusercontent.com/17621507/76162566-2d5b1800-613f-11ea-8822-5074b42a6f12.png">

- 1. [Animated lines](https://github.com/react-native-community/react-native-modal/blob/master/src/modal.tsx#L420)

<img width="639" alt="Screenshot 2020-03-08 at 13 10 59" src="https://user-images.githubusercontent.com/17621507/76162644-d7d33b00-613f-11ea-864d-4fa141043a9a.png">

[Commit which added this to RN](https://github.com/facebook/react-native/commit/5876052615f4858ed5fc32fa3da9b64695974238)

**Comment by rewieer** [comment]
@dsznajder has it been fixed in the latest RNM version ? I think I saw a patch about that

**Comment by BogdanRad** [comment]
I have same error on 11.6.1.....
![image](https://user-images.githubusercontent.com/40359109/105142571-6dcb4680-5b03-11eb-86fa-2f795ca682d1.png)
 how can I fix this problem?

**Comment by danieltereschenko** [comment]
if you okay with not using native driver
react-native-modal/src/index.js ->
![image](https://user-images.githubusercontent.com/37038091/111337206-f3dcb700-8686-11eb-96a1-8e31cfe76e19.png)
![image](https://user-images.githubusercontent.com/37038091/111337262-ffc87900-8686-11eb-9100-58c788de3fdf.png)

just checked it's fixed in 11.7.0 version
