### ISSUE TITLE
Is there a presentationStyle pageSheet avilable or something similar?

### ISSUE THREAD

**Issue by levelingup** [react-native-community/react-native-modal#421]
I tried adding presentationStyle="pageSheet" to this modal, but I get a warning message:

"Modal with 'pageSheet' presentation style and 'transparent' value is not supported"

Is there something similar to having a pageSheet like modal with this package? When I activate my modal with pageSheet, it kind of has a similar pageSheet like the react-native package but doesn't seem to be functioning correctly.

**Comment by levelingup** [comment]
I found out that I needed to set transparent={false}

**Comment by carissacks** [comment]
Hi do you mind telling where I need to set the transparent value? I'm facing the same issue. 
Thank you!

**Comment by dalmargarido** [comment]
It's probably too late but it's a prop, even though it doesn't show up in the documentation
