### ISSUE TITLE
keyboad  move make button not catch  event

### ISSUE THREAD

**Issue by hxzAugustinus** [react-native-community/react-native-modal#427]
## Versions

- Android:  yes
- iOS:
- react-native-modal: ^11.5.6
- react-native:  0.61.5 => 0.61.5
- react:  16.9.0 => 16.9.0

## Description

```
 <Modal
 isVisible={this.props.isModalShow}
 onBackdropPress={this.onBackdropPress}
avoidKeyboard={true}>
    <TextInput  onBlur={() => console.info('blur')}
              onChangeText={text => {
                this.setState({val: text});
              }}
             value={this.state.val }
            />
      <TouchableOpacity
                onPress={() => { console.info('send');  }} >
                <Text >send</Text>
         </TouchableOpacity>
</Modal>

```
on  simulator,  
1. foucs textInput ;
2. press  the  TouchableOpacity  (and  the  keyboard is closing ) ;
3. it always  output  'blur' , not output  'send' ；

on  Real machine:
it  will  output  'send' ;

**Comment by kyle-ssg** [comment]
@hxzAugustinus did you find a way to resolve this?
