### ISSUE TITLE
Modal won't reach bottom of the screen (Android)

### ISSUE THREAD

**Issue by AdamGerthel** [react-native-community/react-native-modal#433]
## Environment

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz
    Memory: 53.72 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.4 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-app-id: 0.0.5
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1

## Platforms

Android

## Versions

- Android: 6.0.1
- react-native-modal: 11.5.6
- react-native: 0.61.4
- react: 16.9.0

## Description

I'm using [Immersive Mode](https://developer.android.com/training/system-ui/immersive#immersive) in my app, using [react-native-immersive-mode](https://github.com/jayli3n/react-native-android-immersive-mode) to enter it. Using Immersive Mode means that the navigation bar is hidden and can be re-introduced to the screen by swiping up from the bottom. When in Immersive Mode, the UI on the device behaves much like when Gesture Navigation (available in > Android 10) is enabled.

The problem is that the bottom part of the screen, where the navigation bar would normally appear, is _never_ filled by the modal. There are two known issues related to this in the readme:

 - [The backdrop is not completely filled/covered on some Android devices](https://github.com/react-native-community/react-native-modal#the-backdrop-is-not-completely-filledcovered-on-some-android-devices-galaxy-for-one)
- [The modal is not covering the entire screen](https://github.com/react-native-community/react-native-modal#the-modal-is-not-covering-the-entire-screen)

But neither of those solutions matter in my case. I can set `deviceHeight` to whatever high value (or use screen size for that matter), but the modal still refuses to fill the entire height of the screen.

The description for `deviceHeight` states 

> Device height (useful on devices that can hide the navigation bar)

But that doesn't seem to be the case for me.

![Screenshot_20200517-225125](https://user-images.githubusercontent.com/1490370/82159895-e6517780-9891-11ea-8164-eac92cd95a08.png)

## Reproducible Demo

The code below is what I'm doing in the specific modal shown in the screenshot, but this applies to all modals in my application.
```
<Modal
  style={{ margin: 0 }}
  deviceHeight={2000} // This is just a sample value which is much higher than the actual screen height. I've tried all kinds of values to no avail.
  backdropOpacity={0.8}
  backdropColor={'#000000'}
  isVisible={screen === 'credits'}>
  <Text style={{ color: 'white' }}>Hello!</Text>
</Modal>
```

**Comment by AdamGerthel** [comment]
Update: I managed to reproduce the problem using Modal from react-native so the problem is not with react-native-modal. Closing here, will reference this from a new issue in React Native's issue queue.

**Comment by jimtang9527** [comment]
```javascript
        <Modal visible={this.state.showBigImage} statusBarTranslucent backdropColor={'#fff'} style={{ margin: 0, flex: 1 }}>
         <ImageViewer
                    index={selectedIndex}
                    imageUrls={images}
                    menuContext={{ saveToLocal: 'Save', cancel: 'Cancel' }}
                    onSave={(url) => { this._saveImage(url) }}
                    onClick={() => { this.setState({ showBigImage: false }) }}
                />
</Modal>
```
![image](https://user-images.githubusercontent.com/7098183/86073454-5882c200-bab6-11ea-89dd-22429da6b45c.png)
