### ISSUE TITLE
How to set the position of the animation start point

### ISSUE THREAD

**Issue by eraldoforgoli** [react-native-community/react-native-modal#436]
Hello, i would like to ask if there is a way to specify the start point of the modal animation start.
As far as i know, the modal pops from the top, bottom, left, right or center.
Is there a way to specify the position from where the modal is going to pop or scroll ?

In my case, i want the modal to be shown below the header (currenty, the modal pops up by scrolling from the top using this code: `
<Modal
      isVisible={isVisible}
      onBackdropPress={() => setIsVisible(false)}
      onSwipeComplete={() => setIsVisible(false)}
      swipeDirection="up"
      animationIn="slideInDown"
      animationOut="slideOutUp" ...`

![image](https://user-images.githubusercontent.com/24622515/83027151-11755d00-a030-11ea-815c-0692420b96f0.png)

**Comment by fadhilmi** [comment]
hey, do you found the solution to this?
