### ISSUE TITLE
Modal Behind Header

### ISSUE THREAD

**Issue by burhanahmed92** [react-native-community/react-native-modal#440]
## Environment

Expo SDK 37.0.0

## Platforms

Expo both Android/iOS

## Versions

- Android: 10
- iOS: 13.5
- react-native-modal:11.5.5
- react-native:0.62
- react:16.9.0

## Description

Modal is appearing over the header. I want modal to be behind the header. I am using native base I tried elevation & zIndex style properties on both modal and header but it is not working.
Is zIndex supported with modal. I just want it to appear behind of Header

**Comment by AxelHgt** [comment]
Same issue here,
it appears when "coverScreen" = false and an Animated View has zIndex or elevation

**Comment by mmazzarolo** [comment]
Please follow the issue template, thanks! :)

**Comment by frodoe7** [comment]
I have the same issue
if you reached to any solution , share it please
