### ISSUE TITLE
Backdrop doesn't cover Android navigation bar at the bottom

### ISSUE THREAD

**Issue by deckyfx** [react-native-community/react-native-modal#442]
As the title said, if I hide the navigation bar at the bottom of the Android device, the Modal backdrop is clipped and fail to cover the entire screen

<img width="884" alt="Screen Shot 2020-06-03 at 08 30 38" src="https://user-images.githubusercontent.com/1076192/83585620-85ee5580-a574-11ea-82c6-cd914673f116.png">

**Comment by IkaroAlef** [comment]
I fixed it by doing this:
```
import {  Dimensions } from 'react-native';
const deviceHeight = Dimensions.get('screen').height;
...
<Modal deviceHeight={deviceHeight} >
```

**Comment by houssston** [comment]
I had same problem. I just put this `statusBarTranslucent` 


```
<Modal
  isVisible={isModal}
  backdropOpacity={0.5}
  backdropColor="black"
  animationIn="fadeIn"
  animationOut="fadeOut"
  statusBarTranslucent
>
</Modal>
```


Let me know if it worked for you!

**Comment by mmazzarolo** [comment]
Thanks @houssston and @IkaroAlef  :)

**Comment by Wei102193** [comment]
I got the similar issue after upgrading EXPO SDK to the latest 39. 
I found out two main problems that cause this issue are:
1.width and height of Dimensions from react-native are not switching when rotating screen on android.(use useWindowDimensions instead)
2.I have android status bar hidden.(if you have status bar hidden too, top one and bottom one)
My solution: add these to Modal:     
deviceWidth={Platform.OS === "ios" ? useWindowDimensions().width : useWindowDimensions().width + StatusBar.currentHeight * 2}
deviceHeight={Platform.OS === "ios" ? useWindowDimensions().height : useWindowDimensions().height + StatusBar.currentHeight * 2}
Hope this help someone :D

**Comment by alainib** [comment]
i had to make a mix of solution to let Modal cover statusbar and take full height over Tab.Navigator on Android

```

import {getStatusBarHeight} from 'react-native-safearea-height';
const {width: windowWidth, height: windowHeight} = Dimensions.get('window');


  <ModalWrapper
      deviceHeight={windowHeight + STATUS_BAR_HEIGHT}
      statusBarTranslucent
      backdropOpacity={backdropOpacity}
      onBackdropPress={onHide}
      animationIn={'slideInDown'}
      animationOut={'slideOutUp'}
      isVisible={isVisible}>
 </ModalWrapper>
 
 
 const ModalWrapper = styled(Modal)`
  margin-horizontal: 0px;
  margin-vertical: 0px;
  width: ${windowWidth}px;
  height: ${windowHeight + STATUS_BAR_HEIGHT}px;
`;
 
 
 
```

**Comment by manglesh-0605** [comment]
Hello Everyone, I am facing the same problem, Not able to hide the bottom navigation bar when the modal is open in Android. 

Emulator
: Android version 13

    "react": "^18.2.0",
    "react-native": "^0.73.0",
   "react-native-immersive": "^2.0.0",
   "react-native-modal": "^13.0.1",
    "react-native-system-navigation-bar": "^2.6.3",

![Screenshot_1726095976](https://github.com/user-attachments/assets/312afa26-a1c0-444d-a9b7-4163486ff2cd)

**Comment by dhavalbhuva** [comment]
@manglesh-0605 Did you get the solution to this issue?

**Comment by cbdeveloper** [comment]
My issue was probably related to some `SafeAreaView` conflict.

For now, I've fixed with:

```
const insets = useSafeAreaInsets();
const extraHeight = Platform.OS === 'android' ? insets.top : 0;
return (
  <Modal
    isVisible={isOpen}
    statusBarTranslucent
    deviceHeight={DEVICE_HEIGHT + extraHeight}
  >
);
```

**Comment by timoisalive** [comment]
We are trying to integrate edge-to-edge support, but I don't seem to be able to extend the modal to cover the Android navigation bar. Status bar gets covered with `statusBarTranslucent` prop, but `deviceHeight` doesn't help in covering the nav bar, no matter how much is the value. My screens are flowing below the nav bar as expected. Any idea what could be wrong?

```
    <Modal
      deviceHeight={Dimensions.get('screen').height + 1000}
      isVisible={true}
      statusBarTranslucent
    >
      <View
        style={{
          backgroundColor: 'yellow',
          flex: 1,
          width: 100,
        }}
      />
    </Modal>
```

**Comment by iqorlobanov** [comment]
> We are trying to integrate edge-to-edge support, but I don't seem to be able to extend the modal to cover the Android navigation bar. Status bar gets covered with `statusBarTranslucent` prop, but `deviceHeight` doesn't help in covering the nav bar, no matter how much is the value. My screens are flowing below the nav bar as expected. Any idea what could be wrong?

Same issue. It works as expected only on Android 15+
