### ISSUE TITLE
State updates causing new animation In

### ISSUE THREAD

**Issue by Aryk** [react-native-community/react-native-modal#448]
I'm having this issue where when the state updates and the screen re-renders, it causes the modal to animate in again.

However, the isVisible state did not change and it stayed on true.

Do I need to wrap the component in some kind of useMemo or useCallback? I searched the issues and could not find a similar problem.

Any advice or pointers would be much appreciated!

![demo1](https://user-images.githubusercontent.com/525212/84557034-35bf8200-ad30-11ea-9fce-32bb4feadb22.gif)

**Comment by Aryk** [comment]
Nevermind, I got it to work using useCallback

**Comment by NickRance** [comment]
Hi @Aryk. I'm curious what your implementation was to stop the modal from animating in again. Thanks

**Comment by Aryk** [comment]
Hey @NickRance can you share your code and let me see if i can help!

**Comment by NickRance** [comment]
> Hey @NickRance can you share your code and let me see if i can help!

Thanks so much @Aryk ! I put a gif of the issue as well as a code fragment [here](https://drive.google.com/drive/folders/1WZP6jrBuyVjQMPa9uc6MBM5IqI5BJfht?usp=sharing).

I really appreciate it and I'm happy to provide any additional info

**Comment by Aryk** [comment]
@NickRance  Any chance I can see the whole component? Just want to see where the isVisible is stored and how that gets updated. 

Also do you have any recommendations for Lottie Designer? :)

**Comment by NickRance** [comment]
I added the link to the whole component [here](https://drive.google.com/file/d/1wZI5xb4R6ZLdGe5bK4ORSyQCgvwOq1Ro/view?usp=sharing) -- you can see all three files in the directory above.

isVisible is a standard state variable passed to the modal via props.

Thanks so much for your help!

-Nick

P.S. No idea haha, I'm only recently familiarizing myself with the technology :smile:

**Comment by Aryk** [comment]
I dont see the three files...only one...

**Comment by NickRance** [comment]
> I dont see the three files...only one...

Sorry I meant [this](https://drive.google.com/drive/folders/1WZP6jrBuyVjQMPa9uc6MBM5IqI5BJfht) link

**Comment by Aryk** [comment]
Modal component I need to see what it is inside..is that component memoized? in an observer? you aren't showing the whole thing. Need to see it all.

**Comment by NickRance** [comment]
I updated the directory to contain the whole files. 

Modal is the react-native-modal component

```
import Modal from "react-native-modal"
```

The component is not memoized or in an observer
