### ISSUE TITLE
What's the difference between this and RN's Modal

### ISSUE THREAD

**Issue by lslvxy** [react-native-community/react-native-modal#45]
react-native also have a `Modal`  Component,what is the  difference?

**Comment by mmazzarolo** [comment]
Under the hood `react-native-modal` uses react-native own's `Modal`.  
`react-native-modal` aims at expanding the `Modal` component by adding animations and styles customization options while still trying to provide a super-simple API.  

A requested feature much discussed [here](https://github.com/react-native-community/react-native-modal/issues/11) is adding a "touch outside to close" feature, but we're still thinking on the best way to achieve it.

**Comment by mmazzarolo** [comment]
I closed the issue but I'll re-open it if needed :) 
Let me know if you need any more info on the subject!

**Comment by sheshbabu** [comment]
@mmazzarolo Thanks for the explanation! It's very helpful for people new to RN. Is it possible to add this to readme?

**Comment by mmazzarolo** [comment]
Done @sheshbabu !

**Comment by sheshbabu** [comment]
That was pretty quick, thanks! 👍

**Comment by lslvxy** [comment]
👍👍
