### ISSUE TITLE
Stacking modals

### ISSUE THREAD

**Issue by KristineTrona** [react-native-community/react-native-modal#464]
## Ask your Question

Hi, I am looking for a way to call a new modal from within a modal and give it a stack kind of feel (like the presentationStyle "pagesheet" modal only with adjustable height), something that would look like this:

<img width="277" alt="Screenshot 2020-07-22 at 12 11 31 2" src="https://user-images.githubusercontent.com/39855778/88387293-74763c80-cdb2-11ea-8cf5-9d2db0eb6f9e.png">

Any tips/tricks on how to achieve this?

There is an app called Bunch that also has such an effect:

![WOvTpG3A](https://user-images.githubusercontent.com/39855778/88395973-2832f880-cdc2-11ea-9a86-99cb8f6b46b6.jpeg)

**Comment by mmazzarolo** [comment]
@KristineTrona unfortunately that's not possible with react-native-modal for now, because this stacking is not yet supported by the RN's own native modal :/

**Comment by mmckinley8** [comment]
It can be done, you just have to trigger the subsequent modal from the previous modal...there are some things to be careful of that, such as closing the parent modal from the child whenever you have to navigate to a new screen
