### ISSUE TITLE
Closing the modal by tapping outside it's parent component

### ISSUE THREAD

**Issue by petkovv** [react-native-community/react-native-modal#465]
Hi everyone. It is really urgent so I will be very happy and thankful if someone can answer me. And my apologise if it has already been answered. So the problem is that I can't close the modal by clicking outside of its parent component. It is closing if I only tap inside the parent component. I am using onBackdropPress but it only helps me to close the modal if I tap inside it's parent component. So any suggestions or something why it should be. I am not attaching any code because I think it probably is not necessary but if it is I will. Thanks in advance :)

**Comment by Knurenko** [comment]
Guys you have this prop for it.
coverScreen | bool | true | Will use RN Modal component to cover the entire screen wherever the modal is mounted in the component hierarchy.

I mean if @petkovv is right and modal cannot be closed by clicking outside its parent component it's bug.

**Comment by mmazzarolo** [comment]
thanks @Knurenko :)
