### ISSUE TITLE
backdrop android full width bug after change orientation

### ISSUE THREAD

**Issue by maystrenkoYurii** [react-native-community/react-native-modal#472]
backdrop android full width bug after change orientation v11.5.6
![Screenshot_2020-08-12-10-50-03-265_com clientpanel](https://user-images.githubusercontent.com/23016311/89989479-ada31d80-dc89-11ea-807b-4520a8cfeb42.jpg)

**Comment by mmazzarolo** [comment]
Please follow the issue template, thanks! :)
