### ISSUE TITLE
[Android] Modal can't cover screen when entering immersive/fullscreen mode Android

### ISSUE THREAD

**Issue by dangkhoa2708** [react-native-community/react-native-modal#473]
Thanks for your package, but I'm experiencing this issue when using immersive/fullscreen mode Android
When I hide status bar & navigation bar on Android, I can't manage to make the Modal cover fullscreen, see images below
It seems to be drawn underneath, any workaround to fix it ? Removing View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN, View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION fixes it. But I need these lines.
![Screenshot_1598513041](https://user-images.githubusercontent.com/20517762/91411096-12f23380-e872-11ea-919f-97fd84d23b25.png)
<img width="860" alt="Screen Shot 2020-08-27 at 14 24 26" src="https://user-images.githubusercontent.com/20517762/91411116-1a194180-e872-11ea-9a7c-570eba30fc93.png">

**Comment by komandoros** [comment]
Hey, @dangkhoa2708 
Did you tried [react-native-portalize](https://github.com/jeremybarbet/react-native-portalize)?

**Comment by IkaroAlef** [comment]
#442  Did you see this issue?

**Comment by mmazzarolo** [comment]
Thanks @IkaroAlef :)
