### ISSUE TITLE
Animation is so LAG

### ISSUE THREAD

**Issue by HoaiHuynh** [react-native-community/react-native-modal#480]
I have installed react-native-modal in my project, and when I use it, the AnimationIn an AnimationOut is so lag. my React version is 0.63. Does anyone have the same issue? Here is my package.json
"@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/datetimepicker": "^3.0.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/picker": "^1.6.6",
    "@react-native-community/segmented-control": "^2.1.1",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/material-top-tabs": "^5.2.16",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "axios": "^0.19.2",
    "moment": "^2.27.0",
    "native-base": "^2.13.13",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-calendar-strip": "^2.0.9",
    "react-native-calendars": "^1.313.0",
    "react-native-dialog": "^5.6.0",
    "react-native-fbsdk": "^2.0.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-google-signin": "^2.1.1",
    "react-native-image-picker": "^2.3.3",
    "react-native-modal": "^11.5.6",
    "react-native-modalize": "^2.0.6",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^1.13.0",
    "react-native-responsive-fontsize": "^0.4.3",
    "react-native-safe-area-context": "^3.1.1",
    "react-native-screens": "^2.9.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-tab-view": "^2.15.1",
    "react-native-vector-icons": "^7.0.0",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "reselect": "^4.0.0"

**Comment by BryanEnid** [comment]
Yes. I have the same animation bug. Every time "animationOut" fires, right away the backdrop flashes.

[![Video of the visual bug](https://user-images.githubusercontent.com/30734480/92868446-b9404c00-f3cf-11ea-93a5-cb2093f2df32.png)](https://youtu.be/6w5Ih6cRAwo "Click to Watch!")

**Comment by BryanEnid** [comment]
try setting backdropTransitionOutTiming={0} and hideModalContentWhileAnimating={true}

**Comment by HoaiHuynh** [comment]
> Try setting backdropTransitionOutTiming={0} and hideModalContentWhileAnimating={true}

I tried, but I think the problem is I use React Native 0.63, and the library Reanimated is better than Animated.

**Comment by mmazzarolo** [comment]
Please follow the issue template, thanks! :)
