### ISSUE TITLE
the modal will cover navigation

### ISSUE THREAD

**Issue by onfuns** [react-native-community/react-native-modal#49]
hi,when i use modal with react-navigation,the modal will cover navigation,how can i set the modal's layer

**Comment by gianpieroc** [comment]
@onfuns Hello!!.. do you have any conclusion? I'm facing a similar issue with react-navigation

**Comment by phbn** [comment]
Why was this closed? Facing this exact issue right now.

**Comment by mmazzarolo** [comment]
@phbn a "modal", by definition, will cover the entire app screen. See the latest comments on #39
