### ISSUE TITLE
Executing function when showing or hiding modal as soon as possible

### ISSUE THREAD

**Issue by alexkuc** [react-native-community/react-native-modal#53]
Currently, there is onModalShow and onModalHide that allows to execute function. One of their downsides is that they execute passed function once the animation finishes. This makes it difficult to create synchronous animation.

Here's example below:
![onmodalhide](https://user-images.githubusercontent.com/3331946/29252386-9ccc7dda-8098-11e7-81cc-d00cf520e501.gif)

The plus button changes colour _after_ the modal is hidden. In my opinion, this doesn't create a smooth animation.

Here's my proposal:
![onmodalhideearly](https://user-images.githubusercontent.com/3331946/29252396-d841e77e-8098-11e7-9f05-bf6b43b53b18.gif)

The plus button changes colour almost immediately with the modal creating a seamless effect. This creates a much better UI experience in my opinion.

Here's how I have achieved this effect:
```
  _close = async () => {
    this.props.onModalHideEarly();
    this.backdropRef.transitionTo({ opacity: 0 }, this.props.backdropTransitionOutTiming);
    this.contentRef[this.props.animationOut](this.props.animationOutTiming).then(() => {
      this.setState({ isVisible: false });
      this.props.onModalHide();
    });
  };
```
Ps. this is only a part of the commit.

I have forked the repo and can submit a PR request if you think this enhancement is worthwhile.

**Comment by mmazzarolo** [comment]
Hey @alexkuc!
I think I understand what you're trying to achieve, but you should already be able to do your own logic both when the hide animation starts (right before setting the `visible` prop of the modal to `false`) and when it ends (in the `onModalHide` callback).  

The following snippet should reproduce the same behaviour you're requesting, let me know if I'm missing something 👍 

```javascript
export default class YouFirstScreen extends Component {
  state = {
    isModalVisible: false
  }

  _showModal = () => this.setState({ isModalVisible: true })

  _hideModal = () => this.setState({ isModalVisible: false })

  _handleClose = () => {
    // First, do the logic you'd  do inside your onModalHideEarly()
   YourLogicBeforeHidingTheModal
    // Then, start the close animation
    this._hideModal();
    // From now on you'll know when the animation has ended thanks to onModalHide()
  }

  _handleModalClosePostAnimation = () => {
    // Here you can safely assume the modal animation has just ended 
  }

  render () {
    return (
      <View style={{ flex: 1 }}>
        <TouchableOpacity onPress={this._showModal}>
          <Text>Show the modal</Text>
        </TouchableOpacity>
        <Modal isVisible={this.state.isModalVisible} onModalHide={this._handleModalClosePostAnimation}>
          <View style={{ flex: 1 }}>
            <TouchableOpacity onPress={this._handleClose}>
                <Text>Close</Text>
             </TouchableOpacity>
          </View>
        </Modal>
      </View>
    )
  }

}
```

**Comment by mmazzarolo** [comment]
Closing, feel free to open another issue/submit the PR if needed 👍
