### ISSUE TITLE
Opening a Modal from a Modal

### ISSUE THREAD

**Issue by impuulse** [react-native-community/react-native-modal#58]
```
<Modal isVisible={this.props.isFirstModalVisible}>
    <View>
        <TouchableOpacity onPress={() => this.props.showSecondModal()}>
               <Text>{'show second modal'}</Text>
         </TouchableOpacity>
    </View>
</Modal>

<Modal isVisible={this.props.isSecondModalVisible}>
    <View>
        <Text>{'Hello World'}</Text>
    </View>
</Modal>

<TouchableOpacity onPress={() => this.props.showFirstModal()}>
     <Text>{'show first modal'}</Text>
</TouchableOpacity>
```
second modal doesn't open, i'm using redux
plz help

**Comment by mmazzarolo** [comment]
I'm sorry @impuulse but the info you're providing are not detailed enough for me to understand your issue.  

Please take a look at the issue template below and make sure to complete all the required steps, it will speed up the issue resolution.  

---

### When reporting a bug, please be sure to check if the issue still persists with react-native original modal:
Under the hood `react-native-modal` uses react-native original [Modal component](https://facebook.github.io/react-native/docs/modal.html).  
Before reporting a bug, try swapping `react-native-modal` with react-native original Modal component to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior
