### ISSUE TITLE
backdropColor not showing on Samsung S6

### ISSUE THREAD

**Issue by FacuAcosta** [react-native-community/react-native-modal#59]
Hi people! I'm having a weird issue. If I run my application on a Samsung S6 with Android 7.0.0 the backdropColor is not showing.
![screenshot_20170818-101016](https://user-images.githubusercontent.com/19332669/29453084-560ac0ee-8400-11e7-95dc-5055f4d571a2.png)

I've tried the same app in an iOS 10.3 simulator and is doing good. I also tried it in the following Android devices and it's also doing good:

- HTC Desire, Android 4.4.2

- Nexus 5, Android 6.0.0

- Nexus 5, Android 7.0.0

Do you know what's going on?

"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-modal": "^2.5.0",

**Comment by mmazzarolo** [comment]
Hello @FacuAcosta,
Under the hood `react-native-modal` uses react-native original [Modal component](https://facebook.github.io/react-native/docs/modal.html).  
Cold you try swapping `react-native-modal` with react-native original Modal component to check if the problem persists?

**Comment by FacuAcosta** [comment]
Hi @mmazzarolo , I tried the Modal component and it's even worse because the background is not even showing on iOS. This behaviour is so weird because if it's working on Nexus 5 7.0.0 it "should" work on Samsung S6 7.0.0

**Comment by mmazzarolo** [comment]
@FacuAcosta You mean that the default modal works correctly on Nexus5 but not on Samsung S6?
I guess you should report the issue on [react native repo](https://github.com/facebook/react-native/issues) then 🤔

**Comment by FacuAcosta** [comment]
No, I mean that your modal is working everywhere except on Samsung S6. Maybe is because of Samsung's TouchWiz layer they use over Android?

**Comment by mmazzarolo** [comment]
@FacuAcosta https://github.com/facebook/react-native/issues/13035

**Comment by FacuAcosta** [comment]
@mmazzarolo Yeah, I'll try to see a workaround to fix this. Thanks for answering so fast!

**Comment by mmazzarolo** [comment]
Thank you man! 
Post here any progress/doubt about the issue, I'll try to help as much as I can (P.S.: This week I'm still on holiday and I can't test it).

**Comment by FacuAcosta** [comment]
It seems that I've found what it's causing the bug, but this s*it makes no sense at all. If you activate Js Dev Mode ( _DEV_ = true), the modal is showing on Android with background and everything. If you deactivate Js Dev Mode (_DEV_ = false), the background is not shown. Do you know what can we do to fix this?

**Comment by mmazzarolo** [comment]
Did you already tried building an APK with a release flavour and try it on a real device?  
From my experience the Js Dev Mode can be a bit buggy sometimes.

**Comment by FacuAcosta** [comment]
That´s the first thing I did. I built the app for Release on iOS and it´s working fine, but if I build the APK for Android the problem pesists. I´ve seen that when i close the modal, the backdrop is shown for a milisecond, so maybe It has something to do with the zIndex?

**Comment by FacuAcosta** [comment]
Okay, so I've found a quick solution. If anyone is having the same issue, just wrap the modal content with a <View /> container that has style like:

`container: {
	    flex: 1,
	    justifyContent: 'center',
	    padding: 20,
	    backgroundColor: (Platform.OS === 'ios') ? 'rgba(0, 0, 0, 0.01)' : 'rgba(0, 0, 0, 0.7)'
  },`

This will work on iOS perfectly, but on Android we will have a little transparent margin. To fix this, go to node_modules/react-native-modal/index.js, import Platform module and change the styling of the modal like:

`<View
          ref={ref => (this.contentRef = ref)}
          style={[{ margin: (Platform.OS === 'ios') ? deviceWidth * 0.05 : 0 }, styles.content, style]}
          {...otherProps}
        >
          {children}
</View>`

I don't know why the backdropColor is not showing on Android when _DEV_ = false and on release APK on Android, but this will fix it.

**Comment by mmazzarolo** [comment]
Thank you so much @FacuAcosta, maybe it should be worth mentioning the issue in the React-Native repo too?  
What do you think?

**Comment by FacuAcosta** [comment]
@mmazzarolo If you have time and do some testings on the emulator so we are sure it´s not just an isolated problem that I had, that would be nice. The process is simple, create an app with a modal, show it and run it on Android with `_DEV_=false`. I had problems with the react-native Modal too on Android when trying to close the Modal with a button within it, so many headaches.

**Comment by mmazzarolo** [comment]
I'm closing the issue for now, feel free to write here again if @FacuAcosta solution doesn't work for you and I'll re-open the issue.
