### ISSUE TITLE
Modal margin improvement ?

### ISSUE THREAD

**Issue by Louis-T** [react-native-community/react-native-modal#60]
Hi,
First of all, thanks for this very useful package !

I just wanted to point out that the margin of the modal's content (`deviceWidth * 0.05`) seems to be problematic in some case (at least in mine, with the latest android emulator).

I noticed that since the margin value is not rounded, I sometimes get a "blank" pixel that I can't fill (for example, when trying to make some buttons at the bottom). 
It can be simply solved by using a custom margin of `Math.round(deviceWidth * 0.05)`, and I thought that maybe it would be interesting to put it directly in the package !

I am using the last version (3.0.2) with react-native 0.47.1. The "problem" appears on the emulator with android 7.0.

I enclosed some pictures to help visualize what I meant : 

![margin_not_rounded](https://user-images.githubusercontent.com/2038811/29585379-36ee642e-8787-11e7-8cb6-860498d5a80f.png)
Here with the current margin

&nbsp;

![margin_rounded](https://user-images.githubusercontent.com/2038811/29585332-0eaf6ac6-8787-11e7-9429-a56e9e8e0b05.png)
Here with the rounded margin (no more white pixel line at the bottom).

Bye

PS : if this behavior is intended, please forgive me for the disturbance.

**Comment by mmazzarolo** [comment]
Hi @Louis-T, thank you for opening the issue.  
I fired up the emulator and did some tests and I couldn't reproduce the issue.  
Could it be caused by the emulator zoom of the emulator? Are you using still having the issue with the 100% zoom?  🤔

**Comment by Louis-T** [comment]
Hi, I do not use the zoom on the emulator (always 100%).
But I get this bug on an XPS 13 with a 3200x1800 screen (that could be the problem).

I tried to change the Ubuntu scale (which I had set to 1.62 because 3200x1800 on a 13" screen is a little small !) but I still get the 1px white line when I'm with the native scale (1x)...

Anyway, it's not really problematic since I'm able to override the margin to use the rounded one !
Thanks for giving it a shot :+1: 

Bye
