### ISSUE TITLE
onBackdropPress not functioning as expected on Android

### ISSUE THREAD

**Issue by vanhoutk** [react-native-community/react-native-modal#63]
So I've been trying to use the newly implemented onBackdropPress to close a modal when the backdrop is pressed. As it wasn't working originally, I decided to replace the functionality with a console log to see when onBackdropPress is being called. 

From what I can see, the only times it's firing off are when I open the modal originally, and when I close the modal using onBackButtonPress. Nothing seems to be triggered when I tap the modal itself.

I've attempted to move the modal to different levels in component structure (I have a number of child components and ideally wanted to call it from the very last child), but it seems to function the same regardless of where it is.

My usage of the modal looks like this:

```
<Modal
    isVisible = {this.props.visible}
    backdropColor = 'red'
    onBackdropPress = {console.log("Pressed")}
    onBackButtonPress = {this.props.closeModal}>
    <View style = {styles.modalView}>
        ...
    </View>
</Modal>
```

Dependencies in use:
react-native-modal 3.1.0.
react 16.0.0-alpha.12
react-native 0.47.2

I'm running on a Samsung Galaxy S5.

Here's a link to a basic expo app which shows the issue: [https://github.com/vanhoutk/modaltest](https://github.com/vanhoutk/modaltest)

**Comment by mmazzarolo** [comment]
Hey @vanhoutk, thank you for submitting the issue, could you provide a bit more info on the matter? 
Unfortunately your snippet in not enough for debugging it.  

### When reporting a bug, please be sure to include the following:
- [x] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [x] The behavior you expect to see, and the actual behavior

**Comment by vanhoutk** [comment]
@mmazzarolo, I've edited my original issue to provide more information. If there's anything else you'd like me to add just let me know.

**Comment by mmazzarolo** [comment]
Thanks, the following won't work though: 
```
onBackdropPress = {console.log("Pressed")}
```

Try replacing it with:
```
onBackdropPress = {() => console.log("Pressed")}
```

Let me know if the issue still persists.

**Comment by vanhoutk** [comment]
Thank you, that fixed it. Oddly the former still actually logs "Pressed" any time the modal is open or closed, which is why I didn't realise the need for `() =>` to be included.

**Comment by lukecwilliams** [comment]
@vanhoutk that call would happen anytime the component is mounted - console.log is called, and the resulting value (null) is set to onBackdropPress.
