### ISSUE TITLE
Not able to Trigger Android BackButton Action, when Modal is opened.

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [react-native-community/react-native-modal#67]
I am not able to trigger Android BackButton when modal is opened.
Here is my code

```
BackAndroid.addEventListener("hardwareBackPress", () => {
	Alert.alert("Sample", "Backbutton Pressed");
	if(this.state.isModalVisible) {
		this.setState({isModalVisible: false});
                return true
	}
	else {
		if (this.props.navigator.getCurrentRoutes().length > 1) {
			this.props.navigator.pop()
			return true
		} else {
			return false
		}
	}
})
```

**Comment by mmazzarolo** [comment]
Hi, there's a modal prop you can use to achieve the desired effect: `onBackButtonPress`

**Comment by xieliying** [comment]
There's a Modal prop `onRequestClose` you can use, like this: 
`
<Modal animationType="fade" onRequestClose={() => {alert("When you press Back Button, it will alert.")}}>

</Modal>
`
