### ISSUE TITLE
No animationOut instead of slideOutDown

### ISSUE THREAD

**Issue by seb0zz** [react-native-community/react-native-modal#68]
I've got a really strange behavior with this library and react-native 0.48. I am using the modal with default props. When I open the modal it properly uses the `slideInUp` animation. When I close the modal no animation is used even though it should be `slideOutDown` by default. Strangely - when I open the modal, then put the app into background, open the app again and close the modal afterwards - it will properly use the slideOutDown animation 🤔

**Comment by brunolemos** [comment]
I don't get any animation out as well, tried `bounceOut`.
RN 0.48.2.

**Comment by brunolemos** [comment]
It's working fine for me now. The problem was that the code was like this:
```
<View>
    {isVisible && <MyModal isVisible={isVisible} />}
</View>
```

But you should not remove the modal from the tree, so this works:
<View>
    <MyModal isVisible={isVisible} />
</View>
```

**Comment by mmazzarolo** [comment]
Thanks @brunolemos for answering :)
@seb0zz could you provide an example of your issue?

**Comment by seb0zz** [comment]
@brunolemos your hint was good 👍  Have to check something. Will re-open this issue if the problem remains.

**Comment by therealaldo** [comment]
I'm running into this same problem where the out animation isn't properly working. I've tried using different out animations and the modal continues to just fade out when closed.

React 16.0.0.alpha-12
React Native 0.48.3
React Native Modal 3.1.0

**Comment by mmazzarolo** [comment]
@therealaldo did you already check if the issue persists in release mode? also, are you on iOS or Android?

**Comment by therealaldo** [comment]
@mmazzarolo I haven't checked to see if it works in release mode yet, and I'm on iOS currently. Going to check to see if it works in release mode.

**Comment by therealaldo** [comment]
@mmazzarolo The issue still persists while running in Release mode.

**Comment by therealaldo** [comment]
Weirdly enough, the issue went away. I deleted some extra this.setState stuff when I would open the modal which I think was causing the issue.

**Comment by mmazzarolo** [comment]
Glad you solved it :)
