### ISSUE TITLE
onBackdropPress function is not working 

### ISSUE THREAD

**Issue by atchuthsai468** [react-native-community/react-native-modal#82]
this is my latest code i divide the  flex in two different parts i applied  onBackdropPress function to  blue color part but modal will not be colsed  
![screen shot 2017-10-30 at 2 48 38 pm](https://user-images.githubusercontent.com/32636257/32163437-516a661e-bd82-11e7-9a56-0285f7e2cc0f.png)

import React, { Component } from 'react';
import { Modal, Text, TouchableHighlight,TouchableOpacity, View } from 'react-native';

export default class ModalExample extends Component {

  state = {
    modalVisible: false,
  }

  setModalVisible(visible) {
    this.setState({modalVisible: visible});
  }

  render() {
    return (
      <View style={{marginTop: 22}}>
        <Modal
          animationType="slide"
          transparent={false}
        
          visible={this.state.modalVisible}
          onBackDropPress ={() => {alert("Modal has been closed.")}}
          >
         <View style={{flex:1}}>
          <View style={{flex:40,backgroundColor:'red'}}>
            <Text>Hello World!</Text>

            <TouchableHighlight onPress={() => {
              this.setModalVisible(!this.state.modalVisible)
            }}>
              <Text>Hide Modal</Text>
            </TouchableHighlight>

          </View>

          <View style={{flex:60,backgroundColor:'blue'}}>

          </View>

         </View>
        </Modal>

        <TouchableHighlight onPress={() => {
          this.setModalVisible(true)
        }}>
          <Text>Show Modal</Text>
        </TouchableHighlight>

      </View>
    );
  }
}

**Comment by mmazzarolo** [comment]
Hi @atchuthsai468,
what is the alert function you're calling? it doesn't seem to be defined anywhere

**Comment by atchuthsai468** [comment]
just now modified code check once

**Comment by mmazzarolo** [comment]
I'm sorry, I can't understand what you are saying :(

**Comment by ghoshabhi** [comment]
What is the `onRequestClose` function ? Is it not `onBackDropPress` ?

**Comment by atchuthsai468** [comment]
sry not onRequestClose just now i modified my code can you check once

**Comment by mmazzarolo** [comment]
@atchuthsai468 you still have an "alert" function not defined anywhere in your code. 

Please @atchuthsai468 try [the example here](https://github.com/react-native-community/react-native-modal/tree/master/example) first, then adjust one of that modals to better suit your needs.

**Comment by thanhpcc96** [comment]
@atchuthsai468 style={{flex:1}} caused this problem

**Comment by mmazzarolo** [comment]
@atchuthsai468 onBackDropPress should work with `flex: 1` too, could you provide a reproducible example?

**Comment by atchuthsai468** [comment]
I remove style={{flex:1}} in main view. but it is not working
