### ISSUE TITLE
Modal temporary closes when App is minimized by Menu Button . Android . 

### ISSUE THREAD

**Issue by sadi304** [react-native-community/react-native-modal#83]
Hello, 
i have used both the react native official modal and this one. I am asking for a help. Is there any way to prevent this behavior -> when the modal is open, if i press the menu button of the mobile (built in one) the modal flickers and closes temporary exposing the background view. Please see the attached video for clarification .
![20171021_163835](https://user-images.githubusercontent.com/8942965/31850922-585d44f2-b67d-11e7-80e0-ad473f339abf.gif)

**Comment by mmazzarolo** [comment]
Hi @sadi304.
Never noticed it, but I still can't understand one thing: does it happen with the native modal too?

**Comment by sadi304** [comment]
@mmazzarolo 
yeah same thing with native modal too. Don't know if there's an easy fix with style properties.

**Comment by mmazzarolo** [comment]
Ouch, if it doesn't work with the native one I guess we should report it to the official react-native repo.  
From your screenshot it seems you're not using a stock version of Android, do you know if the same issue happens on it?  
Could you give it a try on a Nexus5 for example? (A simulator might be enough too)

**Comment by sadi304** [comment]
Surprisingly this is not happening on the emulator. I have just tested with Nexus 6 . API 23 (Genymotion) .
I was using Samsung Note 5, (Android Version 7.0) . Maybe the problem is with the device or perhaps that version from T-Mobile :/ . closing . Thanks for quick reply.
