### ISSUE TITLE
Delay & no animation

### ISSUE THREAD

**Issue by abdulrahman-khankan** [react-native-community/react-native-modal#84]
Hi,

The modal takes too long to open and I cannot see any animations. When using the Modal from react-native it works fine and I can see the animation.

I tried including a console.log message and it prints right away, but it takes about 2 seconds after that for the modal to open.

Using 
-react-native: 0.48.3
-react-native-modal: 4.1.0 
And developing on android.

Please note that I have the exact same behaviour when I use the example. It takes too long and no animation at all.

Any special configuration I should include?

**Comment by mmazzarolo** [comment]
Hi @abdulrahman-khankan 
Are you working in debugging/development mode?
Try building a release APK and let me know if the issue persists.

**Comment by abdulrahman-khankan** [comment]
@mmazzarolo works perfectly in release!
I suggest adding this as a note in the README.

Thank you very much for your fast response! :)

**Comment by lyz19890927** [comment]
Why not working in debugging/development mode? It's frustrating.

**Comment by mmazzarolo** [comment]
Unfortunately It is not an issue of the component but more of React Native itself.
