### ISSUE TITLE
Issue in Expo with Screen Orientation

### ISSUE THREAD

**Issue by LastxTemplar** [react-native-community/react-native-modal#85]
### When reporting a bug, please be sure to include the following:
- [ ] The same happens with the original modal from react-native
- [ ] Get code from here https://pastebin.com/GjipbY1i
- [ ] using "react-native-modal": "^4.1.0", on iOS
- [ ] I expect the modal to be shown in a landscape view, not switch to portrait

Short video on what is happening:
https://youtu.be/zeNi1UG2jZs

**Comment by blackflamedigital** [comment]
Managed to fix this by adding
`supportedOrientations={['landscape']}`
to the modal as per documentation [here](https://facebook.github.io/react-native/docs/modal.html#supportedorientations)

**Comment by mmazzarolo** [comment]
thanks @blackflamedigital 
@LastxTemplar could you give @blackflamedigital solution a try?

**Comment by LastxTemplar** [comment]
Hah, sorry, both usernames are mine, i solved it myself :)

**Comment by mmazzarolo** [comment]
Ah-ah! Nice :)

**Comment by henkvhest** [comment]
@mmazzarolo Had the same issue on an iPhone 5s with iOS 11.0 (15A372). Can confirm that @blackflamedigital solution worked, added the following to the modal inside index.js:

` supportedOrientations={['portrait', 'landscape']}`
