### ISSUE TITLE
Ability to swipe up/down to make modal appear/disappear?

### ISSUE THREAD

**Issue by sunweiyang** [react-native-community/react-native-modal#87]
I need to create a modal that can be summoned by a swipe up and dismissed by a swipe down. Is that currently possible with react-native-modal?

(Ideally the animation would track the swipe at any intermediate swipe position as well.)

**Comment by dbartelmus** [comment]
Im not related to this project but I think it’s only possible with predefined points in view window (20px on bottom ex.), then you just need to add swipe like action related to closing action.

**Comment by mmazzarolo** [comment]
> I need to create a modal that can be summoned by a swipe up and dismissed by a swipe down. Is that currently possible with react-native-modal?

Nope, it is not currently supported unfortunately.
@dbartelmus is on the right path in my opinion. 
Anyone willing to give it a shot in a PR?
