### ISSUE TITLE
Avoiding keybord squashes a view on top of the screen on android

### ISSUE THREAD

**Issue by LorandP** [react-native-community/react-native-modal#91]
I have some views, two buttons and a textInput in my modal. 
I have used the avoidKeyboard property and when the keyboard shows, my view that holds the textInput is squashed on top of the screen.
I already use _android:windowSoftInputMode="adjustResize"_ in my manifest.

Image that shows the actual behavior
https://imgur.com/a/l6Sf4

I expected to have my view pushed up just as much as to avoid the keyboard when it was active.

**This problem reproduces on android**
- real device: Lenovo A2010-a - android version 5.1
- emulator: Pixel_2_API_26(AVD) - 8.0.0

**Version of library:**
react-native-modal: "4.1.1"
react-native: "0.50.0"

**Comment by mmazzarolo** [comment]
Hi @LorandP , thanks for submitting the issue.  
Could you give PR #89 a shot?

**Comment by LorandP** [comment]
I have already solved the problem by putting a KeyboardAwareScrollView inside the modal and put all my views inside the KeyboardAwareScrollView but I wanted to submit this for you to know. I didn't see it posted before so I thought it would help you guys know about this.

**Comment by rochapablo** [comment]
Even adding ```KeyboardAwareScrollView``` the modal still been cropped. Is there any other solution?

**Comment by rochapablo** [comment]
Solved! Here's what I did:

```
let props = {}
if (Platform.OS === 'ios') {
  props = {
    avoidKeyboard: true
  }
}

<Modal {...props} ...>
...
```

**Comment by kcbar** [comment]
Great solution @rochapablo
You can also do this in one line:
`<Modal avoidKeyboard={Platform.OS === 'ios'} ...>`

**Comment by jimji1005** [comment]
Also running into this issue.
react: 16.8.3 => 16.8.3 
react-native: 0.59.10 => 0.59.10 
"react-native-modal": "^11.3.1",
android:windowSoftInputMode="adjustResize"

If Modal isn't fullscreen or cover screen, avoidKeyboard works perfectly on ios and android.

But when its fullscreen, on android it pushes the entire modal up. (Modal has no other keyboard avoid component, just a texinput)

**Comment by jimji1005** [comment]
Modal does not get pushed up, if coverScreen is not used. basically, if coverScreen is active, then it will push the entire modal up

**Comment by jimji1005** [comment]
did some more tests

avoidKeyboard true, coverScreen false, adjustResize -> Bottom Tabbar + Modal pushed up

avoidKeyboard true, coverScreen true, adjustResize -> Modal pushed up

avoidKeyboard false, coverScreen true, adjustResize -> Modal pushed up

avoidKeyboard false, coverScreen true, adjustPan -> Modal pushed up

avoidKeyboard true, coverScreen true, adjustPan -> Modal pushed up

avoidKeyboard false, coverScreen false, adjustPan -> Modal stayed in place

Something tells me that, when coverScreen is true, keyboard avoid strategy takes the entire Modal and pushes it up

**Comment by PeterPham-robo** [comment]
> did some more tests
> 
> avoidKeyboard true, coverScreen false, adjustResize -> Bottom Tabbar + Modal pushed up
> 
> avoidKeyboard true, coverScreen true, adjustResize -> Modal pushed up
> 
> avoidKeyboard false, coverScreen true, adjustResize -> Modal pushed up
> 
> avoidKeyboard false, coverScreen true, adjustPan -> Modal pushed up
> 
> avoidKeyboard true, coverScreen true, adjustPan -> Modal pushed up
> 
> avoidKeyboard false, coverScreen false, adjustPan -> Modal stayed in place
> 
> Something tells me that, when coverScreen is true, keyboard avoid strategy takes the entire Modal and pushes it up

Thank you so much! The last one that working for me 👍
