### ISSUE TITLE
Content is not scrollable?

### ISSUE THREAD

**Issue by nichesoftgh04** [react-native-community/react-native-modal#93]
### Problem: 
When content of the modal is not fitting inside the modal then there should be a feature to enable scroll bar. If this option already exists then it should be documented properly.. right now i don't see anything related to scrollbar?

**Comment by nichesoftgh04** [comment]
Is this repository still maintained?

**Comment by mmazzarolo** [comment]
@nichesoftgh04 Yes, I'm sorry but I'm just really busy right now (pre-christmas), I'll try to take a closer look at the issues next week. 

However, your issue should be solved by adding a ScrollView inside the content modal, give it a try.

**Comment by BalalRaza** [comment]
I have a FlatList inside Modal. When it has lot of rows, it just overflows and there is no scrolling. We could have something like a max-width or something, so that for scrollable lists, the modal expands only upto that mark and the list hence becomes scrollable.

**Comment by mmazzarolo** [comment]
@BalalRaza did you already tried playing with the style of the modal?
Try setting a fixed width/height for example.

**Comment by krishnadusad** [comment]
Have the same issue: flatlist inside modal. Wondering what the solution was.

**Comment by lekeCoder** [comment]
a temporary fix l used what to **comment out** `swipeDirection` on the `Modal`
