### ISSUE TITLE
question: behaviour seem to fall back to standard react native Modal

### ISSUE THREAD

**Issue by bnii** [react-native-community/react-native-modal#98]
hi, 
this is most probably not a real issue and I should have been figured out myself already, but I hope somebody catch my mistake at the first sight.

The modal component in the below example doesn't seem to take into consideration any specific props - neither the animation and backdrop ones, and component behaves like the default Modal from React Native.

My expectation would be that the background is getting "blurred" and the modal is sliding in/out like i see even the simplest provided example, but this doesn't.

This can be tried out on this [expo snack](https://snack.expo.io/H1UflFcQf).

```javascript 
      <View
        style={{
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
        }}>
        <Modal
          visible={this.state.modalVisible}
          onRequestClose={this.close}
          backdropColor="black"
          backdropOpacity={1}
          animationInTiming={1000}
          animationOutTiming={1000}
          backdropTransitionInTiming={1000}
          backdropTransitionOutTiming={1000}
          animationIn="slideUpIn">
          animationOut="slideDownOut">
          <View
            style={{
              backgroundColor: 'white',
              padding: 22,
              justifyContent: 'center',
              alignItems: 'center',
              borderRadius: 4,
              borderColor: 'rgba(0, 0, 0, 0.1)',
            }}>
            {this.renderItems()}
          </View>
        </Modal>
      </View>
```

thanks!

**Comment by mmazzarolo** [comment]
Hi @bnii !
That's weird, could you try with a simpler example on expo and see if it works correctly?  
You could try directly with the one you can find in the README.

**Comment by bnii** [comment]
ok, it was my ignorance as expected.

as i was trying to replace an existing standard `<Modal/>` , I forgot to replace the `visible` prop and I read it again and again as `isVisible` - it was really misleading that a modal actually popped up and got hidden as expected - as i guess the props were passed down to the backing stock `<Modal/>` directly .

maybe it would worth to "block" the propagation of the `visible` & the other stock Modal props - hope i was the last who spent half day on this : )

anyway, thanks for the component and the help
